#!/usr/bin/env python3
"""codex-skill-sync.py - single-source -> Codex SKILL.md skill generation.

Issue #555 (companion to codex-power-pack epic cooneycw/codex-power-pack#64,
story B1, ratified hybrid SoT): evolved the flat custom-prompt surface
(scripts/codex-prompt-sync.py, issue #446, retired at the #556 cutover) into
real Codex skills. ADR 0001 section 5 fixes the source of
truth as .claude/commands/<family>/*.md; this script emits checked-in
per-command skill directories under codex/skills/:

    codex/skills/<family>-<command>/
        SKILL.md        # frontmatter (name/description) + harness adaptations
                        # + body inline (progressive disclosure: short bodies)
        reference.md    # full command body (long bodies load on demand)
        scripts/<name>  # helper scripts the body references, bundled byte-identical

Usage:
    codex-skill-sync.py                      # --check (default): exit 1 on drift
    codex-skill-sync.py --check [family...]  # check some or all families
    codex-skill-sync.py --write [family...]  # (re)generate codex/skills/
    codex-skill-sync.py --install            # copy skill dirs -> ~/.codex/skills/

Harness transforms: source frontmatter is replaced by Codex skill frontmatter
(name + description with trigger words front-loaded, JSON-escaped so YAML stays
valid - the retired codex-skill-gen.py's #312 quoting bug); /family:cmd slash
refs are rewritten to the /family-cmd skill names that actually exist in this
surface; Claude-only constructs detected in the body (native worktree tools,
AskUserQuestion, MCP tools, /plugin refs, CLAUDE.md paths) each get a targeted
Codex fallback bullet in a generated adaptations block.

Ownership rule: the script manages ONLY skill dirs whose SKILL.md carries its
GENERATED marker. Hand-curated skill dirs are never overwritten or
orphan-deleted. Mirrors the plugin-sync.sh idiom:
deterministic, git-free (byte-for-byte local diff, no network) so it runs in
the git-less CI validate container. Reconcile drift by editing the SOURCE
(.claude/commands/<family>/) then re-running with --write.
"""

from __future__ import annotations

import argparse
import json
import re
import shutil
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
SOURCE_ROOT = REPO_ROOT / ".claude" / "commands"
SCRIPTS_ROOT = REPO_ROOT / "scripts"
OUTPUT_ROOT = REPO_ROOT / "codex" / "skills"

# Same packaged families as plugin-sync.sh (ADR 0001 target design), minus the
# `codex` family: those commands orchestrate the Codex CLI itself, so shipping
# them INTO Codex as skills would be circular.
FAMILIES = [
    "browser", "cicd", "claude-md", "cpp", "documentation", "evaluate",
    "flow", "github", "project", "qa", "second-opinion", "secrets",
    "security", "self-improvement",
]

# Per-family source basenames excluded from generation:
#   cpp: the legacy symlink installer retired in Phase B4.
#   self-improvement/memory.md: Codex ships the hand-curated equivalent
#     codex/cpp-memory.md (issue #433; relocated out of the retired codex/prompts/
#     flat surface at the #556 cutover); a generated variant would duplicate it.
EXCLUDE: dict[str, set[str]] = {
    "cpp": {"init.md", "status.md", "update.md"},
    "self-improvement": {"memory.md"},
}

MARKER_PREFIX = (
    "<!-- GENERATED by claude-power-pack - scripts/codex-skill-sync.py;"
)

# Codex truncates long skill lists, so descriptions stay short with their
# trigger words up front.
DESCRIPTION_MAX = 150

# Progressive disclosure: bodies at or under this many lines inline into
# SKILL.md; longer bodies move to reference.md behind a pointer.
INLINE_MAX_LINES = 100

# Claude-only construct classes -> the Codex fallback bullet emitted when any
# of the class's patterns appears in a command body. Only detected classes are
# emitted, so short clean commands carry no adaptations block at all.
ADAPTATIONS: list[tuple[tuple[str, ...], str]] = [
    (
        ("EnterWorktree", "ExitWorktree", ".claude/worktrees", ".codex/worktrees"),
        "Codex worktrees: create them OUTSIDE the repo at"
        " `$FLOW_WORKTREE_BASE/<repo>-<branch>` when FLOW_WORKTREE_BASE is set,"
        " else a visible sibling under the repo's parent dir (`../<repo>-<branch>`,"
        " issue #133/#136) - `git worktree add \"$WORKTREE_DIR\" -b <branch>`, work"
        " inside it, then `git worktree remove <path>` from the main repo when done.",
    ),
    (
        ("AskUserQuestion",),
        "`AskUserQuestion` tool: ask the user directly in the conversation"
        " and wait for their answer.",
    ),
    (
        ("Skill tool", "Agent tool", "subagent"),
        "Claude subagent/skill dispatch: do the work inline in this session,"
        " or shell out to `codex exec` when isolation is needed.",
    ),
    (
        ("mcp__", "MCP", "playwright"),
        "MCP tools: use the MCP servers configured in `~/.codex/config.toml`,"
        " or fall back to the referenced repo scripts and CLI entry points.",
    ),
    (
        ("/plugin install", "/plugin marketplace"),
        "Claude `/plugin` install references: install the codex-power-pack"
        " equivalent plugin/skill instead.",
    ),
    (
        ("CLAUDE.md",),
        "`CLAUDE.md` references: Codex reads `AGENTS.md`; treat them as the"
        " target repo's agent-context file.",
    ),
    (
        ("`! <command>`", "the `!` prefix"),
        "Claude's `! <command>` prompt prefix: run the command in your own"
        " shell instead.",
    ),
]

BUNDLED_SCRIPTS_BULLET = (
    "Helper scripts referenced as `scripts/<name>` are bundled under"
    " `scripts/` in this skill directory (byte-identical copies from the"
    " claude-power-pack checkout); some expect sibling repo resources, so"
    " prefer a full checkout when one is available."
)


def marker_for(family: str, base: str) -> str:
    return (
        f"{MARKER_PREFIX} edit .claude/commands/{family}/{base} instead -->"
    )


def parse_frontmatter(content: str) -> tuple[dict[str, str], str]:
    """Split a leading YAML frontmatter block into a flat key map + body.

    Only top-level scalar `key: value` lines are read (that is all the command
    sources use); everything else in the block is ignored.
    """
    if not content.startswith("---"):
        return {}, content
    end = content.find("\n---", 3)
    if end == -1:
        return {}, content
    block = content[3:end]
    body = content[end + len("\n---"):].lstrip("\n")
    meta: dict[str, str] = {}
    for line in block.splitlines():
        if ":" not in line or line.startswith((" ", "\t", "#")):
            continue
        key, _, value = line.partition(":")
        value = value.strip()
        if len(value) >= 2 and value[0] == value[-1] and value[0] in "'\"":
            value = value[1:-1]
        meta[key.strip()] = value
    return meta, body


def _visible_lines(body: str) -> list[str]:
    """Body lines with HTML comment blocks and fenced code stripped out."""
    lines: list[str] = []
    in_comment = False
    in_fence = False
    for line in body.splitlines():
        stripped = line.strip()
        if in_comment:
            if "-->" in stripped:
                in_comment = False
            continue
        if stripped.startswith("<!--"):
            if not stripped.endswith("-->"):
                in_comment = True
            continue
        if stripped.startswith("```"):
            in_fence = not in_fence
            continue
        if in_fence:
            continue
        lines.append(line)
    return lines


def derive_description(meta: dict[str, str], body: str) -> str:
    """Skill-list description: source frontmatter description when present,
    else H1 title + first prose paragraph. Front-loads the trigger words and
    caps the length (Codex truncates long skill lists)."""
    desc = " ".join(meta.get("description", "").split())
    if not desc:
        title = ""
        para_lines: list[str] = []
        for line in _visible_lines(body):
            stripped = line.strip()
            if not stripped:
                if para_lines:
                    break
                continue
            if stripped.startswith("#"):
                if para_lines:
                    break
                if not title:
                    title = stripped.lstrip("#").strip()
                continue
            if stripped.startswith(("|", ">", "- ", "* ", "---")):
                if para_lines:
                    break
                continue
            para_lines.append(stripped)
        para = " ".join(para_lines)
        if title and para:
            desc = f"{title} - {para}"
        else:
            desc = title or para
        desc = " ".join(desc.split())
    if len(desc) > DESCRIPTION_MAX:
        desc = desc[:DESCRIPTION_MAX].rsplit(" ", 1)[0].rstrip(" ,;:-") + " ..."
    return desc


def derive_title(body: str) -> str:
    for line in _visible_lines(body):
        stripped = line.strip()
        if stripped.startswith("# "):
            return stripped[2:].strip()
    return ""


def detect_adaptations(body: str) -> list[str]:
    return [
        bullet
        for patterns, bullet in ADAPTATIONS
        if any(pattern in body for pattern in patterns)
    ]


_SCRIPT_REF = re.compile(r"scripts/([A-Za-z0-9._-]+\.(?:sh|py))")


def find_bundled_scripts(body: str) -> list[str]:
    """Helper-script basenames referenced by the body that exist in scripts/."""
    found: set[str] = set()
    for match in _SCRIPT_REF.finditer(body):
        name = match.group(1)
        if (SCRIPTS_ROOT / name).is_file():
            found.add(name)
    return sorted(found)


def generated_names(selected: list[str]) -> dict[tuple[str, str], str]:
    """Map (family, stem) -> skill dir name for every command being generated."""
    names: dict[tuple[str, str], str] = {}
    for family in selected:
        src_dir = SOURCE_ROOT / family
        if not src_dir.is_dir():
            raise FileNotFoundError(f"source dir not found: {src_dir}")
        for f in sorted(src_dir.glob("*.md")):
            if f.name in EXCLUDE.get(family, set()):
                continue
            names[(family, f.stem)] = f"{family}-{f.stem}"
    return names


_SLASH_REF = re.compile(r"/([a-z][a-z0-9-]*):([a-z][a-z0-9-]*)")


def rewrite_slash_refs(body: str, names: dict[tuple[str, str], str]) -> str:
    """Rewrite /family:cmd -> /family-cmd, only for refs that resolve to a
    generated skill; unknown targets (e.g. /codex:auto, /cpp:init) are left
    untouched so the adaptations block covers them."""

    def repl(match: re.Match[str]) -> str:
        family, stem = match.group(1), match.group(2)
        if (family, stem) in names:
            return f"/{family}-{stem}"
        return match.group(0)

    return _SLASH_REF.sub(repl, body)


def generate_skill(
    source_file: Path, family: str, names: dict[tuple[str, str], str]
) -> dict[str, str]:
    """Map of skill-dir-relative path -> content for one command."""
    meta, body = parse_frontmatter(source_file.read_text())
    body = rewrite_slash_refs(body, names).rstrip("\n") + "\n"
    name = f"{family}-{source_file.stem}"
    description = derive_description(meta, body)
    marker = marker_for(family, source_file.name)
    bullets = detect_adaptations(body)
    scripts = find_bundled_scripts(body)
    if scripts:
        bullets.append(BUNDLED_SCRIPTS_BULLET)

    parts: list[str] = [
        "---",
        f"name: {json.dumps(name, ensure_ascii=False)}",
        f"description: {json.dumps(description, ensure_ascii=False)}",
        "---",
        marker,
        "",
    ]
    if bullets:
        parts += [
            "## Codex harness adaptations",
            "",
            "Generated from a Claude Code command. Where the procedure"
            " references these Claude-only surfaces, adapt as follows:",
            "",
        ]
        parts += [f"- {bullet}" for bullet in bullets]
        parts.append("")

    files: dict[str, str] = {}
    if body.count("\n") <= INLINE_MAX_LINES:
        parts.append(body.rstrip("\n"))
        files["SKILL.md"] = "\n".join(parts) + "\n"
    else:
        title = derive_title(body) or name
        summary = description
        if title and summary.startswith(title):
            summary = summary[len(title):].lstrip(" -") or description
        parts += [
            f"# {title}",
            "",
            summary,
            "",
            "## Full procedure",
            "",
            "Read `reference.md` in this skill directory for the complete,"
            " authoritative procedure before acting on this skill.",
        ]
        files["SKILL.md"] = "\n".join(parts) + "\n"
        files["reference.md"] = f"{marker}\n\n{body.rstrip(chr(10))}\n"
    for script in scripts:
        files[f"scripts/{script}"] = (SCRIPTS_ROOT / script).read_text()
    return files


def expected_outputs(selected: list[str]) -> dict[str, dict[str, str]]:
    """Map skill dir name -> {relative path -> content} for selected families.

    The rewrite map always spans ALL families so cross-family refs resolve
    identically no matter which subset is being synced.
    """
    all_names = generated_names(FAMILIES)
    outputs: dict[str, dict[str, str]] = {}
    for family in selected:
        src_dir = SOURCE_ROOT / family
        for f in sorted(src_dir.glob("*.md")):
            if f.name in EXCLUDE.get(family, set()):
                continue
            outputs[f"{family}-{f.stem}"] = generate_skill(f, family, all_names)
    return outputs


def is_managed(skill_dir: Path) -> bool:
    """A skill dir is managed when its SKILL.md carries the GENERATED marker
    as the first content line after the frontmatter block."""
    try:
        content = (skill_dir / "SKILL.md").read_text()
    except OSError:
        return False
    if content.startswith("---"):
        end = content.find("\n---", 3)
        if end != -1:
            content = content[end + len("\n---"):]
    for line in content.splitlines():
        if line.strip():
            return line.startswith(MARKER_PREFIX)
    return False


def skill_files(skill_dir: Path) -> list[Path]:
    return sorted(p for p in skill_dir.rglob("*") if p.is_file())


def find_orphans(outputs: dict[str, dict[str, str]], selected: list[str]) -> list[Path]:
    """Marker-bearing skill dirs under codex/skills/ with no matching source.

    Only families in `selected` are considered so a partial-family run never
    misreads other families' outputs as orphans.
    """
    if not OUTPUT_ROOT.is_dir():
        return []
    prefixes = tuple(f"{family}-" for family in selected)
    orphans = []
    for d in sorted(OUTPUT_ROOT.iterdir()):
        if not d.is_dir() or d.name in outputs or not d.name.startswith(prefixes):
            continue
        if is_managed(d):
            orphans.append(d)
    return orphans


def run_check(selected: list[str]) -> int:
    outputs = expected_outputs(selected)
    drift = 0
    for skill, files in outputs.items():
        skill_dir = OUTPUT_ROOT / skill
        for rel, content in files.items():
            dest = skill_dir / rel
            if not dest.is_file():
                print(f"MISSING: codex/skills/{skill}/{rel}")
                drift = 1
            elif dest.read_text() != content:
                print(f"DRIFT: codex/skills/{skill}/{rel} differs from generated source")
                drift = 1
        if skill_dir.is_dir() and is_managed(skill_dir):
            for actual in skill_files(skill_dir):
                rel = actual.relative_to(skill_dir).as_posix()
                if rel not in files:
                    print(f"STALE: codex/skills/{skill}/{rel} (no longer generated)")
                    drift = 1
    for orphan in find_orphans(outputs, selected):
        print(f"ORPHAN skill: codex/skills/{orphan.name} (no matching source command)")
        drift = 1
    if drift:
        print(
            "\ncodex-skill-sync: DRIFT detected. Edit the SOURCE"
            " (.claude/commands/<family>/), then run:"
            " scripts/codex-skill-sync.py --write",
            file=sys.stderr,
        )
        return 1
    print(f"codex-skill-sync: {len(outputs)} skill(s) in sync ({', '.join(selected)})")
    return 0


def run_write(selected: list[str]) -> int:
    OUTPUT_ROOT.mkdir(parents=True, exist_ok=True)
    outputs = expected_outputs(selected)
    written = 0
    pruned = 0
    for skill, files in outputs.items():
        skill_dir = OUTPUT_ROOT / skill
        for rel, content in files.items():
            dest = skill_dir / rel
            if not dest.is_file() or dest.read_text() != content:
                dest.parent.mkdir(parents=True, exist_ok=True)
                dest.write_text(content)
                if rel.startswith("scripts/"):
                    shutil.copymode(SCRIPTS_ROOT / Path(rel).name, dest)
                written += 1
        if is_managed(skill_dir):
            for actual in skill_files(skill_dir):
                rel = actual.relative_to(skill_dir).as_posix()
                if rel not in files:
                    actual.unlink()
                    print(f"codex-skill-sync: pruned stale {skill}/{rel}")
                    pruned += 1
            for sub in sorted(skill_dir.rglob("*"), reverse=True):
                if sub.is_dir() and not any(sub.iterdir()):
                    sub.rmdir()
    removed = 0
    for orphan in find_orphans(outputs, selected):
        shutil.rmtree(orphan)
        print(f"codex-skill-sync: removed orphan skill {orphan.name}")
        removed += 1
    print(
        f"codex-skill-sync: {len(outputs)} skill(s) current"
        f" ({written} file(s) written, {pruned} stale file(s) pruned,"
        f" {removed} orphan(s) removed)"
    )
    return 0


def run_install() -> int:
    if not OUTPUT_ROOT.is_dir():
        print(f"codex-skill-sync: nothing to install ({OUTPUT_ROOT} missing)", file=sys.stderr)
        return 2
    dest_root = Path.home() / ".codex" / "skills"
    dest_root.mkdir(parents=True, exist_ok=True)
    count = 0
    for d in sorted(OUTPUT_ROOT.iterdir()):
        if not d.is_dir() or not (d / "SKILL.md").is_file():
            continue
        shutil.copytree(d, dest_root / d.name, dirs_exist_ok=True)
        count += 1
    print(f"codex-skill-sync: installed {count} skill(s) -> {dest_root}")
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Generate Codex SKILL.md skills from .claude/commands/<family>/ sources"
    )
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--check", action="store_true", help="fail on drift (default)")
    mode.add_argument("--write", action="store_true", help="(re)generate codex/skills/")
    parser.add_argument(
        "--install", action="store_true",
        help="copy codex/skills/ dirs (generated + curated) to ~/.codex/skills/",
    )
    parser.add_argument("families", nargs="*", help="subset of families (default: all)")
    args = parser.parse_args(argv)

    selected = args.families or FAMILIES
    for family in selected:
        if family not in FAMILIES:
            print(
                f"codex-skill-sync: unknown family '{family}'"
                f" (known: {' '.join(FAMILIES)})",
                file=sys.stderr,
            )
            return 2

    if args.write:
        rc = run_write(selected)
    elif args.install and not args.check:
        rc = 0  # install-only invocation
    else:
        rc = run_check(selected)

    if rc == 0 and args.install:
        rc = run_install()
    return rc


if __name__ == "__main__":
    sys.exit(main())
