"""Non-mutating latest-CPP adoption reports (issue #207)."""

from __future__ import annotations

import hashlib
import importlib.util
import json
import os
import subprocess
from pathlib import Path
from types import SimpleNamespace
from typing import Any

import pytest

MODULE_PATH = Path(__file__).resolve().parents[1] / "scripts" / "codex_skills_sync.py"
_spec = importlib.util.spec_from_file_location("codex_skills_sync_report", MODULE_PATH)
assert _spec is not None and _spec.loader is not None
sync = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(sync)

GIT_ENV = os.environ | {
    "GIT_AUTHOR_NAME": "CxPP report test",
    "GIT_AUTHOR_EMAIL": "test@example.com",
    "GIT_COMMITTER_NAME": "CxPP report test",
    "GIT_COMMITTER_EMAIL": "test@example.com",
}
FIXED_TIMESTAMP = "2026-09-07T18:00:00Z"


def _git(root: Path, *args: str) -> str:
    completed = subprocess.run(
        ["git", *args],
        cwd=root,
        env=GIT_ENV,
        check=True,
        text=True,
        stdout=subprocess.PIPE,
    )
    return completed.stdout.strip()


def _write_skill(root: Path, name: str, files: dict[str, str]) -> None:
    for rel, content in files.items():
        path = root / "codex" / "skills" / name / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")


def _source_repo(tmp_path: Path) -> tuple[Path, str]:
    source = tmp_path / "cpp"
    _write_skill(
        source,
        "flow-auto",
        {
            "SKILL.md": "<!-- GENERATED by claude-power-pack -->\nbaseline\n",
            "scripts/removed.sh": "#!/bin/sh\necho baseline\n",
        },
    )
    _git(source, "init", "-q", "-b", "main")
    _git(source, "remote", "add", "origin", sync.CPP_REPO_URL)
    _git(source, "add", ".")
    _git(source, "commit", "-q", "-m", "baseline CPP source")
    commit = _git(source, "rev-parse", "HEAD")
    _git(source, "checkout", "-q", "--detach", commit)
    return source, commit


def _configure_destination(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
    source: Path,
    pin: str,
) -> Path:
    root = tmp_path / "cxpp"
    skills = root / ".codex" / "skills"
    vendor = root / "vendor" / "claude-power-pack"
    plugins = root / "plugins"
    overlay = root / "scripts" / "codex_skills_sync.py"
    skills.mkdir(parents=True)
    vendor.mkdir(parents=True)
    plugins.mkdir(parents=True)
    overlay.parent.mkdir(parents=True)
    overlay.write_bytes(MODULE_PATH.read_bytes())

    contracts = root / ".agents" / "skill-contracts.json"
    contracts.parent.mkdir(parents=True)
    contracts.write_text(
        json.dumps(
            {
                "skills": [
                    {
                        "name": "flow-auto",
                        "package": {
                            "state": "packaged",
                            "path": "plugins/flow/skills/flow-auto",
                        },
                    }
                ]
            }
        ),
        encoding="utf-8",
    )

    monkeypatch.setattr(sync, "REPO_ROOT", root)
    monkeypatch.setattr(sync, "SKILLS_ROOT", skills)
    monkeypatch.setattr(sync, "VENDOR_DIR", vendor)
    monkeypatch.setattr(sync, "MANIFEST_PATH", vendor / "codex-skills.sha256")
    monkeypatch.setattr(sync, "PIN_PATH", vendor / "PIN")
    monkeypatch.setattr(sync, "PLUGINS_ROOT", plugins)
    monkeypatch.setattr(sync, "OVERLAY_PATH", overlay)

    _, by_skill, _ = sync._prepare_source_payloads(source, commit=pin)
    sync._write_skill_payload(skills / "flow-auto", by_skill["flow-auto"])
    sync._write_skill_payload(
        plugins / "flow" / "skills" / "flow-auto", by_skill["flow-auto"]
    )
    sync._write_pin(pin)
    assert sync.run_write() == 0

    _git(root, "init", "-q", "-b", "main")
    _git(root, "add", ".")
    _git(root, "commit", "-q", "-m", "reviewed CxPP baseline")
    return root


def _make_target(source: Path) -> str:
    _git(source, "switch", "-q", "main")
    flow_auto = source / "codex" / "skills" / "flow-auto"
    (flow_auto / "SKILL.md").write_text(
        "<!-- GENERATED by claude-power-pack -->\ntarget\n", encoding="utf-8"
    )
    (flow_auto / "scripts" / "removed.sh").unlink()
    (flow_auto / "reference.md").write_text("new reference\n", encoding="utf-8")
    _write_skill(
        source,
        "flow-wave",
        {"SKILL.md": "<!-- GENERATED by claude-power-pack -->\nnew skill\n"},
    )
    _write_skill(
        source,
        "claude-md-help",
        {"SKILL.md": "<!-- GENERATED by claude-power-pack -->\nexcluded\n"},
    )
    _write_skill(
        source,
        "project-next",
        {"SKILL.md": "<!-- GENERATED by claude-power-pack -->\ncollision\n"},
    )
    _git(source, "add", "-A")
    _git(source, "commit", "-q", "-m", "latest CPP source")
    target = _git(source, "rev-parse", "HEAD")
    _git(source, "checkout", "-q", "--detach", target)
    return target


def _tree_bytes(root: Path) -> dict[str, bytes]:
    return {
        path.relative_to(root).as_posix(): path.read_bytes()
        for path in root.rglob("*")
        if path.is_file() and ".git" not in path.relative_to(root).parts
    }


def _reported_json(output: str) -> tuple[dict[str, Any], str]:
    lines = output.splitlines()
    encoded = next(line.removeprefix("REPORT_JSON=") for line in lines if line.startswith("REPORT_JSON="))
    digest = next(
        line.removeprefix("REPORT_SHA256=")
        for line in lines
        if line.startswith("REPORT_SHA256=")
    )
    return json.loads(encoded), digest


@pytest.fixture
def report_fixture(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> tuple[Path, Path, str, str]:
    source, pin = _source_repo(tmp_path)
    root = _configure_destination(tmp_path, monkeypatch, source, pin)
    target = _make_target(source)
    return root, source, pin, target


def test_complete_drift_is_stable_successful_data_and_never_mutates(
    report_fixture: tuple[Path, Path, str, str],
    capsys: pytest.CaptureFixture[str],
) -> None:
    root, source, pin, target = report_fixture
    before = _tree_bytes(root)
    capsys.readouterr()

    assert sync.run_source_report(source, target, generated_at=FIXED_TIMESTAMP) == 0

    output = capsys.readouterr().out
    report, digest = _reported_json(output)
    canonical = json.dumps(report, sort_keys=True, separators=(",", ":"))
    assert digest == hashlib.sha256(canonical.encode()).hexdigest()
    assert report["schema_version"] == 1
    assert report["complete"] is True
    assert report["generated_at"] == FIXED_TIMESTAMP
    assert report["status"] == "drift"
    assert report["baseline"]["pin_commit"] == pin
    assert report["target"]["commit"] == target
    assert report["counts"] == {
        "added": 2,
        "removed": 1,
        "changed": 1,
        "drift": 4,
        "excluded_source_skills": 1,
        "native_collisions": 1,
        "missing_plugin_destinations": 1,
    }
    assert report["changes"] == {
        "added": ["flow-auto/reference.md", "flow-wave/SKILL.md"],
        "removed": ["flow-auto/scripts/removed.sh"],
        "changed": ["flow-auto/SKILL.md"],
    }
    assert report["omissions"] == {
        "excluded_families": [
            {"family": "agents-md", "skills": []},
            {"family": "claude-md", "skills": ["claude-md-help"]},
        ],
        "native_collisions": ["project-next"],
        "new_skills_missing_plugin_destinations": [
            {"skill": "flow-wave", "reason": "no-contract-record"}
        ],
    }
    assert "CODEX_UPSTREAM_REPORT: ok" in output
    assert _tree_bytes(root) == before

    assert sync.run_source_report(source, target, generated_at=FIXED_TIMESTAMP) == 0
    repeated_output = capsys.readouterr().out
    repeated_report, repeated_digest = _reported_json(repeated_output)
    assert repeated_output == output
    assert repeated_report == report
    assert repeated_digest == digest


def test_current_target_is_also_a_complete_success(
    report_fixture: tuple[Path, Path, str, str],
    capsys: pytest.CaptureFixture[str],
) -> None:
    _, source, pin, _ = report_fixture
    _git(source, "checkout", "-q", "--detach", pin)

    assert sync.run_source_report(source, pin, generated_at=FIXED_TIMESTAMP) == 0

    report, _ = _reported_json(capsys.readouterr().out)
    assert report["status"] == "current"
    assert report["changes"] == {"added": [], "removed": [], "changed": []}
    assert report["counts"]["drift"] == 0


def test_executable_bit_only_change_is_reported_and_changes_payload_identity(
    report_fixture: tuple[Path, Path, str, str],
    capsys: pytest.CaptureFixture[str],
) -> None:
    _, source, pin, _ = report_fixture
    _git(source, "checkout", "-q", "--detach", pin)
    mode_only = source / "codex" / "skills" / "flow-auto" / "scripts" / "removed.sh"
    mode_only.chmod(0o755)
    _git(source, "add", "codex/skills/flow-auto/scripts/removed.sh")
    _git(source, "commit", "-q", "-m", "make helper executable")
    target = _git(source, "rev-parse", "HEAD")

    assert sync.run_source_report(source, target, generated_at=FIXED_TIMESTAMP) == 0

    report, _ = _reported_json(capsys.readouterr().out)
    assert report["changes"] == {
        "added": [],
        "removed": [],
        "changed": ["flow-auto/scripts/removed.sh"],
    }
    assert report["counts"]["drift"] == 1
    assert (
        report["baseline"]["adapted_payload_sha256"]
        != report["target"]["adapted_payload_sha256"]
    )


def test_uncommitted_baseline_mode_change_is_an_execution_error(
    report_fixture: tuple[Path, Path, str, str],
    capsys: pytest.CaptureFixture[str],
) -> None:
    root, source, _, target = report_fixture
    generated = root / ".codex" / "skills" / "flow-auto" / "scripts" / "removed.sh"
    generated.chmod(0o755)
    before = _tree_bytes(root)

    assert sync.run_source_report(source, target, generated_at=FIXED_TIMESTAMP) == 2

    captured = capsys.readouterr()
    assert "CODEX_UPSTREAM_REPORT: fail" in captured.out
    assert "payload mode differs from CxPP commit" in captured.err
    assert "REPORT_JSON=" not in captured.out
    assert _tree_bytes(root) == before


def test_latest_resolution_returns_the_single_main_commit(
    report_fixture: tuple[Path, Path, str, str],
) -> None:
    _, source, _, target = report_fixture

    assert sync._resolve_latest_cpp_commit(str(source)) == target


@pytest.mark.parametrize(
    "stdout",
    [
        "",
        "bad\trefs/heads/main\n",
        ("a" * 40 + "\trefs/heads/main\n" + "b" * 40 + "\trefs/heads/main\n"),
        "a" * 40 + "\trefs/heads/other\n",
    ],
)
def test_latest_resolution_rejects_missing_malformed_or_ambiguous_results(
    monkeypatch: pytest.MonkeyPatch, stdout: str
) -> None:
    monkeypatch.setattr(
        sync.subprocess,
        "run",
        lambda *args, **kwargs: SimpleNamespace(returncode=0, stdout=stdout),
    )

    with pytest.raises(sync.IntegrityError, match="latest CPP ref"):
        sync._resolve_latest_cpp_commit()


def test_source_identity_failure_is_not_a_successful_drift_report(
    report_fixture: tuple[Path, Path, str, str],
    capsys: pytest.CaptureFixture[str],
) -> None:
    _, source, pin, target = report_fixture
    assert pin != target
    _git(source, "checkout", "-q", "--detach", pin)

    assert sync.run_source_report(source, target, generated_at=FIXED_TIMESTAMP) == 2

    captured = capsys.readouterr()
    assert "CODEX_UPSTREAM_REPORT: fail" in captured.out
    assert "REPORT_JSON=" not in captured.out
    assert "does not match declared ref" in captured.err


def test_overlay_failure_emits_no_success_artifact(
    report_fixture: tuple[Path, Path, str, str],
    capsys: pytest.CaptureFixture[str],
) -> None:
    root, source, _, target = report_fixture
    sync.OVERLAY_PATH.write_text("uncommitted overlay\n", encoding="utf-8")
    before = _tree_bytes(root)

    assert sync.run_source_report(source, target, generated_at=FIXED_TIMESTAMP) == 2

    captured = capsys.readouterr()
    assert "CODEX_UPSTREAM_REPORT: fail" in captured.out
    assert "REPORT_JSON=" not in captured.out
    assert "overlay input" in captured.err
    assert _tree_bytes(root) == before


def test_incomplete_current_package_inventory_is_an_execution_error(
    report_fixture: tuple[Path, Path, str, str],
    capsys: pytest.CaptureFixture[str],
) -> None:
    root, source, _, target = report_fixture
    contract = root / ".agents" / "skill-contracts.json"
    contract.write_text('{"skills": []}\n', encoding="utf-8")
    _git(root, "add", str(contract.relative_to(root)))
    _git(root, "commit", "-q", "-m", "broken inventory fixture")

    assert sync.run_source_report(source, target, generated_at=FIXED_TIMESTAMP) == 2

    captured = capsys.readouterr()
    assert "CODEX_UPSTREAM_REPORT: fail" in captured.out
    assert "REPORT_JSON=" not in captured.out
    assert "package inventory is missing generated skills" in captured.err


def test_adaptation_failure_is_an_execution_error_without_partial_output(
    report_fixture: tuple[Path, Path, str, str],
    monkeypatch: pytest.MonkeyPatch,
    capsys: pytest.CaptureFixture[str],
) -> None:
    _, source, _, target = report_fixture

    def fail_adaptation(*args: object, **kwargs: object) -> object:
        raise sync.IntegrityError("fixture overlay failure")

    monkeypatch.setattr(sync, "_prepare_source_payloads", fail_adaptation)

    assert sync.run_source_report(source, target, generated_at=FIXED_TIMESTAMP) == 2

    captured = capsys.readouterr()
    assert "fixture overlay failure" in captured.err
    assert "REPORT_JSON=" not in captured.out
    assert "CODEX_UPSTREAM_REPORT: fail" in captured.out
