from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SKILLS_DIR = ROOT / ".codex" / "skills"

AGENTS_MD_SKILLS = {
    "help": "agents-md-help",
    "lint": "agents-md-lint",
}


def _frontmatter_value(text: str, key: str) -> str:
    match = re.search(rf"^{key}:\s*[\"']?([^\"'\n]+)[\"']?$", text, re.MULTILINE)
    assert match is not None, f"missing frontmatter key: {key}"
    return match.group(1)


def test_agents_md_native_skill_trigger_parity() -> None:
    for command, skill_name in AGENTS_MD_SKILLS.items():
        trigger = f"/agents-md:{command}"
        skill_md = SKILLS_DIR / skill_name / "SKILL.md"

        assert skill_md.is_file(), f"Missing skill file for {trigger}: {skill_md}"

        text = skill_md.read_text()
        assert _frontmatter_value(text, "name") == skill_name
        assert trigger in text
        assert f"agents-md:{command}" in text


def test_agents_md_skills_are_cxpp_owned_not_cpp_generated() -> None:
    generated_marker = "<!-- GENERATED by claude-power-pack"
    for skill_name in AGENTS_MD_SKILLS.values():
        text = (SKILLS_DIR / skill_name / "SKILL.md").read_text()
        assert generated_marker not in text
        assert ".codex/prompts/agents-md" not in text
