"""Immutable CPP source provenance and publication safety (issues #195/#204)."""

from __future__ import annotations

import importlib.util
import json
import os
import subprocess
from pathlib import Path

import pytest

MODULE_PATH = Path(__file__).resolve().parents[1] / "scripts" / "codex_skills_sync.py"
_spec = importlib.util.spec_from_file_location("codex_skills_sync_provenance", MODULE_PATH)
assert _spec is not None and _spec.loader is not None
sync = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(sync)

GIT_ENV = os.environ | {
    "GIT_AUTHOR_NAME": "CxPP provenance test",
    "GIT_AUTHOR_EMAIL": "test@example.com",
    "GIT_COMMITTER_NAME": "CxPP provenance test",
    "GIT_COMMITTER_EMAIL": "test@example.com",
}


def _git(root: Path, *args: str) -> str:
    completed = subprocess.run(
        ["git", *args],
        cwd=root,
        env=GIT_ENV,
        check=True,
        text=True,
        stdout=subprocess.PIPE,
    )
    return completed.stdout.strip()


def _source_repo(tmp_path: Path, *, origin: str = sync.CPP_REPO_URL) -> tuple[Path, str]:
    source = tmp_path / "cpp"
    skill = source / "codex" / "skills" / "flow-auto"
    skill.mkdir(parents=True)
    (skill / "SKILL.md").write_text(
        "---\nname: flow-auto\n---\n<!-- GENERATED by claude-power-pack -->\n",
        encoding="utf-8",
    )
    helper = skill / "scripts" / "fixture.sh"
    helper.parent.mkdir()
    helper.write_text("#!/usr/bin/env bash\necho fixture\n", encoding="utf-8")
    helper.chmod(0o755)

    _git(source, "init", "-q", "-b", "main")
    _git(source, "remote", "add", "origin", origin)
    _git(source, "add", ".")
    _git(source, "commit", "-q", "-m", "fixture CPP source")
    commit = _git(source, "rev-parse", "HEAD")
    _git(source, "checkout", "-q", "--detach", commit)
    return source, commit


def _configure_destination(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> Path:
    root = tmp_path / "cxpp"
    skills = root / ".codex" / "skills"
    vendor = root / "vendor" / "claude-power-pack"
    plugins = root / "plugins"
    skills.mkdir(parents=True)
    vendor.mkdir(parents=True)
    plugins.mkdir(parents=True)
    contracts = root / ".agents" / "skill-contracts.json"
    contracts.parent.mkdir(parents=True)
    contracts.write_text(
        json.dumps(
            {
                "skills": [
                    {
                        "name": "flow-auto",
                        "package": {
                            "state": "packaged",
                            "path": "plugins/flow/skills/flow-auto",
                        },
                    }
                ]
            }
        ),
        encoding="utf-8",
    )
    monkeypatch.setattr(sync, "REPO_ROOT", root)
    monkeypatch.setattr(sync, "SKILLS_ROOT", skills)
    monkeypatch.setattr(sync, "VENDOR_DIR", vendor)
    monkeypatch.setattr(sync, "MANIFEST_PATH", vendor / "codex-skills.sha256")
    monkeypatch.setattr(sync, "PIN_PATH", vendor / "PIN")
    monkeypatch.setattr(sync, "PLUGINS_ROOT", plugins)
    return root


def _publish_fixture(source: Path, commit: str) -> None:
    source_skill = source / "codex" / "skills" / "flow-auto"
    generated = sync.SKILLS_ROOT / "flow-auto"
    payloads = sync._adapted_source_payloads(source_skill)
    sync._write_skill_payload(generated, payloads)

    packaged = sync.PLUGINS_ROOT / "flow" / "skills" / "flow-auto"
    for rel, payload in payloads.items():
        target = packaged / rel
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_bytes(payload.content)
        target.chmod(payload.mode)
    metadata = packaged / "agents" / "openai.yaml"
    metadata.parent.mkdir()
    metadata.write_text("interface: fixture-only metadata\n", encoding="utf-8")

    sync._write_pin(commit)
    assert sync.run_write() == 0


@pytest.fixture
def provenance_fixture(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> tuple[Path, Path, str]:
    root = _configure_destination(tmp_path, monkeypatch)
    source, commit = _source_repo(tmp_path)
    _publish_fixture(source, commit)
    return root, source, commit


def _tree_bytes(root: Path) -> dict[str, bytes]:
    return {
        path.relative_to(root).as_posix(): path.read_bytes()
        for path in root.rglob("*")
        if path.is_file() and ".git" not in path.relative_to(root).parts
    }


def test_exact_pin_accepts_clean_source_and_plugin_metadata_overlay(
    provenance_fixture: tuple[Path, Path, str], capsys: pytest.CaptureFixture[str]
) -> None:
    _, source, commit = provenance_fixture

    assert sync.run_pin_check(source) == 0

    output = capsys.readouterr().out
    assert f"PIN_COMMIT={commit}" in output
    assert f"SOURCE_HEAD={commit}" in output
    assert "PAYLOAD_FILES=2" in output
    assert "PACKAGED_SKILLS=1" in output
    assert "CODEX_PIN_CHECK: ok" in output


@pytest.mark.parametrize(
    "replacement, message",
    [
        ("commit: abc", "40 lowercase"),
        ("commit: {commit}\ncommit: {commit}", "duplicate field 'commit'"),
        ("unknown: value", "unknown field 'unknown'"),
        ("pulls: ../skills/  ->  .codex/skills/", "escapes its root"),
        ("pulls: codex/skills/  ->  ../../outside/", "escapes its root"),
    ],
)
def test_pin_rejects_malformed_duplicate_and_unsafe_fields(
    provenance_fixture: tuple[Path, Path, str], replacement: str, message: str
) -> None:
    _, _, commit = provenance_fixture
    text = sync.PIN_PATH.read_text(encoding="utf-8")
    if replacement.startswith("commit:"):
        text = text.replace(f"commit: {commit}", replacement.format(commit=commit))
    elif replacement.startswith("pulls:"):
        text = text.replace(
            "pulls: codex/skills/  ->  .codex/skills/", replacement
        )
    else:
        text += replacement + "\n"
    sync.PIN_PATH.write_text(text, encoding="utf-8")

    with pytest.raises(sync.IntegrityError, match=message):
        sync.read_pin()


@pytest.mark.parametrize(
    "manifest, message",
    [
        ("bad  flow-auto/SKILL.md\n", "64 lowercase hex"),
        (("0" * 64 + "  ../escape\n"), "escapes its root"),
        (
            ("0" * 64 + "  flow-auto/SKILL.md\n") * 2,
            "duplicate path 'flow-auto/SKILL.md'",
        ),
    ],
)
def test_manifest_rejects_malformed_duplicate_and_unsafe_entries(
    provenance_fixture: tuple[Path, Path, str], manifest: str, message: str
) -> None:
    del provenance_fixture
    sync.MANIFEST_PATH.write_text(manifest, encoding="utf-8")

    with pytest.raises(sync.IntegrityError, match=message):
        sync.read_manifest()


def test_exact_pin_rejects_missing_commit(
    provenance_fixture: tuple[Path, Path, str]
) -> None:
    _, source, commit = provenance_fixture
    sync.PIN_PATH.write_text(
        sync.PIN_PATH.read_text(encoding="utf-8").replace(commit, "0" * 40),
        encoding="utf-8",
    )

    assert sync.run_pin_check(source) == 1


def test_exact_pin_rejects_head_mismatch(
    provenance_fixture: tuple[Path, Path, str]
) -> None:
    _, source, _ = provenance_fixture
    _git(source, "switch", "-q", "--detach")
    (source / "later.txt").write_text("later\n", encoding="utf-8")
    _git(source, "add", "later.txt")
    _git(source, "commit", "-q", "-m", "later source")

    assert sync.run_pin_check(source) == 1


def test_exact_pin_rejects_dirty_source(
    provenance_fixture: tuple[Path, Path, str]
) -> None:
    _, source, _ = provenance_fixture
    (source / "untracked.txt").write_text("dirty\n", encoding="utf-8")

    assert sync.run_pin_check(source) == 1


def test_exact_pin_rejects_assume_unchanged_forged_source_and_generated_payload(
    provenance_fixture: tuple[Path, Path, str]
) -> None:
    _, source, _ = provenance_fixture
    source_skill = source / "codex" / "skills" / "flow-auto"
    source_file = source_skill / "SKILL.md"
    _git(source, "update-index", "--assume-unchanged", "codex/skills/flow-auto/SKILL.md")
    source_file.write_text(
        "---\nname: flow-auto\n---\n<!-- GENERATED by claude-power-pack -->\nforged\n",
        encoding="utf-8",
    )
    assert _git(source, "status", "--porcelain", "--untracked-files=all") == ""

    # Even a forged source mirrored into generated/plugin payloads and the manifest
    # cannot bless bytes that are absent from the immutable pinned Git tree.
    payloads = sync._adapted_source_payloads(source_skill)
    sync._write_skill_payload(sync.SKILLS_ROOT / "flow-auto", payloads)
    sync._sync_plugin_payload("flow-auto")
    assert sync.run_write() == 0

    assert sync.run_pin_check(source) == 1


def test_exact_pin_rejects_mismatched_source_origin(
    provenance_fixture: tuple[Path, Path, str]
) -> None:
    _, source, _ = provenance_fixture
    _git(source, "remote", "set-url", "origin", "https://github.com/cooneycw/other.git")

    assert sync.run_pin_check(source) == 1


@pytest.mark.parametrize(
    "origin",
    [
        "https://github.com/cooneycw/claude-power-pack.git",
        "git@github.com:cooneycw/claude-power-pack.git",
        "ssh://git@github.com/cooneycw/claude-power-pack.git",
    ],
)
def test_documented_credential_free_github_origins_are_normalized(origin: str) -> None:
    assert sync._github_repo_identity(origin) == ("cooneycw", "claude-power-pack")


@pytest.mark.parametrize(
    "origin",
    [
        "http://github.com/cooneycw/claude-power-pack",
        "https://token@github.com/cooneycw/claude-power-pack",
        "https://example.com/cooneycw/claude-power-pack",
    ],
)
def test_unsafe_or_credential_bearing_origins_are_rejected(origin: str) -> None:
    with pytest.raises(sync.IntegrityError, match="credential-free GitHub"):
        sync._github_repo_identity(origin)


def test_exact_pin_rejects_source_symlink_escape(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    _configure_destination(tmp_path, monkeypatch)
    source, _ = _source_repo(tmp_path)
    _git(source, "switch", "-q", "main")
    outside = tmp_path / "outside.txt"
    outside.write_text("outside\n", encoding="utf-8")
    (source / "codex" / "skills" / "flow-auto" / "escape").symlink_to(outside)
    _git(source, "add", ".")
    _git(source, "commit", "-q", "-m", "unsafe source link")
    commit = _git(source, "rev-parse", "HEAD")
    _git(source, "checkout", "-q", "--detach", commit)
    sync._write_pin(commit)
    sync.MANIFEST_PATH.write_text("0" * 64 + "  flow-auto/SKILL.md\n", encoding="utf-8")

    assert sync.run_pin_check(source) == 1


def test_exact_pin_rejects_destination_symlink_escape(
    provenance_fixture: tuple[Path, Path, str], tmp_path: Path
) -> None:
    _, source, _ = provenance_fixture
    skill = sync.SKILLS_ROOT / "flow-auto"
    outside = tmp_path / "outside.txt"
    outside.write_text("outside\n", encoding="utf-8")
    (skill / "SKILL.md").unlink()
    (skill / "SKILL.md").symlink_to(outside)

    assert sync.run_pin_check(source) == 1


def test_exact_pin_rejects_incomplete_generated_coverage(
    provenance_fixture: tuple[Path, Path, str]
) -> None:
    _, source, _ = provenance_fixture
    (sync.SKILLS_ROOT / "flow-auto" / "scripts" / "fixture.sh").unlink()

    assert sync.run_pin_check(source) == 1


def test_exact_pin_rejects_plugin_payload_mismatch(
    provenance_fixture: tuple[Path, Path, str]
) -> None:
    _, source, _ = provenance_fixture
    packaged = sync.PLUGINS_ROOT / "flow" / "skills" / "flow-auto" / "SKILL.md"
    packaged.write_text("drift\n", encoding="utf-8")

    assert sync.run_pin_check(source) == 1


def test_exact_pin_rejects_missing_inventory_declared_plugin_package(
    provenance_fixture: tuple[Path, Path, str]
) -> None:
    _, source, _ = provenance_fixture
    package = sync.PLUGINS_ROOT / "flow" / "skills" / "flow-auto"
    for path in sorted(package.rglob("*"), reverse=True):
        if path.is_file():
            path.unlink()
        else:
            path.rmdir()
    package.rmdir()

    assert sync.run_pin_check(source) == 1


def test_exact_pin_rejects_extra_plugin_agents_payload_file(
    provenance_fixture: tuple[Path, Path, str]
) -> None:
    _, source, _ = provenance_fixture
    extra = sync.PLUGINS_ROOT / "flow" / "skills" / "flow-auto" / "agents" / "extra.txt"
    extra.write_text("not UI metadata\n", encoding="utf-8")

    assert sync.run_pin_check(source) == 1


def test_validated_refresh_publishes_frozen_payload_and_preserves_local_overlays(
    provenance_fixture: tuple[Path, Path, str]
) -> None:
    _, source, _ = provenance_fixture
    metadata = sync.PLUGINS_ROOT / "flow" / "skills" / "flow-auto" / "agents" / "openai.yaml"
    metadata_before = metadata.read_bytes()
    native = sync.SKILLS_ROOT / "project-next" / "SKILL.md"
    native.parent.mkdir()
    native.write_text("native\n", encoding="utf-8")
    stale_agent_payload = (
        sync.PLUGINS_ROOT
        / "flow"
        / "skills"
        / "flow-auto"
        / "agents"
        / "stale-runtime.txt"
    )
    stale_agent_payload.write_text("stale\n", encoding="utf-8")

    _git(source, "switch", "-q", "main")
    helper = source / "codex" / "skills" / "flow-auto" / "scripts" / "fixture.sh"
    helper.write_text("#!/usr/bin/env bash\necho refreshed\n", encoding="utf-8")
    source_agent_payload = (
        source / "codex" / "skills" / "flow-auto" / "agents" / "runtime.txt"
    )
    source_agent_payload.parent.mkdir()
    source_agent_payload.write_text("source-owned runtime\n", encoding="utf-8")
    _git(source, "add", ".")
    _git(source, "commit", "-q", "-m", "refreshed CPP source")
    commit = _git(source, "rev-parse", "HEAD")
    _git(source, "checkout", "-q", "--detach", commit)

    assert sync.run_refresh(source, commit) == 0
    assert sync.read_pin().commit == commit
    assert (sync.SKILLS_ROOT / "flow-auto" / "scripts" / "fixture.sh").read_text(
        encoding="utf-8"
    ).endswith("echo refreshed\n")
    assert metadata.read_bytes() == metadata_before
    assert (
        sync.PLUGINS_ROOT
        / "flow"
        / "skills"
        / "flow-auto"
        / "agents"
        / "runtime.txt"
    ).read_text(encoding="utf-8") == "source-owned runtime\n"
    assert not stale_agent_payload.exists()
    assert native.read_text(encoding="utf-8") == "native\n"
    assert sync.compute_manifest() == sync.read_manifest()
    assert sync.run_pin_check(source) == 0


@pytest.mark.parametrize("target_name", ["PIN_PATH", "MANIFEST_PATH"])
def test_refresh_refuses_symlinked_provenance_file_without_external_write(
    provenance_fixture: tuple[Path, Path, str], tmp_path: Path, target_name: str
) -> None:
    root, source, commit = provenance_fixture
    target: Path = getattr(sync, target_name)
    external = tmp_path / f"external-{target.name}"
    external.write_bytes(target.read_bytes())
    target.unlink()
    target.symlink_to(external)
    before = _tree_bytes(root)
    external_before = external.read_bytes()

    assert sync.run_refresh(source, commit) == 2
    assert _tree_bytes(root) == before
    assert external.read_bytes() == external_before


@pytest.mark.parametrize("symlink_level", ["provenance-dir", "vendor-parent"])
def test_refresh_refuses_symlinked_provenance_parent_without_external_write(
    provenance_fixture: tuple[Path, Path, str], tmp_path: Path, symlink_level: str
) -> None:
    root, source, commit = provenance_fixture
    link = sync.VENDOR_DIR if symlink_level == "provenance-dir" else root / "vendor"
    external = tmp_path / f"external-{symlink_level}"
    link.rename(external)
    sentinel = external / "external-sentinel.txt"
    sentinel.write_text("must remain unchanged\n", encoding="utf-8")
    link.symlink_to(external, target_is_directory=True)
    root_before = _tree_bytes(root)
    external_before = _tree_bytes(external)

    assert sync.run_refresh(source, commit) == 2
    assert _tree_bytes(root) == root_before
    assert _tree_bytes(external) == external_before


@pytest.mark.parametrize("target_name", ["PIN_PATH", "MANIFEST_PATH"])
def test_refresh_refuses_non_regular_provenance_destination_before_writes(
    provenance_fixture: tuple[Path, Path, str], target_name: str
) -> None:
    root, source, commit = provenance_fixture
    target: Path = getattr(sync, target_name)
    target.unlink()
    target.mkdir()
    (target / "sentinel.txt").write_text("unchanged\n", encoding="utf-8")
    before = _tree_bytes(root)

    assert sync.run_refresh(source, commit) == 2
    assert _tree_bytes(root) == before


@pytest.mark.parametrize("failure", ["dirty", "head-mismatch", "unsafe-destination"])
def test_refresh_validation_failure_preserves_every_published_byte(
    provenance_fixture: tuple[Path, Path, str], tmp_path: Path, failure: str
) -> None:
    root, source, commit = provenance_fixture
    before = _tree_bytes(root)

    if failure == "dirty":
        (source / "untracked.txt").write_text("dirty\n", encoding="utf-8")
        refresh_ref = commit
    elif failure == "head-mismatch":
        _git(source, "switch", "-q", "--detach")
        (source / "later.txt").write_text("later\n", encoding="utf-8")
        _git(source, "add", "later.txt")
        _git(source, "commit", "-q", "-m", "later source")
        refresh_ref = commit
    else:
        outside = tmp_path / "outside-destination"
        outside.mkdir()
        (sync.SKILLS_ROOT / "escape").symlink_to(outside, target_is_directory=True)
        before = _tree_bytes(root)
        refresh_ref = commit

    assert sync.run_refresh(source, refresh_ref) == 2
    assert _tree_bytes(root) == before
