"""Behavioral guardrails for the native spec-kit plugin."""

from __future__ import annotations

import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SKILLS = ROOT / ".codex" / "skills"
PLUGIN = ROOT / "plugins" / "spec"
SYNC_SCRIPT = SKILLS / "spec-sync" / "scripts" / "speckit-tasks-to-issues.sh"


def read_skill(name: str) -> str:
    return (SKILLS / name / "SKILL.md").read_text(encoding="utf-8")


def test_spec_skills_are_native_and_packaged() -> None:
    for name in ("spec-adopt", "spec-sync"):
        source = SKILLS / name / "SKILL.md"
        packaged = PLUGIN / "skills" / name / "SKILL.md"

        assert source.is_file()
        assert packaged.read_bytes() == source.read_bytes()
        assert "<!-- GENERATED by claude-power-pack" not in source.read_text(encoding="utf-8")

    assert (PLUGIN / "skills" / "spec-sync" / "scripts" / SYNC_SCRIPT.name).read_bytes() == SYNC_SCRIPT.read_bytes()


def test_spec_adopt_requires_consent_and_uses_codex_initialization() -> None:
    text = read_skill("spec-adopt")

    for needle in [
        "explicit approval",
        "uv tool install specify-cli",
        "specify init --here --integration codex",
        "Do not create GitHub issues as a side effect",
    ]:
        assert needle in text


def test_spec_sync_requires_dry_run_and_has_no_label_adapter() -> None:
    text = read_skill("spec-sync")

    for needle in [
        "Start with `--dry-run`.",
        "explicit user confirmation",
        "no GitHub MCP server and no label adapter",
    ]:
        assert needle in text


def test_sync_helper_exposes_safe_interface_without_network() -> None:
    result = subprocess.run(
        ["bash", str(SYNC_SCRIPT), "--help"],
        check=True,
        capture_output=True,
        text=True,
    )

    assert "--dry-run" in result.stdout
    assert "label-free GitHub issue" in result.stdout
