"""Immutable CPP source provenance and publication safety (issues #195/#204)."""

from __future__ import annotations

import hashlib
import importlib.util
import json
import os
import shutil
import subprocess
from pathlib import Path

import pytest

MODULE_PATH = Path(__file__).resolve().parents[1] / "scripts" / "codex_skills_sync.py"
_spec = importlib.util.spec_from_file_location("codex_skills_sync_provenance", MODULE_PATH)
assert _spec is not None and _spec.loader is not None
sync = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(sync)

GIT_ENV = os.environ | {
    "GIT_AUTHOR_NAME": "CxPP provenance test",
    "GIT_AUTHOR_EMAIL": "test@example.com",
    "GIT_COMMITTER_NAME": "CxPP provenance test",
    "GIT_COMMITTER_EMAIL": "test@example.com",
}


def _git(root: Path, *args: str) -> str:
    completed = subprocess.run(
        ["git", *args],
        cwd=root,
        env=GIT_ENV,
        check=True,
        text=True,
        stdout=subprocess.PIPE,
    )
    return completed.stdout.strip()


def _source_repo(tmp_path: Path, *, origin: str = sync.CPP_REPO_URL) -> tuple[Path, str]:
    source = tmp_path / "cpp"
    skill = source / "codex" / "skills" / "flow-auto"
    skill.mkdir(parents=True)
    (skill / "SKILL.md").write_text(
        "---\nname: flow-auto\n---\n<!-- GENERATED by claude-power-pack -->\n",
        encoding="utf-8",
    )
    helper = skill / "scripts" / "fixture.sh"
    helper.parent.mkdir()
    helper.write_text("#!/usr/bin/env bash\necho fixture\n", encoding="utf-8")
    helper.chmod(0o755)

    _git(source, "init", "-q", "-b", "main")
    _git(source, "remote", "add", "origin", origin)
    _git(source, "add", ".")
    _git(source, "commit", "-q", "-m", "fixture CPP source")
    commit = _git(source, "rev-parse", "HEAD")
    _git(source, "checkout", "-q", "--detach", commit)
    return source, commit


def _configure_destination(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> Path:
    root = tmp_path / "cxpp"
    skills = root / ".codex" / "skills"
    vendor = root / "vendor" / "claude-power-pack"
    plugins = root / "plugins"
    skills.mkdir(parents=True)
    native_context = root / sync._NATIVE_CONTEXT_REL
    native_context.parent.mkdir(parents=True)
    native_context.write_bytes((MODULE_PATH.parents[1] / sync._NATIVE_CONTEXT_REL).read_bytes())
    native_context.chmod(0o644)
    vendor.mkdir(parents=True)
    plugins.mkdir(parents=True)
    contracts = root / ".agents" / "skill-contracts.json"
    contracts.parent.mkdir(parents=True)
    contracts.write_text(
        json.dumps(
            {
                "skills": [
                    {
                        "name": "flow-auto",
                        "package": {
                            "state": "packaged",
                            "path": "plugins/flow/skills/flow-auto",
                        },
                    }
                ]
            }
        ),
        encoding="utf-8",
    )
    monkeypatch.setattr(sync, "REPO_ROOT", root)
    monkeypatch.setattr(sync, "SKILLS_ROOT", skills)
    monkeypatch.setattr(sync, "VENDOR_DIR", vendor)
    monkeypatch.setattr(sync, "MANIFEST_PATH", vendor / "codex-skills.sha256")
    monkeypatch.setattr(sync, "PIN_PATH", vendor / "PIN")
    monkeypatch.setattr(sync, "ADOPTION_POLICY_PATH", vendor / "adoption-policy.json")
    monkeypatch.setattr(sync, "RETAIN_OVERLAY_ROOT", vendor / "overlays" / "retain")
    monkeypatch.setattr(sync, "PLUGINS_ROOT", plugins)
    return root


def _publish_fixture(source: Path, commit: str) -> None:
    source_skill = source / "codex" / "skills" / "flow-auto"
    generated = sync.SKILLS_ROOT / "flow-auto"
    payloads = sync._adapted_source_payloads(source_skill)
    sync._write_skill_payload(generated, payloads)

    packaged = sync.PLUGINS_ROOT / "flow" / "skills" / "flow-auto"
    for rel, payload in payloads.items():
        target = packaged / rel
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_bytes(payload.content)
        target.chmod(payload.mode)
    metadata = packaged / "agents" / "openai.yaml"
    metadata.parent.mkdir()
    metadata.write_text("interface: fixture-only metadata\n", encoding="utf-8")

    sync._write_pin(commit)
    assert sync.run_write() == 0


def _install_synthetic_adoption_policy(
    source: Path, commit: str, monkeypatch: pytest.MonkeyPatch
) -> None:
    """Give the synthetic source a VALID adoption policy (issue #258).

    Publishing and validating paths now require a policy rather than tolerating
    its absence, so a fixture with no policy no longer represents a legal CxPP
    state - it represents the state #258 says must fail.

    The `historical_audit` block is reused VERBATIM from the reviewed policy, so
    `ADOPTION_CHANGE_SET_SHA256` validates unpatched and that assertion stays
    live here. The disposition map is necessarily empty - the reviewed policy's
    adopt/adapt paths do not exist in this two-file synthetic tree, and
    `_apply_adoption_policy` raises on an absent approved payload - so the two
    digests derived from dispositions are fixture-supplied.

    WHAT STILL VERIFIES THOSE TWO, since a fixture that supplies the value under
    test verifies nothing: `test_adoption_policy_rejects_count_preserving_action_swap_before_publication`
    and `test_adoption_policy_rejects_coordinated_retained_payload_change` drive
    the REAL policy through `_committed_policy_fixture` and are the purpose-built
    negative controls for exactly these two digests. They do not use this fixture.
    """
    real = json.loads(
        (MODULE_PATH.parents[1] / "vendor/claude-power-pack/adoption-policy.json").read_text(
            encoding="utf-8"
        )
    )
    adopted = [
        rel.relative_to(source / "codex" / "skills").as_posix()
        for rel in sorted((source / "codex" / "skills").rglob("*"))
        if rel.is_file()
    ]
    tree = _git(source, "rev-parse", f"{commit}^{{tree}}")
    skills_tree = _git(source, "rev-parse", f"{commit}:codex/skills")
    policy = {
        "schema_version": 1,
        "kind": "cxpp-selective-cpp-adoption",
        "source": {
            "repo": sync.CPP_REPO_URL,
            "commit": commit,
            "tree": tree,
            "codex_skills_tree": skills_tree,
        },
        # The audit's CHANGES must cover the disposition set exactly, and the
        # dispositions must name paths that exist in this tree - so both describe
        # the synthetic source. The audit's other fields are copied from the
        # reviewed policy purely to satisfy their format checks.
        "historical_audit": dict(
            real["historical_audit"],
            changes={"added": sorted(adopted), "changed": [], "removed": []},
        ),
        "counts": {"adopt": len(adopted), "adapt": 0, "defer": 0},
        # The reviewed boundaries VERBATIM, like historical_audit above: the
        # loader requires `boundaries == ADOPTION_BOUNDARIES`, so copying the
        # constant keeps that assertion live here instead of patching it away.
        "boundaries": json.loads(json.dumps(sync.ADOPTION_BOUNDARIES)),
        "dispositions": [
            {
                "path": path,
                "source_change": "added",
                "action": "adopt",
                "owner": "fixture",
                "reason": "synthetic adopted state for the test fixture",
                "overlay": None,
            }
            for path in sorted(adopted)
        ],
    }
    sync.ADOPTION_POLICY_PATH.write_text(json.dumps(policy, indent=2) + "\n", encoding="utf-8")
    # COMMIT it in the DESTINATION repo. `_load_adoption_policy` reads the policy's
    # committed bytes out of REPO_ROOT's HEAD as a hidden-edit guard, so a policy
    # that exists only in the working tree fails there - and fails with "source
    # checkout failed git rev-parse validation", which names the wrong repository
    # entirely. That message is why this fixture looked broken rather than
    # incomplete; the query is against the destination, not the source.
    root = sync.REPO_ROOT
    if not (root / ".git").is_dir():
        _git(root, "init", "-q", "-b", "main")
    _git(root, "add", "-A")
    _git(root, "commit", "-q", "-m", "synthetic adopted state")
    monkeypatch.setattr(sync, "ADOPTION_TARGET_COMMIT", commit)
    monkeypatch.setattr(
        sync, "ADOPTION_COUNTS", {"adopt": len(adopted), "adapt": 0, "defer": 0}
    )
    def _digest(value: object) -> str:
        return hashlib.sha256(
            json.dumps(value, sort_keys=True, separators=(",", ":")).encode()
        ).hexdigest()

    monkeypatch.setattr(
        sync, "ADOPTION_CHANGE_SET_SHA256", _digest(policy["historical_audit"]["changes"])
    )
    monkeypatch.setattr(
        sync, "ADOPTION_DECISIONS_SHA256", _digest({path: "adopt" for path in sorted(adopted)})
    )
    monkeypatch.setattr(sync, "ADOPTION_RETAINED_PAYLOADS_SHA256", _digest({}))


@pytest.fixture
def provenance_fixture(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> tuple[Path, Path, str]:
    root = _configure_destination(tmp_path, monkeypatch)
    source, commit = _source_repo(tmp_path)
    # Publish BEFORE adopting the synthetic policy: `run_write` refuses when the
    # pin already IS the adoption target (":816"), so the fixture has to lay the
    # payload down first and only then declare it adopted.
    _publish_fixture(source, commit)
    _install_synthetic_adoption_policy(source, commit, monkeypatch)
    return root, source, commit


def _tree_bytes(root: Path) -> dict[str, bytes]:
    return {
        path.relative_to(root).as_posix(): path.read_bytes()
        for path in root.rglob("*")
        if path.is_file() and ".git" not in path.relative_to(root).parts
    }


def test_exact_pin_accepts_clean_source_and_plugin_metadata_overlay(
    provenance_fixture: tuple[Path, Path, str], capsys: pytest.CaptureFixture[str]
) -> None:
    _, source, commit = provenance_fixture

    assert sync.run_pin_check(source) == 0

    output = capsys.readouterr().out
    assert f"PIN_COMMIT={commit}" in output
    assert f"SOURCE_HEAD={commit}" in output
    assert "PAYLOAD_FILES=3" in output
    assert "PACKAGED_SKILLS=1" in output
    assert "CODEX_PIN_CHECK: ok" in output


@pytest.mark.parametrize(
    "replacement, message",
    [
        ("commit: abc", "40 lowercase"),
        ("commit: {commit}\ncommit: {commit}", "duplicate field 'commit'"),
        ("unknown: value", "unknown field 'unknown'"),
        ("pulls: ../skills/  ->  .codex/skills/", "escapes its root"),
        ("pulls: codex/skills/  ->  ../../outside/", "escapes its root"),
    ],
)
def test_pin_rejects_malformed_duplicate_and_unsafe_fields(
    provenance_fixture: tuple[Path, Path, str], replacement: str, message: str
) -> None:
    _, _, commit = provenance_fixture
    text = sync.PIN_PATH.read_text(encoding="utf-8")
    if replacement.startswith("commit:"):
        text = text.replace(f"commit: {commit}", replacement.format(commit=commit))
    elif replacement.startswith("pulls:"):
        text = text.replace(
            "pulls: codex/skills/  ->  .codex/skills/", replacement
        )
    else:
        text += replacement + "\n"
    sync.PIN_PATH.write_text(text, encoding="utf-8")

    with pytest.raises(sync.IntegrityError, match=message):
        sync.read_pin()


@pytest.mark.parametrize(
    "manifest, message",
    [
        ("bad  flow-auto/SKILL.md\n", "64 lowercase hex"),
        (("0" * 64 + "  ../escape\n"), "escapes its root"),
        (
            ("0" * 64 + "  flow-auto/SKILL.md\n") * 2,
            "duplicate path 'flow-auto/SKILL.md'",
        ),
    ],
)
def test_manifest_rejects_malformed_duplicate_and_unsafe_entries(
    provenance_fixture: tuple[Path, Path, str], manifest: str, message: str
) -> None:
    del provenance_fixture
    sync.MANIFEST_PATH.write_text(manifest, encoding="utf-8")

    with pytest.raises(sync.IntegrityError, match=message):
        sync.read_manifest()


def test_exact_pin_rejects_missing_commit(
    provenance_fixture: tuple[Path, Path, str]
) -> None:
    _, source, commit = provenance_fixture
    sync.PIN_PATH.write_text(
        sync.PIN_PATH.read_text(encoding="utf-8").replace(commit, "0" * 40),
        encoding="utf-8",
    )

    assert sync.run_pin_check(source) == 1


def test_exact_pin_rejects_head_mismatch(
    provenance_fixture: tuple[Path, Path, str]
) -> None:
    _, source, _ = provenance_fixture
    _git(source, "switch", "-q", "--detach")
    (source / "later.txt").write_text("later\n", encoding="utf-8")
    _git(source, "add", "later.txt")
    _git(source, "commit", "-q", "-m", "later source")

    assert sync.run_pin_check(source) == 1


def test_exact_pin_rejects_dirty_source(
    provenance_fixture: tuple[Path, Path, str]
) -> None:
    _, source, _ = provenance_fixture
    (source / "untracked.txt").write_text("dirty\n", encoding="utf-8")

    assert sync.run_pin_check(source) == 1


def test_exact_pin_rejects_assume_unchanged_forged_source_and_generated_payload(
    provenance_fixture: tuple[Path, Path, str]
) -> None:
    _, source, _ = provenance_fixture
    source_skill = source / "codex" / "skills" / "flow-auto"
    source_file = source_skill / "SKILL.md"
    _git(source, "update-index", "--assume-unchanged", "codex/skills/flow-auto/SKILL.md")
    source_file.write_text(
        "---\nname: flow-auto\n---\n<!-- GENERATED by claude-power-pack -->\nforged\n",
        encoding="utf-8",
    )
    assert _git(source, "status", "--porcelain", "--untracked-files=all") == ""

    # Even a forged source mirrored into generated/plugin payloads and the manifest
    # cannot bless bytes that are absent from the immutable pinned Git tree.
    payloads = sync._adapted_source_payloads(source_skill)
    sync._write_skill_payload(sync.SKILLS_ROOT / "flow-auto", payloads)
    sync._sync_plugin_payload("flow-auto")
    # Write the manifest directly rather than via `run_write`. The fixture now
    # declares an ADOPTED state, and `run_write` correctly refuses to snapshot one
    # (":816" - adopted manifests may only be written by --refresh). Forging the
    # manifest is this test's SETUP, not its subject; the subject is that
    # forged bytes cannot pass the pinned-tree check, which is asserted below and
    # is unchanged.
    sync.MANIFEST_PATH.write_text(sync.format_manifest(sync.compute_manifest()))

    assert sync.run_pin_check(source) == 1


def test_exact_pin_rejects_mismatched_source_origin(
    provenance_fixture: tuple[Path, Path, str]
) -> None:
    _, source, _ = provenance_fixture
    _git(source, "remote", "set-url", "origin", "https://github.com/cooneycw/other.git")

    assert sync.run_pin_check(source) == 1


@pytest.mark.parametrize(
    "origin",
    [
        "https://github.com/cooneycw/claude-power-pack.git",
        "git@github.com:cooneycw/claude-power-pack.git",
        "ssh://git@github.com/cooneycw/claude-power-pack.git",
    ],
)
def test_documented_credential_free_github_origins_are_normalized(origin: str) -> None:
    assert sync._github_repo_identity(origin) == ("cooneycw", "claude-power-pack")


@pytest.mark.parametrize(
    "origin",
    [
        "http://github.com/cooneycw/claude-power-pack",
        "https://token@github.com/cooneycw/claude-power-pack",
        "https://example.com/cooneycw/claude-power-pack",
    ],
)
def test_unsafe_or_credential_bearing_origins_are_rejected(origin: str) -> None:
    with pytest.raises(sync.IntegrityError, match="credential-free GitHub"):
        sync._github_repo_identity(origin)


def test_exact_pin_rejects_source_symlink_escape(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    _configure_destination(tmp_path, monkeypatch)
    source, _ = _source_repo(tmp_path)
    _git(source, "switch", "-q", "main")
    outside = tmp_path / "outside.txt"
    outside.write_text("outside\n", encoding="utf-8")
    (source / "codex" / "skills" / "flow-auto" / "escape").symlink_to(outside)
    _git(source, "add", ".")
    _git(source, "commit", "-q", "-m", "unsafe source link")
    commit = _git(source, "rev-parse", "HEAD")
    _git(source, "checkout", "-q", "--detach", commit)
    sync._write_pin(commit)
    sync.MANIFEST_PATH.write_text("0" * 64 + "  flow-auto/SKILL.md\n", encoding="utf-8")

    assert sync.run_pin_check(source) == 1


def test_exact_pin_rejects_destination_symlink_escape(
    provenance_fixture: tuple[Path, Path, str], tmp_path: Path
) -> None:
    _, source, _ = provenance_fixture
    skill = sync.SKILLS_ROOT / "flow-auto"
    outside = tmp_path / "outside.txt"
    outside.write_text("outside\n", encoding="utf-8")
    (skill / "SKILL.md").unlink()
    (skill / "SKILL.md").symlink_to(outside)

    assert sync.run_pin_check(source) == 1


def test_exact_pin_rejects_incomplete_generated_coverage(
    provenance_fixture: tuple[Path, Path, str]
) -> None:
    _, source, _ = provenance_fixture
    (sync.SKILLS_ROOT / "flow-auto" / "scripts" / "fixture.sh").unlink()

    assert sync.run_pin_check(source) == 1


def test_exact_pin_rejects_plugin_payload_mismatch(
    provenance_fixture: tuple[Path, Path, str]
) -> None:
    _, source, _ = provenance_fixture
    packaged = sync.PLUGINS_ROOT / "flow" / "skills" / "flow-auto" / "SKILL.md"
    packaged.write_text("drift\n", encoding="utf-8")

    assert sync.run_pin_check(source) == 1


def test_exact_pin_rejects_missing_inventory_declared_plugin_package(
    provenance_fixture: tuple[Path, Path, str]
) -> None:
    _, source, _ = provenance_fixture
    package = sync.PLUGINS_ROOT / "flow" / "skills" / "flow-auto"
    for path in sorted(package.rglob("*"), reverse=True):
        if path.is_file():
            path.unlink()
        else:
            path.rmdir()
    package.rmdir()

    assert sync.run_pin_check(source) == 1


def test_exact_pin_rejects_extra_plugin_agents_payload_file(
    provenance_fixture: tuple[Path, Path, str]
) -> None:
    _, source, _ = provenance_fixture
    extra = sync.PLUGINS_ROOT / "flow" / "skills" / "flow-auto" / "agents" / "extra.txt"
    extra.write_text("not UI metadata\n", encoding="utf-8")

    assert sync.run_pin_check(source) == 1


def test_validated_refresh_publishes_frozen_payload_and_preserves_local_overlays(
    provenance_fixture: tuple[Path, Path, str], monkeypatch: pytest.MonkeyPatch
) -> None:
    _, source, _ = provenance_fixture
    metadata = sync.PLUGINS_ROOT / "flow" / "skills" / "flow-auto" / "agents" / "openai.yaml"
    metadata_before = metadata.read_bytes()
    native = sync.SKILLS_ROOT / "project-next" / "SKILL.md"
    native.parent.mkdir()
    native.write_text("native\n", encoding="utf-8")
    stale_agent_payload = (
        sync.PLUGINS_ROOT
        / "flow"
        / "skills"
        / "flow-auto"
        / "agents"
        / "stale-runtime.txt"
    )
    stale_agent_payload.write_text("stale\n", encoding="utf-8")

    _git(source, "switch", "-q", "main")
    helper = source / "codex" / "skills" / "flow-auto" / "scripts" / "fixture.sh"
    helper.write_text("#!/usr/bin/env bash\necho refreshed\n", encoding="utf-8")
    source_agent_payload = (
        source / "codex" / "skills" / "flow-auto" / "agents" / "runtime.txt"
    )
    source_agent_payload.parent.mkdir()
    source_agent_payload.write_text("source-owned runtime\n", encoding="utf-8")
    _git(source, "add", ".")
    _git(source, "commit", "-q", "-m", "refreshed CPP source")
    commit = _git(source, "rev-parse", "HEAD")
    _git(source, "checkout", "-q", "--detach", commit)
    # Re-adopt at the NEW commit. `_validate_policy_source` binds the policy to an
    # exact source commit and tree, so refreshing to a new source without moving
    # the policy is the coordinated-update failure #254 is about - here it simply
    # means the fixture must declare the new source adopted before refreshing it.
    _install_synthetic_adoption_policy(source, commit, monkeypatch)

    assert sync.run_refresh(source, commit) == 0
    assert sync.read_pin().commit == commit
    assert (sync.SKILLS_ROOT / "flow-auto" / "scripts" / "fixture.sh").read_text(
        encoding="utf-8"
    ).endswith("echo refreshed\n")
    assert metadata.read_bytes() == metadata_before
    assert (
        sync.PLUGINS_ROOT
        / "flow"
        / "skills"
        / "flow-auto"
        / "agents"
        / "runtime.txt"
    ).read_text(encoding="utf-8") == "source-owned runtime\n"
    assert not stale_agent_payload.exists()
    assert native.read_text(encoding="utf-8") == "native\n"
    assert sync.compute_manifest() == sync.read_manifest()
    assert sync.run_pin_check(source) == 0


@pytest.mark.parametrize("target_name", ["PIN_PATH", "MANIFEST_PATH"])
def test_refresh_refuses_symlinked_provenance_file_without_external_write(
    provenance_fixture: tuple[Path, Path, str], tmp_path: Path, target_name: str
) -> None:
    root, source, commit = provenance_fixture
    target: Path = getattr(sync, target_name)
    external = tmp_path / f"external-{target.name}"
    external.write_bytes(target.read_bytes())
    target.unlink()
    target.symlink_to(external)
    before = _tree_bytes(root)
    external_before = external.read_bytes()

    assert sync.run_refresh(source, commit) == 2
    assert _tree_bytes(root) == before
    assert external.read_bytes() == external_before


@pytest.mark.parametrize("symlink_level", ["provenance-dir", "vendor-parent"])
def test_refresh_refuses_symlinked_provenance_parent_without_external_write(
    provenance_fixture: tuple[Path, Path, str], tmp_path: Path, symlink_level: str
) -> None:
    root, source, commit = provenance_fixture
    link = sync.VENDOR_DIR if symlink_level == "provenance-dir" else root / "vendor"
    external = tmp_path / f"external-{symlink_level}"
    link.rename(external)
    sentinel = external / "external-sentinel.txt"
    sentinel.write_text("must remain unchanged\n", encoding="utf-8")
    link.symlink_to(external, target_is_directory=True)
    root_before = _tree_bytes(root)
    external_before = _tree_bytes(external)

    assert sync.run_refresh(source, commit) == 2
    assert _tree_bytes(root) == root_before
    assert _tree_bytes(external) == external_before


@pytest.mark.parametrize("target_name", ["PIN_PATH", "MANIFEST_PATH"])
def test_refresh_refuses_non_regular_provenance_destination_before_writes(
    provenance_fixture: tuple[Path, Path, str], target_name: str
) -> None:
    root, source, commit = provenance_fixture
    target: Path = getattr(sync, target_name)
    target.unlink()
    target.mkdir()
    (target / "sentinel.txt").write_text("unchanged\n", encoding="utf-8")
    before = _tree_bytes(root)

    assert sync.run_refresh(source, commit) == 2
    assert _tree_bytes(root) == before


@pytest.mark.parametrize("failure", ["dirty", "head-mismatch", "unsafe-destination"])
def test_refresh_validation_failure_preserves_every_published_byte(
    provenance_fixture: tuple[Path, Path, str], tmp_path: Path, failure: str
) -> None:
    root, source, commit = provenance_fixture
    before = _tree_bytes(root)

    if failure == "dirty":
        (source / "untracked.txt").write_text("dirty\n", encoding="utf-8")
        refresh_ref = commit
    elif failure == "head-mismatch":
        _git(source, "switch", "-q", "--detach")
        (source / "later.txt").write_text("later\n", encoding="utf-8")
        _git(source, "add", "later.txt")
        _git(source, "commit", "-q", "-m", "later source")
        refresh_ref = commit
    else:
        outside = tmp_path / "outside-destination"
        outside.mkdir()
        (sync.SKILLS_ROOT / "escape").symlink_to(outside, target_is_directory=True)
        before = _tree_bytes(root)
        refresh_ref = commit

    assert sync.run_refresh(source, refresh_ref) == 2
    assert _tree_bytes(root) == before


def _committed_policy_fixture(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> tuple[Path, Path]:
    root = tmp_path / "policy-repo"
    skills = root / ".codex" / "skills"
    source_vendor = MODULE_PATH.parents[1] / "vendor" / "claude-power-pack"
    vendor = root / "vendor" / "claude-power-pack"
    plugins = root / "plugins"
    skills.mkdir(parents=True)
    plugins.mkdir()
    vendor.parent.mkdir(parents=True)
    shutil.copytree(source_vendor / "overlays", vendor / "overlays")
    shutil.copy2(source_vendor / "adoption-policy.json", vendor / "adoption-policy.json")
    _git(root, "init", "-q", "-b", "main")
    _git(root, "add", ".")
    _git(root, "commit", "-q", "-m", "reviewed adoption policy")
    monkeypatch.setattr(sync, "REPO_ROOT", root)
    monkeypatch.setattr(sync, "SKILLS_ROOT", skills)
    monkeypatch.setattr(sync, "VENDOR_DIR", vendor)
    monkeypatch.setattr(sync, "MANIFEST_PATH", vendor / "codex-skills.sha256")
    monkeypatch.setattr(sync, "PIN_PATH", vendor / "PIN")
    monkeypatch.setattr(sync, "ADOPTION_POLICY_PATH", vendor / "adoption-policy.json")
    monkeypatch.setattr(sync, "RETAIN_OVERLAY_ROOT", vendor / "overlays" / "retain")
    monkeypatch.setattr(sync, "PLUGINS_ROOT", plugins)
    return root, vendor


def _assert_policy_stops_refresh_before_publication(
    root: Path,
    monkeypatch: pytest.MonkeyPatch,
    capsys: pytest.CaptureFixture[str],
    message: str,
) -> None:
    before = _tree_bytes(root)

    def unexpected_source_validation(*args: object, **kwargs: object) -> tuple[str, str]:
        pytest.fail("source validation ran after invalid adoption policy")

    monkeypatch.setattr(sync, "_validate_source_checkout", unexpected_source_validation)
    assert sync.run_refresh(root / "source-not-used", sync.ADOPTION_TARGET_COMMIT) == 2
    assert message in capsys.readouterr().err
    assert _tree_bytes(root) == before


def test_reviewed_adoption_policy_covers_all_59_paths_from_the_frozen_audit() -> None:
    policy = sync._load_adoption_policy()
    assert policy is not None
    assert len(policy.dispositions) == 59
    assert {
        action: sum(item.action == action for item in policy.dispositions.values())
        for action in sync.ADOPTION_COUNTS
    } == sync.ADOPTION_COUNTS
    assert sum(item.retained is not None for item in policy.dispositions.values()) == 9
    assert policy.historical_audit["report_sha256"] == (
        "cc752f61b4f8e0aef496f65f8a435192382ff3229b201918566fb4cb2252e8ba"
    )
    assert policy.boundaries == sync.ADOPTION_BOUNDARIES


def test_adoption_policy_rejects_count_preserving_action_swap_before_publication(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
    capsys: pytest.CaptureFixture[str],
) -> None:
    root, vendor = _committed_policy_fixture(tmp_path, monkeypatch)
    path = vendor / "adoption-policy.json"
    value = json.loads(path.read_text(encoding="utf-8"))
    by_path = {item["path"]: item for item in value["dispositions"]}
    by_path["flow-auto/scripts/flow-ci-status.sh"]["action"] = "defer"
    by_path["flow-auto/scripts/flow-driver-capability.sh"]["action"] = "adapt"
    path.write_text(json.dumps(value, indent=2) + "\n", encoding="utf-8")
    _git(root, "add", "vendor/claude-power-pack/adoption-policy.json")
    _git(root, "commit", "-q", "-m", "swap two reviewed actions")

    _assert_policy_stops_refresh_before_publication(
        root, monkeypatch, capsys, "path/action decisions"
    )


@pytest.mark.parametrize("mutation", ["bytes", "mode"])
def test_adoption_policy_rejects_coordinated_retained_payload_change(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
    capsys: pytest.CaptureFixture[str],
    mutation: str,
) -> None:
    root, vendor = _committed_policy_fixture(tmp_path, monkeypatch)
    policy_path = vendor / "adoption-policy.json"
    value = json.loads(policy_path.read_text(encoding="utf-8"))
    disposition = next(
        item
        for item in value["dispositions"]
        if item["path"] == "flow-repair/reference.md"
    )
    overlay_path = root / disposition["overlay"]["path"]
    if mutation == "bytes":
        overlay_path.write_bytes(overlay_path.read_bytes() + b"coordinated change\n")
        disposition["overlay"]["sha256"] = hashlib.sha256(
            overlay_path.read_bytes()
        ).hexdigest()
    else:
        overlay_path.chmod(0o755)
        disposition["overlay"]["mode"] = "100755"
    policy_path.write_text(json.dumps(value, indent=2) + "\n", encoding="utf-8")
    _git(root, "add", "vendor/claude-power-pack")
    _git(root, "commit", "-q", "-m", f"coordinate retained {mutation} change")

    _assert_policy_stops_refresh_before_publication(
        root, monkeypatch, capsys, "reviewed historical evidence"
    )


@pytest.mark.parametrize("location", ["top-level", "nested"])
def test_adoption_policy_rejects_conflicting_duplicate_json_keys_before_publication(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
    capsys: pytest.CaptureFixture[str],
    location: str,
) -> None:
    root, vendor = _committed_policy_fixture(tmp_path, monkeypatch)
    path = vendor / "adoption-policy.json"
    text = path.read_text(encoding="utf-8")
    if location == "top-level":
        text = text.replace(
            '{\n  "schema_version": 1,',
            '{\n  "schema_version": 2,\n  "schema_version": 1,',
            1,
        )
        duplicate = "schema_version"
    else:
        text = text.replace(
            f'    "commit": "{sync.ADOPTION_TARGET_COMMIT}",',
            f'    "commit": "{"0" * 40}",\n'
            f'    "commit": "{sync.ADOPTION_TARGET_COMMIT}",',
            1,
        )
        duplicate = "commit"
    path.write_text(text, encoding="utf-8")
    _git(root, "add", "vendor/claude-power-pack/adoption-policy.json")
    _git(root, "commit", "-q", "-m", f"duplicate {location} JSON key")

    _assert_policy_stops_refresh_before_publication(
        root, monkeypatch, capsys, f"duplicate JSON key: {duplicate}"
    )


@pytest.mark.parametrize("hidden_change", ["bytes", "mode"])
def test_adoption_policy_rejects_hidden_tracked_overlay_edits(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch, hidden_change: str
) -> None:
    root, vendor = _committed_policy_fixture(tmp_path, monkeypatch)
    overlay_rel = "vendor/claude-power-pack/overlays/retain/cpp-help/reference.md"
    overlay = root / overlay_rel
    _git(root, "update-index", "--assume-unchanged", overlay_rel)
    if hidden_change == "bytes":
        overlay.write_bytes(overlay.read_bytes() + b"hidden\n")
        expected = "checked-out bytes differ"
    else:
        overlay.chmod(0o755)
        expected = "checked-out mode differs"
    assert _git(root, "status", "--porcelain", "--untracked-files=all") == ""

    with pytest.raises(sync.IntegrityError, match=expected):
        sync._load_adoption_policy()


@pytest.mark.parametrize(
    "mutation, message",
    [
        ("unknown-field", "field mismatch"),
        ("duplicate", "duplicate disposition"),
        ("unsafe-path", "escapes its root"),
        ("target-mismatch", "reviewed #196 target commit"),
        ("audit-mismatch", "historical audit identity"),
        ("boundary-mismatch", "policy boundary"),
        ("overlay-digest", "retention overlay digest mismatch"),
    ],
)
def test_adoption_policy_rejects_malformed_duplicate_unsafe_or_mismatched_data(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
    mutation: str,
    message: str,
) -> None:
    root, vendor = _committed_policy_fixture(tmp_path, monkeypatch)
    path = vendor / "adoption-policy.json"
    value = json.loads(path.read_text(encoding="utf-8"))
    if mutation == "unknown-field":
        value["unexpected"] = True
    elif mutation == "duplicate":
        value["dispositions"].append(value["dispositions"][0])
    elif mutation == "unsafe-path":
        value["historical_audit"]["changes"]["changed"][0] = "../escape"
    elif mutation == "target-mismatch":
        value["source"]["commit"] = "0" * 40
    elif mutation == "audit-mismatch":
        value["historical_audit"]["baseline_manifest_sha256"] = "0" * 64
    elif mutation == "boundary-mismatch":
        value["boundaries"]["native_collisions"].pop()
    else:
        retained = next(item for item in value["dispositions"] if item["overlay"])
        retained["overlay"]["sha256"] = "0" * 64
    path.write_text(json.dumps(value, indent=2) + "\n", encoding="utf-8")
    _git(root, "add", "vendor/claude-power-pack/adoption-policy.json")
    _git(root, "commit", "-q", "-m", f"mutate policy: {mutation}")

    with pytest.raises(sync.IntegrityError, match=message):
        sync._load_adoption_policy()


# Immutable upstream evidence is intentionally separate from production policy.
CONTRACT_FIXTURE = MODULE_PATH.parent.parent / "tests/fixtures/github-issue-contract-source.json"
CONTRACT_IDENTITIES = {
    "before": (
        "f64a654f76ea8d26a33eb33f785f6e1065a823b6",
        "32f7905e61b78ec6a6c8b001d2539ac59a691a47",
        "77abab65998d61802f16f33d9935d7f8203b4e1e9a1824aac295489155c0d59a", 2667,
    ),
    "after": (
        "8ebef00ce1424f713f61150eac214a1612589604",
        "2c850e3c88f0674c912482f6dce773e184dfc276",
        "d4bc6b921f0b5e4a909d4e284bf95ae9e5be90ead3f406152cc9c210dcf28382", 3902,
    ),
}


def _contract_witnesses() -> dict[str, bytes]:
    fixture = json.loads(CONTRACT_FIXTURE.read_text())
    result = {}
    for state, identity in CONTRACT_IDENTITIES.items():
        record = fixture[state]
        content = record["text"].encode()
        assert record["path"] == "codex/skills/github-issue-create/reference.md"
        assert tuple(record[key] for key in ("commit", "blob", "sha256", "size")) == identity
        assert len(content) == identity[3]
        assert hashlib.sha256(content).hexdigest() == identity[2]
        git_blob = hashlib.sha1(
            b"blob " + str(len(content)).encode() + b"\0" + content, usedforsecurity=False
        ).hexdigest()
        assert git_blob == identity[1]
        result[state] = content
    return result


def test_issue_contract_backport_reproduces_upstream_once_before_native_adaptations(tmp_path: Path) -> None:
    witnesses = _contract_witnesses()
    skill = tmp_path / "github-issue-create"
    skill.mkdir()
    (skill / "SKILL.md").write_text("---\nname: github-issue-create\n---\n")
    for state in ("before", "after"):
        assert sync._backport_github_issue_contract(skill, "reference.md", witnesses[state]) == witnesses["after"]
        actual = sync._adapted_source_payloads(
            skill, {"reference.md": sync.PreparedPayload(witnesses[state], 0o644)}
        )["reference.md"]
        # Independently expected native edits to the immutable AFTER witness.
        expected = witnesses["after"].decode().replace("cooneycw/claude-power-pack", '\"$REPO\"')
        expected = expected.replace(
            "../../../docs/agents/issue-contract.md",
            "https://github.com/cooneycw/codex-power-pack/blob/main/docs/agents/issue-contract.md",
        ).replace("/github-issue-create", "$github-issue-create")
        expected = expected.replace(
            "## Issue Creation Flow\n",
            "If the canonical reference is unavailable, report it and continue otherwise\n"
            "authorized routine work using known project/user constraints and authority.\n"
            "Do not invent missing policy or treat a proposal as permission to cross those bounds.\n\n"
            "## Issue Creation Flow\n",
        )
        assert actual == sync.PreparedPayload(expected.encode(), 0o644)
        assert actual.content.count(b"## What the Body Must Make Legible") == 1
        published = MODULE_PATH.parent.parent / ".codex/skills/github-issue-create/reference.md"
        assert published.read_bytes() == actual.content


# The depths upstream has actually written this link at: `../../../docs/...`
# through CPP #862, then `docs/...` from CPP 01b8e13 on. The third entry is not
# an upstream state - it is the guard against a rule that matches the link
# target anywhere and would rewrite an already-absolute URL a second time.
_CONTRACT_LINK_DEPTHS = ["../../../", "../", ""]


@pytest.mark.parametrize("prefix", _CONTRACT_LINK_DEPTHS)
def test_issue_contract_link_is_made_absolute_at_every_upstream_relative_depth(
    tmp_path: Path, prefix: str
) -> None:
    """The DEPTH of this link is upstream's to change, and it did.

    The rewrite matched `../../../docs/agents/issue-contract.md` byte-exactly.
    CPP 01b8e13 shortened the path to `docs/agents/issue-contract.md` in a
    one-line edit, so the rewrite silently stopped firing and the generated
    CxPP reference kept a relative link - which resolves to
    `.codex/skills/github-issue-create/docs/agents/issue-contract.md`, a file
    that does not exist. Nothing failed; the route simply went nowhere.
    """
    skill = tmp_path / "github-issue-create"
    line = f"in [the issue contract]({prefix}docs/agents/issue-contract.md). For work large\n"
    adapted = sync._adapt_github_text(skill, Path("reference.md"), line)

    assert f"]({sync._ISSUE_CONTRACT_URL})" in adapted
    assert "](docs/agents/issue-contract.md)" not in adapted
    assert "](../" not in adapted
    # Rewriting an already-absolute link a second time would nest the URL.
    assert sync._adapt_github_text(skill, Path("reference.md"), adapted) == adapted
    assert adapted.count(sync._ISSUE_CONTRACT_URL) == 1


@pytest.mark.parametrize("state", ["before", "after"])
def test_issue_contract_unreviewed_raw_source_cannot_be_hidden_by_generic_adaptation(
    tmp_path: Path, state: str
) -> None:
    content = _contract_witnesses()[state]
    skill = tmp_path / "github-issue-create"
    skill.mkdir()
    # Replacing native-adapted tokens before identity verification used to look
    # equivalent after generic adaptation. The raw-source guard must still fail.
    altered = content.replace(b"cooneycw/claude-power-pack", b'"$REPO"')
    with pytest.raises(sync.IntegrityError, match="unreviewed raw source"):
        sync._adapted_source_payloads(skill, {"reference.md": sync.PreparedPayload(altered, 0o644)})
    assert sync._backport_github_issue_contract(skill, "SKILL.md", altered) == altered
    assert sync._backport_github_issue_contract(tmp_path / "github-issue-view", "reference.md", altered) == altered


def test_issue_contract_unknown_source_fails_refresh_before_any_publication(
    provenance_fixture: tuple[Path, Path, str],
    capsys: pytest.CaptureFixture[str],
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    root, source, _ = provenance_fixture
    skill = source / "codex/skills/github-issue-create"
    skill.mkdir()
    (skill / "SKILL.md").write_text("---\nname: github-issue-create\n---\n<!-- GENERATED by claude-power-pack -->\n")
    (skill / "reference.md").write_bytes(_contract_witnesses()["after"] + b"unreviewed source change\n")
    _git(source, "add", ".")
    _git(source, "commit", "-q", "-m", "unreviewed github reference")
    commit = _git(source, "rev-parse", "HEAD")
    _git(source, "checkout", "-q", "--detach", commit)
    _install_synthetic_adoption_policy(source, commit, monkeypatch)
    before = _tree_bytes(root)
    assert sync.run_refresh(source, commit) != 0
    assert "unreviewed raw source" in capsys.readouterr().err
    assert _tree_bytes(root) == before


def _flow_context_witnesses() -> dict[str, str]:
    return json.loads((MODULE_PATH.parents[1] / "tests/fixtures/flow-context-source.json").read_text())


def _adapt(tmp_path: Path, raw: bytes) -> dict[str, object]:
    skill = tmp_path / "flow-auto"
    skill.mkdir(parents=True, exist_ok=True)
    return sync._adapted_source_payloads(skill, {"reference.md": sync.PreparedPayload(raw, 0o644)})


def test_flow_context_consumer_replaces_an_upstream_block_that_is_present(tmp_path: Path) -> None:
    """GREEN arm. The 'after' witness is CPP cb16600, where #858 shipped the block."""
    witness = _flow_context_witnesses()
    raw = witness["after"].encode()
    assert sync._FLOW_CONTEXT_START_MARKER in witness["after"]

    adapted = _adapt(tmp_path, raw)

    content = adapted["reference.md"].content
    assert content.count(b"**Generated governing context") == 1
    assert b"speckit-context.py" not in content
    assert b"| **Container**" not in content
    assert adapted["scripts/spec_context.py"].content == (
        MODULE_PATH.parents[1] / sync._NATIVE_CONTEXT_REL
    ).read_bytes()


def test_flow_context_inserts_the_consumer_for_a_pinned_era_source(tmp_path: Path) -> None:
    """The other era, and a real upstream state rather than a synthetic one.

    The 'before' witness is CPP f64a654 - the pin - which genuinely predates #858
    and carries no speckit-context block. The retired recipe used to manufacture
    one here purely so this overlay could delete it again (issue #251); the
    insert branch reaches the same bytes without the ceremony.
    """
    witness = _flow_context_witnesses()
    assert sync._FLOW_CONTEXT_START_MARKER not in witness["before"]

    adapted = _adapt(tmp_path, witness["before"].encode())

    content = adapted["reference.md"].content
    assert content.count(b"**Generated governing context") == 1
    assert b"speckit-context.py" not in content


def test_flow_context_refuses_a_source_without_the_overlay_anchor(tmp_path: Path) -> None:
    """RED arm. The end marker is the single point of failure after #251."""
    witness = _flow_context_witnesses()
    damaged = witness["after"].replace(sync._FLOW_CONTEXT_END_MARKER, "2. **Something else:**")

    with pytest.raises(sync.IntegrityError, match="Re-anchor the insertion point"):
        _adapt(tmp_path, damaged.encode())


def test_both_upstream_eras_generate_the_identical_artifact(tmp_path: Path) -> None:
    """Why retiring the CPP #858 recipe is safe rather than merely tidy.

    The recipe's two deltas both landed in regions the CxPP overlay later
    replaces - the speckit block inside this overlay's own region, the #835
    Container row inside the capability contract section that
    `_adapt_deferred_native_boundaries` rewrites wholesale. So a pre-#858 source
    and a post-#858 source converge on the same published bytes, which is the
    property that let the recipe be deleted outright instead of reduced.

    If a future overlay stops replacing one of those regions this test fails,
    and the two eras start producing different skills - the failure the recipe
    was nominally guarding against, now actually detected.
    """
    witness = _flow_context_witnesses()

    before = _adapt(tmp_path / "b", witness["before"].encode())["reference.md"]
    after = _adapt(tmp_path / "a", witness["after"].encode())["reference.md"]

    assert before.content == after.content


def test_reporting_accepts_an_unreviewed_contract_source_that_publication_refuses(
    provenance_fixture: tuple[Path, Path, str],
) -> None:
    """The #251 split itself, on one source, both verdicts.

    This pins the SPLIT's contract: one source, both verdicts, same bytes.

    It does NOT pin the call site. Removing `review=False` from
    `_upstream_report` restores the #856 cron failure, and this test would
    still pass - the end-to-end control for that needs the report fixture in
    tests/test_codex_skills_report.py, which is outside this change's lane.
    Recorded so the gap is visible rather than assumed covered.

    Structurally valid means the anchors the transformation needs are intact;
    unreviewed means the bytes match neither recorded witness. Reporting READS
    and must accept it. Publication WRITES and must still refuse it.
    """
    _, source, _ = provenance_fixture
    skill = source / "codex/skills/github-issue-create"
    skill.mkdir(parents=True, exist_ok=True)
    (skill / "SKILL.md").write_text(
        "---\nname: github-issue-create\n---\n<!-- GENERATED by claude-power-pack -->\n"
    )
    unreviewed = (
        b"<!-- GENERATED by claude-power-pack -->\n\n"
        b"Upstream prose that matches neither recorded witness.\n\n"
        b"- Problem/use case\n- Proposed solution\n\n"
        b"## Issue Creation Flow\n\nsteps\n"
    )
    (skill / "reference.md").write_bytes(unreviewed)
    # PUBLICATION refuses it - the #195/#204 control, unchanged by the split.
    with pytest.raises(sync.IntegrityError, match="unreviewed raw source"):
        sync._adapted_source_payloads(
            skill, {"reference.md": sync.PreparedPayload(unreviewed, 0o644)}
        )

    # REPORTING accepts it, and still applies the transformation.
    adapted = sync._adapted_source_payloads(
        skill, {"reference.md": sync.PreparedPayload(unreviewed, 0o644)}, review=False
    )
    assert sync._GITHUB_CONTRACT_HEADING in adapted["reference.md"].content


def test_absent_adoption_policy_is_an_error_at_every_pin(
    provenance_fixture: tuple[Path, Path, str], monkeypatch: pytest.MonkeyPatch
) -> None:
    """RED case for issue #258: absence must never read as checked-and-fine.

    `_load_adoption_policy` used to take `required=pin.commit ==
    ADOPTION_TARGET_COMMIT`, so the moment the pin moved off the reviewed target
    an ABSENT policy stopped being an error: the loader returned None,
    `_validate_policy_source` was skipped, and generation proceeded unenforced.
    The control did not weaken gradually - it stopped existing, and nothing said
    so.

    On the pre-fix code this test FAILS: the loader returns None rather than
    raising, which is the whole defect. Both halves are asserted, because
    "it raises now" alone would not distinguish the fix from the policy simply
    being present.
    """
    _, source, _ = provenance_fixture
    assert sync.ADOPTION_POLICY_PATH.is_file(), "fixture should start adopted"

    # The state a bump creates: the pin is no longer the reviewed target, and the
    # policy is gone for whatever reason.
    sync.ADOPTION_POLICY_PATH.unlink()
    monkeypatch.setattr(sync, "ADOPTION_TARGET_COMMIT", "0" * 40)

    # PUBLISHING refuses. Before the fix this returned None and generation
    # proceeded unenforced, which is the whole defect.
    with pytest.raises(sync.IntegrityError, match="adoption policy is missing"):
        sync._load_adoption_policy()

    # READING degrades to unenforced rather than refusing, and says so by
    # returning None instead of raising. Both halves are asserted, because
    # "it raises" alone would not distinguish the fix from a blanket refusal.
    assert sync._load_adoption_policy(publishing=False) is None


def test_pin_and_adoption_target_must_not_diverge() -> None:
    """The pairing #258 found unenforced, now stated in one place.

    The PIN and ADOPTION_TARGET_COMMIT are edited by hand in the same change and
    nothing checked that they agreed. Divergence was loud on the refresh path and
    silent on every path that only consumed the flag derived from it.
    """
    sync._assert_pin_matches_adoption_target(sync.ADOPTION_TARGET_COMMIT)

    with pytest.raises(sync.IntegrityError, match="does not match the reviewed adoption target"):
        sync._assert_pin_matches_adoption_target("0" * 40)


def test_retired_858_backport_recipe_is_gone() -> None:
    """Negative membership: the recipe retired in #251 must not drift back.

    A reintroduced recipe would silently re-pin generation to two byte-exact
    upstream identities, which is the condition that failed every cron run.
    """
    for retired in (
        "_backport_flow_context",
        "_FLOW_CONTEXT_BEFORE",
        "_FLOW_CONTEXT_AFTER",
        "_FLOW_CONTEXT_DELTA",
        "_FLOW_CONTAINER_ROW",
    ):
        assert not hasattr(sync, retired), f"{retired} was retired in issue #251"


@pytest.mark.parametrize("damage", ["missing", "symlink", "bytes", "mode", "unknown-reference"])
def test_context_dependency_and_source_refuse_before_publication(
    provenance_fixture: tuple[Path, Path, str], damage: str
) -> None:
    root, source, commit = provenance_fixture
    native = root / sync._NATIVE_CONTEXT_REL
    if damage == "missing":
        native.unlink()
    elif damage == "symlink":
        native.unlink()
        native.symlink_to(MODULE_PATH.parents[1] / sync._NATIVE_CONTEXT_REL)
    elif damage == "bytes":
        native.write_bytes(native.read_bytes() + b"# unreviewed\n")
    elif damage == "mode":
        native.chmod(0o755)
    else:
        (source / "codex/skills/flow-auto/reference.md").write_text("unreviewed relevant source")
        _git(source, "add", ".")
        _git(source, "commit", "-qm", "unknown source")
        commit = _git(source, "rev-parse", "HEAD")
    before = _tree_bytes(root)
    assert sync.run_refresh(source, commit) == 2
    assert _tree_bytes(root) == before


@pytest.mark.parametrize("mode", [0o600, 0o644, 0o664, 0o666])
def test_native_context_binding_uses_git_mode_not_checkout_umask(
    provenance_fixture: tuple[Path, Path, str], mode: int
) -> None:
    root, _, _ = provenance_fixture
    native = root / sync._NATIVE_CONTEXT_REL
    native.chmod(mode)
    assert sync._native_context_payload().mode == 0o644
    native.chmod(mode | 0o010)
    with pytest.raises(sync.IntegrityError, match="hash/mode"):
        sync._native_context_payload()
