"""Behavioral guardrails for the CxPP host-setup fallback."""

from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SKILLS = ROOT / ".codex" / "skills"
PLUGIN = ROOT / "plugins" / "cxpp"


def read_skill(name: str) -> str:
    return (SKILLS / name / "SKILL.md").read_text(encoding="utf-8")


def test_cxpp_skills_are_native_and_packaged() -> None:
    for name in ("cxpp-init", "cxpp-update", "cxpp-status"):
        source = SKILLS / name / "SKILL.md"
        packaged = PLUGIN / "skills" / name / "SKILL.md"

        assert source.is_file()
        assert packaged.read_bytes() == source.read_bytes()
        assert "<!-- GENERATED by claude-power-pack" not in source.read_text(encoding="utf-8")


def test_cxpp_init_requires_explicit_consent_and_preserves_boundaries() -> None:
    text = read_skill("cxpp-init")

    for needle in [
        "explicit approval",
        "Never request, print, read, or persist secret values.",
        "Never start, stop, deploy, update, or otherwise manage",
        "additive updates only",
        "codex execpolicy check",
    ]:
        assert needle in text


def test_cxpp_status_is_read_only_and_checks_host_pointers() -> None:
    text = read_skill("cxpp-status")

    assert "skill is read-only" in text
    assert "codex plugin list --json" in text
    assert "codex mcp get second-opinion" in text
    assert "curl -sf http://127.0.0.1:8080/readyz" in text


def test_cxpp_plugin_includes_the_host_pointer_template() -> None:
    assert (PLUGIN / "config.toml.example").read_bytes() == (ROOT / "templates" / "config.toml.example").read_bytes()
