"""Behavioral guardrails for the native spec-kit plugin."""

from __future__ import annotations

import subprocess
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
SKILLS = ROOT / ".codex" / "skills"
PLUGIN = ROOT / "plugins" / "spec"
SYNC_SCRIPT = SKILLS / "spec-sync" / "scripts" / "speckit-tasks-to-issues.sh"
SYNC_RUNTIME = SKILLS / "spec-sync" / "scripts" / "spec_sync.py"
EXTENSION = ROOT / "extensions" / "cxpp-issue-sync"


def read_skill(name: str) -> str:
    return (SKILLS / name / "SKILL.md").read_text(encoding="utf-8")


def test_spec_skills_are_native_and_packaged() -> None:
    for name in ("spec-adopt", "spec-sync"):
        source = SKILLS / name / "SKILL.md"
        packaged = PLUGIN / "skills" / name / "SKILL.md"

        assert source.is_file()
        assert packaged.read_bytes() == source.read_bytes()
        assert "<!-- GENERATED by claude-power-pack" not in source.read_text(encoding="utf-8")

    assert (PLUGIN / "skills" / "spec-sync" / "scripts" / SYNC_SCRIPT.name).read_bytes() == SYNC_SCRIPT.read_bytes()
    assert (PLUGIN / "skills" / "spec-sync" / "scripts" / SYNC_RUNTIME.name).read_bytes() == SYNC_RUNTIME.read_bytes()


def test_spec_adopt_requires_consent_and_uses_codex_initialization() -> None:
    text = read_skill("spec-adopt")

    for needle in [
        "explicit approval",
        "uv tool install specify-cli",
        "github/spec-kit.git@v0.16.0",
        "5dce710ce099067c7d3f2ef47a37b9a1c300b327",
        "specify init --here --integration codex",
        "Do not create GitHub issues as a side effect",
    ]:
        assert needle in text


def test_spec_sync_requires_dry_run_and_has_no_label_adapter() -> None:
    text = read_skill("spec-sync")

    for needle in [
        "Start with `--dry-run`.",
        "explicit user confirmation",
        "no GitHub MCP server",
        "no label",
        "hidden stable",
        "identities",
        "Issue Sync ledger",
    ]:
        assert needle in text


def test_sync_helper_exposes_safe_interface_without_network() -> None:
    result = subprocess.run(
        ["bash", str(SYNC_SCRIPT), "--help"],
        check=True,
        capture_output=True,
        text=True,
    )

    assert "--dry-run" in result.stdout
    assert "--artifact-commit" in result.stdout
    assert "--analysis-clean" in result.stdout
    assert "--approve" in result.stdout


def test_official_spec_kit_extension_is_pinned_optional_and_packaged() -> None:
    packaged = PLUGIN / "extensions" / "cxpp-issue-sync"
    for relative in ("extension.yml", "README.md", "commands/speckit.cxpp-issue-sync.preview.md"):
        assert (packaged / relative).read_bytes() == (EXTENSION / relative).read_bytes()

    manifest = yaml.safe_load((EXTENSION / "extension.yml").read_text())
    assert manifest["schema_version"] == "1.0"
    assert manifest["extension"]["id"] == "cxpp-issue-sync"
    assert manifest["requires"]["speckit_version"] == "==0.16.0"
    assert manifest["provides"]["commands"][0]["name"] == "speckit.cxpp-issue-sync.preview"
    assert manifest["hooks"]["after_tasks"]["optional"] is True
    assert manifest["defaults"]["require_approval"] is True
