"""CI/CD pipeline generation.

Generates Woodpecker CI pipelines from detected framework information
and configuration.
"""

from __future__ import annotations

from pathlib import Path
from typing import Optional

from .config import CICDConfig
from .models import Framework, FrameworkInfo, PackageManager

# Docker images for Woodpecker CI steps
_WOODPECKER_IMAGES: dict[Framework, str] = {
    Framework.PYTHON: "python:3.12",
    Framework.NODE: "node:22",
    Framework.GO: "golang:1.23",
    Framework.RUST: "rust:1.82",
    Framework.POWERSHELL: "mcr.microsoft.com/powershell:7.4-ubuntu-24.04",
    Framework.MULTI: "ubuntu:24.04",
    Framework.UNKNOWN: "ubuntu:24.04",
}

# Python version matrices by framework
_DEFAULT_MATRIX: dict[Framework, dict[str, list[str]]] = {
    Framework.PYTHON: {"python-version": ["3.11", "3.12"]},
    Framework.NODE: {"node-version": ["20", "22"]},
    Framework.GO: {"go-version": ["1.22", "1.23"]},
    Framework.RUST: {"rust-version": ["stable"]},
    Framework.POWERSHELL: {"os": ["ubuntu-latest", "windows-latest"]},
}

# AWS-backed deploy secret validation image
_AWS_CLI_IMAGE = "amazon/aws-cli:2.17.63"

# Install commands for Woodpecker CI
_WOODPECKER_INSTALL: dict[tuple[Framework, PackageManager], list[str]] = {
    (Framework.PYTHON, PackageManager.UV): ["pip install uv", "uv sync"],
    (Framework.PYTHON, PackageManager.PIP): ["pip install -r requirements.txt"],
    (Framework.PYTHON, PackageManager.POETRY): ["pip install poetry", "poetry install"],
    (Framework.NODE, PackageManager.NPM): ["npm ci"],
    (Framework.NODE, PackageManager.YARN): ["yarn install --frozen-lockfile"],
    (Framework.NODE, PackageManager.PNPM): ["corepack enable", "pnpm install --frozen-lockfile"],
    (Framework.GO, PackageManager.GO): ["go mod download"],
    (Framework.RUST, PackageManager.CARGO): [],  # cargo fetches deps on build
    (Framework.POWERSHELL, PackageManager.PSRESOURCEGET): [
        "pwsh -Command \"Install-Module -Name Pester -Force -SkipPublisherCheck\"",
        "pwsh -Command \"Install-Module -Name PSScriptAnalyzer -Force\"",
    ],
}


def generate_pipeline(
    info: FrameworkInfo,
    config: CICDConfig,
    output_dir: Optional[str | Path] = None,
) -> dict[str, str]:
    """Generate Woodpecker CI pipeline files based on config.

    Args:
        info: Detected framework information.
        config: CI/CD configuration.
        output_dir: Project root directory for writing files.

    Returns:
        Dict mapping filename to content for each generated file.
    """
    files: dict[str, str] = {
        ".woodpecker.yml": generate_woodpecker(info, config),
    }

    if output_dir:
        root = Path(output_dir)
        for filepath, content in files.items():
            full_path = root / filepath
            full_path.parent.mkdir(parents=True, exist_ok=True)
            full_path.write_text(content)

    return files


def generate_woodpecker(info: FrameworkInfo, config: CICDConfig) -> str:
    """Generate a Woodpecker CI pipeline.

    Args:
        info: Detected framework information.
        config: CI/CD configuration.

    Returns:
        YAML string for .woodpecker.yml
    """
    fw = info.framework
    pm = info.package_manager
    branches = config.pipeline.branches
    image = _WOODPECKER_IMAGES.get(fw, "ubuntu:24.04")
    install_cmds = _WOODPECKER_INSTALL.get((fw, pm), [])
    deploy_targets = set(branches.get("main", []))
    deploy_uses_aws = "deploy" in deploy_targets and config.pipeline.aws_secrets.required
    aws_secret_id = _aws_secret_id(config)
    aws_region = config.pipeline.aws_secrets.region

    lines: list[str] = []
    lines.append("# Generated by Codex Power Pack /cicd:pipeline")
    lines.append("# https://woodpecker-ci.org/docs/usage/pipeline-syntax")
    if deploy_uses_aws:
        lines.append("# Deploy secrets are resolved from AWS Secrets Manager.")
    lines.append("")

    # When clause (branch filtering)
    lines.append("when:")
    lines.append("  branch: [main]")
    lines.append("  event: [push, pull_request]")
    lines.append("")

    # Steps
    lines.append("steps:")

    # Use PR steps (superset for CI), fall back to main
    steps = branches.get("pr", branches.get("main", ["lint", "test"]))

    for step in steps:
        lines.append(f"  - name: {step}")
        lines.append(f"    image: {image}")
        lines.append("    commands:")
        for cmd in install_cmds:
            lines.append(f"      - {cmd}")
        lines.append(f"      - make {step}")
        lines.append("")

    # Deploy step (only on main push)
    main_steps = branches.get("main", [])
    if deploy_uses_aws:
        lines.append("  - name: aws-secretsmanager-preflight")
        lines.append(f"    image: {_AWS_CLI_IMAGE}")
        lines.append("    commands:")
        lines.append(
            "      - printf 'Validating AWS Secrets Manager bundle %s in %s\\n' "
            f"\"{aws_secret_id}\" \"${{AWS_REGION:-{aws_region}}}\""
        )
        lines.append("      - aws sts get-caller-identity >/dev/null")
        lines.append(
            "      - aws secretsmanager describe-secret "
            f"--region \"${{AWS_REGION:-{aws_region}}}\" "
            f"--secret-id \"{aws_secret_id}\" >/dev/null"
        )
        lines.append("    when:")
        lines.append("      branch: main")
        lines.append("      event: push")
        lines.append("")

    if "deploy" in main_steps:
        lines.append("  - name: deploy")
        lines.append(f"    image: {image}")
        if deploy_uses_aws:
            lines.append("    environment:")
            lines.append('      CPP_SECRETS_PROVIDER: "aws-secrets-manager"')
            lines.append(f'      CPP_AWS_SECRET_ID: "{aws_secret_id}"')
            lines.append(f'      AWS_REGION: "{aws_region}"')
            if config.pipeline.secrets_needed:
                required_keys = ",".join(config.pipeline.secrets_needed)
                lines.append(f'      CPP_AWS_REQUIRED_KEYS: "{required_keys}"')
        lines.append("    commands:")
        for cmd in install_cmds:
            lines.append(f"      - {cmd}")
        if deploy_uses_aws:
            lines.append("      - printf 'Deploy secrets provider: %s\\n' \"$CPP_SECRETS_PROVIDER\"")
            lines.append("      - printf 'AWS secret bundle: %s\\n' \"$CPP_AWS_SECRET_ID\"")
            if config.pipeline.secrets_needed:
                lines.append("      - printf 'Expected AWS keys: %s\\n' \"$CPP_AWS_REQUIRED_KEYS\"")
        lines.append("      - make deploy")
        lines.append("    when:")
        lines.append("      branch: main")
        lines.append("      event: push")
        lines.append("")

    return "\n".join(lines)


def _aws_secret_id(config: CICDConfig) -> str:
    """Return the AWS Secrets Manager bundle identifier for deploy pipelines."""
    aws_secrets = config.pipeline.aws_secrets
    project_id = aws_secrets.project_id or "${CI_REPO_NAME:-change-me}"
    return f"{aws_secrets.bundle_prefix}/{project_id}"
