"""CI/CD pipeline generation.

Generates Woodpecker CI pipelines from detected framework information
and configuration.
"""

from __future__ import annotations

from pathlib import Path
from typing import Optional

from .config import CICDConfig
from .models import Framework, FrameworkInfo, PackageManager

# Docker images for Woodpecker CI steps
_WOODPECKER_IMAGES: dict[Framework, str] = {
    Framework.PYTHON: "python:3.12",
    Framework.NODE: "node:22",
    Framework.GO: "golang:1.23",
    Framework.RUST: "rust:1.82",
    Framework.POWERSHELL: "mcr.microsoft.com/powershell:7.4-ubuntu-24.04",
    Framework.MULTI: "ubuntu:24.04",
    Framework.UNKNOWN: "ubuntu:24.04",
}

# Python version matrices by framework
_DEFAULT_MATRIX: dict[Framework, dict[str, list[str]]] = {
    Framework.PYTHON: {"python-version": ["3.11", "3.12"]},
    Framework.NODE: {"node-version": ["20", "22"]},
    Framework.GO: {"go-version": ["1.22", "1.23"]},
    Framework.RUST: {"rust-version": ["stable"]},
    Framework.POWERSHELL: {"os": ["ubuntu-latest", "windows-latest"]},
}

# Install commands for Woodpecker CI
_WOODPECKER_INSTALL: dict[tuple[Framework, PackageManager], list[str]] = {
    (Framework.PYTHON, PackageManager.UV): ["pip install uv", "uv sync"],
    (Framework.PYTHON, PackageManager.PIP): ["pip install -r requirements.txt"],
    (Framework.PYTHON, PackageManager.POETRY): ["pip install poetry", "poetry install"],
    (Framework.NODE, PackageManager.NPM): ["npm ci"],
    (Framework.NODE, PackageManager.YARN): ["yarn install --frozen-lockfile"],
    (Framework.NODE, PackageManager.PNPM): ["corepack enable", "pnpm install --frozen-lockfile"],
    (Framework.GO, PackageManager.GO): ["go mod download"],
    (Framework.RUST, PackageManager.CARGO): [],  # cargo fetches deps on build
    (Framework.POWERSHELL, PackageManager.PSRESOURCEGET): [
        "pwsh -Command \"Install-Module -Name Pester -Force -SkipPublisherCheck\"",
        "pwsh -Command \"Install-Module -Name PSScriptAnalyzer -Force\"",
    ],
}


def generate_pipeline(
    info: FrameworkInfo,
    config: CICDConfig,
    output_dir: Optional[str | Path] = None,
) -> dict[str, str]:
    """Generate Woodpecker CI pipeline files based on config.

    Args:
        info: Detected framework information.
        config: CI/CD configuration.
        output_dir: Project root directory for writing files.

    Returns:
        Dict mapping filename to content for each generated file.
    """
    files: dict[str, str] = {
        ".woodpecker.yml": generate_woodpecker(info, config),
    }

    if output_dir:
        root = Path(output_dir)
        for filepath, content in files.items():
            full_path = root / filepath
            full_path.parent.mkdir(parents=True, exist_ok=True)
            full_path.write_text(content)

    return files


def generate_woodpecker(info: FrameworkInfo, config: CICDConfig) -> str:
    """Generate a Woodpecker CI pipeline.

    Args:
        info: Detected framework information.
        config: CI/CD configuration.

    Returns:
        YAML string for .woodpecker.yml
    """
    fw = info.framework
    pm = info.package_manager
    branches = config.pipeline.branches
    image = _WOODPECKER_IMAGES.get(fw, "ubuntu:24.04")
    install_cmds = _WOODPECKER_INSTALL.get((fw, pm), [])

    lines: list[str] = []
    lines.append("# Generated by Codex Power Pack /cicd:pipeline")
    lines.append("# https://woodpecker-ci.org/docs/usage/pipeline-syntax")
    lines.append("")

    # When clause (branch filtering)
    lines.append("when:")
    lines.append("  branch: [main]")
    lines.append("  event: [push, pull_request]")
    lines.append("")

    # Steps
    lines.append("steps:")

    # Use PR steps (superset for CI), fall back to main
    steps = branches.get("pr", branches.get("main", ["lint", "test"]))

    for step in steps:
        lines.append(f"  - name: {step}")
        lines.append(f"    image: {image}")
        lines.append("    commands:")
        for cmd in install_cmds:
            lines.append(f"      - {cmd}")
        lines.append(f"      - make {step}")
        lines.append("")

    # Deploy step (only on main push)
    main_steps = branches.get("main", [])
    if "deploy" in main_steps:
        lines.append("  - name: deploy")
        lines.append(f"    image: {image}")
        lines.append("    commands:")
        for cmd in install_cmds:
            lines.append(f"      - {cmd}")
        lines.append("      - make deploy")
        lines.append("    when:")
        lines.append("      branch: main")
        lines.append("      event: push")

        # Secrets
        if config.pipeline.secrets_needed:
            lines.append("    secrets:")
            for secret in config.pipeline.secrets_needed:
                lines.append(f"      - {secret.lower()}")
        lines.append("")

    return "\n".join(lines)
