#!/usr/bin/env python3
"""codex_skills_sync.py - vendor + drift-gate the CPP-generated Codex skills (pull model).

codex-power-pack#75 (epic #64, single source-of-truth bridge): CxPP does NOT author
the shared CPP command families. claude-power-pack (CPP) authors those once in
`.claude/commands/<family>/` and generates per-command Codex skill dirs under its
`codex/skills/`. This repo PULLS that generated output - pinned by CPP commit SHA -
into `.codex/skills/`, and gates drift so a hand-edit of a generated skill fails CI.
CxPP-owned native skill families may also live under `.codex/skills/`; they are
explicitly excluded from this vendored manifest and refresh/prune logic.

Surfaces:
    .codex/skills/<family>-<cmd>/     generated skill dirs (SKILL.md [+ reference.md]
                                      [+ scripts/*]), byte-identical to CPP output.
    .codex/skills/agents-md-*/        CxPP-authored native AGENTS.md skills (not
                                      vendored; not covered by the drift manifest).
    .codex/skills/project-next/       CxPP-authored native project triage skill
    .codex/skills/project-lite/       CxPP-authored native project orientation skill
    .codex/skills/cxpp-*/             CxPP-authored host bootstrap/status skills
    .codex/skills/spec-*/             CxPP-authored spec-kit workflow skills
    .codex/skills/woodpecker-*/       CxPP-authored Woodpecker API client skills
    .codex/skills/README.md           CxPP-authored surface note (NOT vendored; not
                                      covered by the drift manifest).
    vendor/claude-power-pack/PIN      provenance: CPP repo URL + pinned commit SHA.
    vendor/claude-power-pack/codex-skills.sha256
                                      integrity manifest (`<sha256>  <relpath>`) of
                                      every generated file under `.codex/skills/`.

Modes:
    --check   (default) recompute `.codex/skills/` hashes, compare to the manifest,
              and assert every skill's SKILL.md carries the CPP GENERATED marker;
              exit 1 on any drift. Git-free and network-free, so it runs unchanged in
              the `uv:python3.11` validate container.
    --write   re-snapshot the manifest from the current `.codex/skills/` tree (bless a
              fresh refresh). Fetches nothing.
    --refresh --cpp-root PATH [--ref SHA]
              (maintainer) mirror `<cpp-root>/codex/skills/<dir>/` -> `.codex/skills/`,
              update PIN, then re-snapshot the manifest.
    --source-check --cpp-root PATH
              compare the adopted, Codex-adapted payload with a CPP checkout;
              used by CI after a shallow upstream clone to catch stale pins.

Reconcile rule (hybrid SoT): for generated shared families, edit the SOURCE in claude-power-pack
`.claude/commands/<family>/`, regenerate CPP's `codex/skills/` (`make codex-skills`
there), then re-run this with `--refresh` here. For CxPP-owned native families,
edit their `.codex/skills/<name>/` package directly and keep the allowlist below
narrow.
"""

from __future__ import annotations

import argparse
import hashlib
import re
import shutil
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
SKILLS_ROOT = REPO_ROOT / ".codex" / "skills"
VENDOR_DIR = REPO_ROOT / "vendor" / "claude-power-pack"
MANIFEST_PATH = VENDOR_DIR / "codex-skills.sha256"
PIN_PATH = VENDOR_DIR / "PIN"
PLUGINS_ROOT = REPO_ROOT / "plugins"

CPP_REPO_URL = "https://github.com/cooneycw/claude-power-pack"

# The GENERATED marker CPP's codex-skill-sync.py stamps into every skill it emits.
MARKER_PREFIX = "<!-- GENERATED by claude-power-pack"

# Shared families CPP generates that CxPP does NOT adopt (a CxPP-owned pull policy).
# `claude-md` is Out-of-Scope per the plugin-marketplace-modernization spec: CxPP is
# the AGENTS.md world, and a Codex-native `agents-md` family covers it (epic #64/#66),
# so CPP's CLAUDE.md-oriented claude-md skills are not pulled here (codex-power-pack#75).
PULL_EXCLUDE_FAMILIES = {"claude-md", "agents-md"}

# CxPP-owned top-level files that live under .codex/skills/ but are NOT pulled from
# CPP, so the drift manifest and copy/prune logic must leave them alone.
LOCAL_FILES = {"README.md"}

# CxPP-owned native skill dirs under .codex/skills/. These are edited in this repo
# and intentionally do not carry the CPP GENERATED marker. Keep this narrow and
# explicit so generated CPP skill drift remains protected.
LOCAL_SKILL_DIRS = {
    "agents-md-help",
    "agents-md-lint",
    "cxpp-init",
    "cxpp-status",
    "cxpp-update",
    "documentation-c4",
    "documentation-pptx",
    "project-lite",
    "project-init",
    "project-next",
    "qa-help",
    "qa-test",
    "second-opinion-help",
    "second-opinion-models",
    "second-opinion-start",
    "security-deep",
    "security-help",
    "security-quick",
    "security-scan",
    "self-improvement-retro",
    "spec-adopt",
    "spec-sync",
    "evaluate-issue",
    "woodpecker-help",
    "woodpecker-logs",
    "woodpecker-restart",
    "woodpecker-status",
}

# Helpers that execute as part of an installed flow skill.  CPP's generated
# references use Claude's stable ~/.claude/scripts location; Codex plugins do
# not populate that directory.  CxPP ships these files inside each skill and
# resolves them from the skill package instead (issue #139).
FLOW_RUNTIME_HELPERS = {
    "check-ignored-additions.sh",
    "flow-live-driver-guard.sh",
    "flow-stale-check.sh",
    "flow-start-resolve.sh",
    "flow-worktree-guard.sh",
    "friction-log.sh",
    "gh-pr-merge.sh",
    "hook-permission-census.sh",
    "worktree-remove.sh",
}

SKILL_DIR_TOKEN = "<SKILL_DIR>"
_GENERIC_WORKTREE_ADAPTATION = (
    "- Native worktrees (`EnterWorktree`/`ExitWorktree` tool calls,"
    " `.claude/worktrees/` paths): use plain git instead -"
    " `git worktree add <path> -b <branch>`, work inside it, then"
    " `git worktree remove <path>` when done."
)
_CXPP_WORKTREE_ADAPTATION = (
    "- Codex worktrees: use the bundled resolver and plain git. Worktrees live"
    " at `$FLOW_WORKTREE_BASE/<repo>-<branch>` when configured, otherwise as a"
    " visible sibling `../<repo>-<branch>`; enter with `cd` and clean up with"
    " `git worktree remove`. Never use Claude's hidden worktree directory."
)
_SKILL_HELPER_PREAMBLE = f"""## Codex installed-skill runtime contract

`{SKILL_DIR_TOKEN}` below means the absolute directory containing this loaded
skill's `SKILL.md`. Resolve it from the skill locator before running a command;
never interpret bundled helper paths relative to the target repository. The
bundled resolver always selects the plain-git lane and creates visible sibling
worktrees (or uses `FLOW_WORKTREE_BASE` when configured).

"""
_GITHUB_REPO_PREAMBLE = """## Codex target-repository contract

Resolve `REPO` from an explicit `owner/repo` argument when supplied; otherwise
run `gh repo view --json nameWithOwner --jq .nameWithOwner` in the current
checkout. Pass `--repo "$REPO"` to every issue command. If neither source can
resolve a repository, ask the user before performing a write.

"""
_CODEX_DOCTOR_HELPERS = f"""# Installed Codex flow helper family (issue #139).
# Resolve SKILL_DIR from this loaded flow-doctor skill before running.
FLOW_SKILLS_ROOT="{SKILL_DIR_TOKEN}/.."
for script in flow-start-resolve.sh flow-stale-check.sh flow-worktree-guard.sh \
  flow-live-driver-guard.sh gh-pr-merge.sh; do
  helper=$(find "$FLOW_SKILLS_ROOT" -path "*/scripts/$script" -type f -perm -u+x -print -quit)
  if [ -n "$helper" ]; then
    echo "PASS $script (bundled Codex flow helper)"
  else
    echo "FAIL $script (missing from installed flow plugin; reinstall or upgrade flow@codex-power-pack)"
  fi
done"""


def _is_local_path(path: Path) -> bool:
    rel = path.relative_to(SKILLS_ROOT)
    first = rel.parts[0]
    return first in LOCAL_FILES or first in LOCAL_SKILL_DIRS


def _generated_files() -> list[Path]:
    """Every pulled file under .codex/skills/ - i.e. files inside a skill subdir.

    Top-level files and CxPP-owned native skill dirs are excluded: they are owned
    here, not vendored, so they are not part of the drift surface.
    """
    if not SKILLS_ROOT.is_dir():
        return []
    return sorted(
        p
        for p in SKILLS_ROOT.rglob("*")
        if p.is_file() and not _is_local_path(p) and len(p.relative_to(SKILLS_ROOT).parts) > 1
    )


def _rel(path: Path) -> str:
    return path.relative_to(SKILLS_ROOT).as_posix()


def _sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def compute_manifest() -> dict[str, str]:
    """Map `<relpath>` -> sha256 for every generated file under .codex/skills/."""
    return {_rel(p): _sha256(p) for p in _generated_files()}


def format_manifest(manifest: dict[str, str]) -> str:
    lines = [f"{digest}  {rel}" for rel, digest in sorted(manifest.items())]
    return "\n".join(lines) + ("\n" if lines else "")


def read_manifest() -> dict[str, str]:
    if not MANIFEST_PATH.is_file():
        return {}
    manifest: dict[str, str] = {}
    for line in MANIFEST_PATH.read_text().splitlines():
        line = line.strip()
        if not line:
            continue
        digest, _, rel = line.partition("  ")
        manifest[rel] = digest
    return manifest


def _skill_dirs() -> list[Path]:
    if not SKILLS_ROOT.is_dir():
        return []
    return sorted(d for d in SKILLS_ROOT.iterdir() if d.is_dir())


def _generated_skill_dirs() -> list[Path]:
    return sorted(d for d in _skill_dirs() if d.name not in LOCAL_SKILL_DIRS)


def _marker_violations() -> list[str]:
    """Skill dirs whose SKILL.md is missing or does not carry the GENERATED marker."""
    violations: list[str] = []
    for skill_dir in _generated_skill_dirs():
        skill_md = skill_dir / "SKILL.md"
        if not skill_md.is_file():
            violations.append(f"{skill_dir.name}: no SKILL.md")
        elif MARKER_PREFIX not in skill_md.read_text():
            violations.append(f"{skill_dir.name}: SKILL.md missing GENERATED marker")
    return violations


def run_check() -> int:
    expected = read_manifest()
    if not expected:
        print(
            "codex-skills-sync: no manifest at"
            f" {MANIFEST_PATH.relative_to(REPO_ROOT)}; run --refresh to pull from CPP.",
            file=sys.stderr,
        )
        return 1

    actual = compute_manifest()
    drift = 0

    for rel in sorted(set(expected) - set(actual)):
        print(f"MISSING: .codex/skills/{rel} (in manifest, not on disk)")
        drift = 1
    for rel in sorted(set(actual) - set(expected)):
        print(f"EXTRA: .codex/skills/{rel} (on disk, not in manifest)")
        drift = 1
    for rel in sorted(set(expected) & set(actual)):
        if expected[rel] != actual[rel]:
            print(f"DRIFT: .codex/skills/{rel} differs from the vendored (pinned) copy")
            drift = 1

    for violation in _marker_violations():
        print(f"MARKER: .codex/skills/{violation}")
        drift = 1

    if drift:
        print(
            "\ncodex-skills-sync: DRIFT detected. These are generated from"
            " claude-power-pack; do not hand-edit. To reconcile, edit the SOURCE in"
            " claude-power-pack .claude/commands/<family>/, regenerate there"
            " (make codex-skills), then re-run: scripts/codex_skills_sync.py --refresh"
            " --cpp-root <path>",
            file=sys.stderr,
        )
        return 1

    print(f"codex-skills-sync: {len(actual)} file(s) across {len(_generated_skill_dirs())} generated skill(s) in sync")
    return 0


def run_write() -> int:
    VENDOR_DIR.mkdir(parents=True, exist_ok=True)
    manifest = compute_manifest()
    MANIFEST_PATH.write_text(format_manifest(manifest))
    print(
        f"codex-skills-sync: snapshot {len(manifest)} file(s) ->"
        f" {MANIFEST_PATH.relative_to(REPO_ROOT)}"
    )
    return 0


def _write_pin(ref: str) -> None:
    VENDOR_DIR.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Pinned claude-power-pack source for the generated Codex skills (pull model).",
        "# Managed by scripts/codex_skills_sync.py --refresh; do not hand-edit.",
        f"repo: {CPP_REPO_URL}",
        f"commit: {ref}",
        "pulls: codex/skills/  ->  .codex/skills/",
        "",
    ]
    PIN_PATH.write_text("\n".join(lines))


def _source_skill_dirs(cpp_root: Path) -> list[Path]:
    src_root = cpp_root / "codex" / "skills"
    if not src_root.is_dir():
        return []
    excluded_prefixes = tuple(f"{fam}-" for fam in PULL_EXCLUDE_FAMILIES)
    return sorted(
        d
        for d in src_root.iterdir()
        if d.is_dir()
        and (d / "SKILL.md").is_file()
        and not d.name.startswith(excluded_prefixes)
        # A newly generated upstream command must never overwrite a native
        # CxPP skill with the same name (#135/#139).
        and d.name not in LOCAL_SKILL_DIRS
    )


def _adapt_flow_text(skill_dir: Path, source_file: Path, text: str) -> str:
    """Apply the narrow CxPP-owned Codex runtime overlay to flow payloads."""
    if not skill_dir.name.startswith("flow-"):
        return text

    text = text.replace(_GENERIC_WORKTREE_ADAPTATION, _CXPP_WORKTREE_ADAPTATION)
    text = text.replace(".claude/friction.jsonl", ".codex/friction.jsonl")

    for helper in sorted(FLOW_RUNTIME_HELPERS):
        helper_owner = next(
            (
                candidate
                for candidate in (
                    skill_dir,
                    skill_dir.parent / "flow-start",
                    skill_dir.parent / "flow-auto",
                    skill_dir.parent / "flow-merge",
                )
                if (candidate / "scripts" / helper).is_file()
            ),
            None,
        )
        if helper_owner is None:
            continue
        if helper_owner == skill_dir:
            resolved = f"{SKILL_DIR_TOKEN}/scripts/{helper}"
        else:
            resolved = f"{SKILL_DIR_TOKEN}/../{helper_owner.name}/scripts/{helper}"
        text = text.replace(f"~/.claude/scripts/{helper}", resolved)
        text = re.sub(
            rf"(?<![/A-Za-z0-9_.-])scripts/{re.escape(helper)}",
            resolved,
            text,
        )

    # Generated references describe Claude's native hidden worktrees.  The
    # SKILL.md adaptation and resolver below are authoritative for Codex, but
    # remove the stale path spellings as well so examples cannot be followed
    # literally and the harness lint remains meaningful.
    text = text.replace(".claude/worktrees", "../<repo>-<branch>")
    text = text.replace(
        "Helpers are invoked bare at their stable `~/.claude/scripts/` paths",
        "Helpers are invoked by absolute path from the installed Codex skill package",
    )

    if skill_dir.name == "flow-doctor" and source_file.name == "reference.md":
        text = re.sub(
            r"# Flow helper family \(issue #581\):.*?^done$",
            _CODEX_DOCTOR_HELPERS,
            text,
            count=1,
            flags=re.MULTILINE | re.DOTALL,
        )
        text = text.replace(
            "| Flow helper family | ✅/⚠️ | flow-start-resolve, flow-stale-check,"
            " flow-worktree-guard, flow-live-driver-guard, gh-pr-merge at"
            " ~/.claude/scripts/ (zero-prompt lane, #581) |",
            "| Flow helper family | ✅/❌ | Bundled executable helpers in the installed"
            " flow skill packages (#139) |",
        )
        text = text.replace(
            "2c. ⚠️ **Flow helper(s) not at ~/.claude/scripts/** - the #581 zero-prompt"
            " lane degrades to CPP-checkout fallback paths, which prompt. Run"
            " `/cpp:update` (Step 5b re-links new scripts) or `/cpp:init` Tier 2",
            "2c. ❌ **Bundled Codex flow helper(s) missing** - reinstall or upgrade"
            " `flow@codex-power-pack`; a CPP clone is not required.",
        )

    if source_file.name == "reference.md" and SKILL_DIR_TOKEN in text:
        marker_end = text.find("\n\n")
        if marker_end != -1 and _SKILL_HELPER_PREAMBLE not in text:
            text = text[: marker_end + 2] + _SKILL_HELPER_PREAMBLE + text[marker_end + 2 :]
    return text


def _adapt_flow_resolver(text: str) -> str:
    """Make CPP's resolver use Codex's plain-git visible-worktree lane."""
    text = text.replace(
        "GIT_LANE=$CROSS_REPO\n[ -n \"${FLOW_WORKTREE_BASE:-}\" ] && GIT_LANE=1",
        "# Codex has no EnterWorktree tool: every lane uses plain git.\nGIT_LANE=1",
    )
    text = text.replace(
        'echo "$TARGET_REPO/.claude/worktrees/$1"',
        'echo "$(dirname "$TARGET_REPO")/$(basename "$TARGET_REPO")-$1"',
    )
    text = text.replace(
        "<target repo>/.claude/worktrees/<branch>",
        "<target repo parent>/<repo>-<branch>",
    )
    text = text.replace(".claude/worktrees", "visible sibling worktrees")
    return text


def _adapt_github_text(skill_dir: Path, source_file: Path, text: str) -> str:
    """Keep shared GitHub skills repository-neutral on the CxPP surface."""
    if not skill_dir.name.startswith("github-"):
        return text
    text = text.replace("cooneycw/claude-power-pack", '"$REPO"')
    if source_file.name == "SKILL.md" and _GITHUB_REPO_PREAMBLE not in text:
        marker_end = text.find("\n\n")
        if marker_end != -1:
            text = text[: marker_end + 2] + _GITHUB_REPO_PREAMBLE + text[marker_end + 2 :]
    return text


def _adapted_source_files(skill_dir: Path) -> dict[str, bytes]:
    files: dict[str, bytes] = {}
    for source_file in sorted(path for path in skill_dir.rglob("*") if path.is_file()):
        rel = source_file.relative_to(skill_dir).as_posix()
        try:
            text = source_file.read_text()
        except UnicodeDecodeError:
            files[rel] = source_file.read_bytes()
            continue
        if rel == "scripts/flow-start-resolve.sh":
            text = _adapt_flow_resolver(text)
        text = _adapt_flow_text(skill_dir, source_file, text)
        text = _adapt_github_text(skill_dir, source_file, text)
        files[rel] = text.encode()
    return files


def _write_skill_payload(src_dir: Path, dest: Path) -> None:
    if dest.exists():
        shutil.rmtree(dest)
    for rel, payload in _adapted_source_files(src_dir).items():
        target = dest / rel
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_bytes(payload)
        source = src_dir / rel
        shutil.copymode(source, target)


def _sync_plugin_payload(skill_name: str) -> None:
    """Mirror an adopted skill into an existing plugin, preserving UI metadata."""
    source = SKILLS_ROOT / skill_name
    candidates = sorted(
        (
            plugin_dir / "skills" / skill_name
            for plugin_dir in PLUGINS_ROOT.iterdir()
            if plugin_dir.is_dir()
        ),
        key=lambda path: len(path.parts),
    )
    for destination in candidates:
        if not destination.is_dir():
            continue
        agents_dir = destination / "agents"
        for existing in list(destination.iterdir()):
            if existing == agents_dir:
                continue
            if existing.is_dir():
                shutil.rmtree(existing)
            else:
                existing.unlink()
        for source_file in sorted(path for path in source.rglob("*") if path.is_file()):
            rel = source_file.relative_to(source)
            if rel.parts[0] == "agents":
                continue
            target = destination / rel
            target.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(source_file, target)
        return


def run_source_check(cpp_root: Path) -> int:
    """Fail when the adopted generated payload differs from a CPP checkout."""
    src_dirs = _source_skill_dirs(cpp_root)
    if not src_dirs:
        print(f"codex-skills-sync: no generated skills under {cpp_root}", file=sys.stderr)
        return 2

    expected: dict[str, bytes] = {}
    for src_dir in src_dirs:
        for rel, payload in _adapted_source_files(src_dir).items():
            expected[f"{src_dir.name}/{rel}"] = payload
    actual = {
        _rel(path): path.read_bytes()
        for path in _generated_files()
    }

    stale = sorted(rel for rel in set(expected) | set(actual) if expected.get(rel) != actual.get(rel))
    if stale:
        for rel in stale:
            print(f"UPSTREAM-DRIFT: .codex/skills/{rel}")
        print(
            "codex-skills-sync: vendored skills differ from the supplied CPP source;"
            " run --refresh with that checkout",
            file=sys.stderr,
        )
        return 1
    print(f"codex-skills-sync: {len(actual)} vendored file(s) current with {cpp_root}")
    return 0


def run_refresh(cpp_root: Path, ref: str) -> int:
    src_root = cpp_root / "codex" / "skills"
    if not src_root.is_dir():
        print(
            f"codex-skills-sync: no generated skills at {src_root}"
            " (is --cpp-root a claude-power-pack checkout?)",
            file=sys.stderr,
        )
        return 2

    src_dirs = _source_skill_dirs(cpp_root)
    if not src_dirs:
        print(f"codex-skills-sync: no skill dirs under {src_root}", file=sys.stderr)
        return 2

    SKILLS_ROOT.mkdir(parents=True, exist_ok=True)
    wanted = {d.name for d in src_dirs}

    # Prune generated skill dirs that no longer exist upstream (keep CxPP-owned skill dirs).
    for existing in _skill_dirs():
        if existing.name in LOCAL_SKILL_DIRS:
            continue
        if existing.name not in wanted:
            shutil.rmtree(existing)
            print(f"codex-skills-sync: pruned {existing.name} (no longer generated upstream)")

    for src_dir in src_dirs:
        dest = SKILLS_ROOT / src_dir.name
        _write_skill_payload(src_dir, dest)
        _sync_plugin_payload(src_dir.name)

    _write_pin(ref)
    print(
        f"codex-skills-sync: pulled {len(src_dirs)} skill(s) from {CPP_REPO_URL}@{ref[:12]}"
    )
    return run_write()


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Vendor + drift-gate the CPP-generated Codex skills (pull model)."
    )
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--check", action="store_true", help="fail on drift (default)")
    mode.add_argument("--write", action="store_true", help="re-snapshot the drift manifest")
    mode.add_argument(
        "--refresh",
        action="store_true",
        help="mirror <cpp-root>/codex/skills/ -> .codex/skills/, update PIN + manifest",
    )
    mode.add_argument(
        "--source-check",
        action="store_true",
        help="compare vendored skills with <cpp-root> after Codex runtime adaptations",
    )
    parser.add_argument("--cpp-root", type=Path, help="path to a claude-power-pack checkout (with --refresh)")
    parser.add_argument("--ref", default="", help="the CPP commit SHA being pinned (with --refresh)")
    args = parser.parse_args(argv)

    if args.refresh:
        if args.cpp_root is None:
            parser.error("--refresh requires --cpp-root")
        return run_refresh(args.cpp_root.expanduser().resolve(), args.ref or "unknown")
    if args.source_check:
        if args.cpp_root is None:
            parser.error("--source-check requires --cpp-root")
        return run_source_check(args.cpp_root.expanduser().resolve())
    if args.write:
        return run_write()
    return run_check()


if __name__ == "__main__":
    sys.exit(main())
