#!/usr/bin/env python3
"""codex_skills_sync.py - vendor + drift-gate the CPP-generated Codex skills (pull model).

codex-power-pack#75 (epic #64, single source-of-truth bridge): CxPP does NOT author
the shared CPP command families. claude-power-pack (CPP) authors those once in
`.claude/commands/<family>/` and generates per-command Codex skill dirs under its
`codex/skills/`. This repo PULLS that generated output - pinned by CPP commit SHA -
into `.codex/skills/`, and gates drift so a hand-edit of a generated skill fails CI.
CxPP-owned native skill families may also live under `.codex/skills/`; they are
explicitly excluded from this vendored manifest and refresh/prune logic.

Surfaces:
    .codex/skills/<family>-<cmd>/     generated skill dirs (SKILL.md [+ reference.md]
                                      [+ scripts/*]), byte-identical to CPP output.
    .codex/skills/agents-md-*/        CxPP-authored native AGENTS.md skills (not
                                      vendored; not covered by the drift manifest).
    .codex/skills/README.md           CxPP-authored surface note (NOT vendored; not
                                      covered by the drift manifest).
    vendor/claude-power-pack/PIN      provenance: CPP repo URL + pinned commit SHA.
    vendor/claude-power-pack/codex-skills.sha256
                                      integrity manifest (`<sha256>  <relpath>`) of
                                      every generated file under `.codex/skills/`.

Modes:
    --check   (default) recompute `.codex/skills/` hashes, compare to the manifest,
              and assert every skill's SKILL.md carries the CPP GENERATED marker;
              exit 1 on any drift. Git-free and network-free, so it runs unchanged in
              the `uv:python3.11` validate container.
    --write   re-snapshot the manifest from the current `.codex/skills/` tree (bless a
              fresh refresh). Fetches nothing.
    --refresh --cpp-root PATH [--ref SHA]
              (maintainer) mirror `<cpp-root>/codex/skills/<dir>/` -> `.codex/skills/`,
              update PIN, then re-snapshot the manifest.

Reconcile rule (hybrid SoT): for generated shared families, edit the SOURCE in claude-power-pack
`.claude/commands/<family>/`, regenerate CPP's `codex/skills/` (`make codex-skills`
there), then re-run this with `--refresh` here. For CxPP-owned native families,
edit their `.codex/skills/<name>/` package directly and keep the allowlist below
narrow.
"""

from __future__ import annotations

import argparse
import hashlib
import shutil
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
SKILLS_ROOT = REPO_ROOT / ".codex" / "skills"
VENDOR_DIR = REPO_ROOT / "vendor" / "claude-power-pack"
MANIFEST_PATH = VENDOR_DIR / "codex-skills.sha256"
PIN_PATH = VENDOR_DIR / "PIN"

CPP_REPO_URL = "https://github.com/cooneycw/claude-power-pack"

# The GENERATED marker CPP's codex-skill-sync.py stamps into every skill it emits.
MARKER_PREFIX = "<!-- GENERATED by claude-power-pack"

# Shared families CPP generates that CxPP does NOT adopt (a CxPP-owned pull policy).
# `claude-md` is Out-of-Scope per the plugin-marketplace-modernization spec: CxPP is
# the AGENTS.md world, and a Codex-native `agents-md` family covers it (epic #64/#66),
# so CPP's CLAUDE.md-oriented claude-md skills are not pulled here (codex-power-pack#75).
PULL_EXCLUDE_FAMILIES = {"claude-md", "agents-md"}

# CxPP-owned top-level files that live under .codex/skills/ but are NOT pulled from
# CPP, so the drift manifest and copy/prune logic must leave them alone.
LOCAL_FILES = {"README.md"}

# CxPP-owned native skill dirs under .codex/skills/. These are edited in this repo
# and intentionally do not carry the CPP GENERATED marker.
LOCAL_SKILL_DIRS = {"agents-md-help", "agents-md-lint"}


def _is_local_path(path: Path) -> bool:
    rel = path.relative_to(SKILLS_ROOT)
    first = rel.parts[0]
    return first in LOCAL_FILES or first in LOCAL_SKILL_DIRS


def _generated_files() -> list[Path]:
    """Every pulled file under .codex/skills/ - i.e. files inside a skill subdir.

    Top-level files and CxPP-owned native skill dirs are excluded: they are owned
    here, not vendored, so they are not part of the drift surface.
    """
    if not SKILLS_ROOT.is_dir():
        return []
    return sorted(
        p
        for p in SKILLS_ROOT.rglob("*")
        if p.is_file() and not _is_local_path(p) and len(p.relative_to(SKILLS_ROOT).parts) > 1
    )


def _rel(path: Path) -> str:
    return path.relative_to(SKILLS_ROOT).as_posix()


def _sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def compute_manifest() -> dict[str, str]:
    """Map `<relpath>` -> sha256 for every generated file under .codex/skills/."""
    return {_rel(p): _sha256(p) for p in _generated_files()}


def format_manifest(manifest: dict[str, str]) -> str:
    lines = [f"{digest}  {rel}" for rel, digest in sorted(manifest.items())]
    return "\n".join(lines) + ("\n" if lines else "")


def read_manifest() -> dict[str, str]:
    if not MANIFEST_PATH.is_file():
        return {}
    manifest: dict[str, str] = {}
    for line in MANIFEST_PATH.read_text().splitlines():
        line = line.strip()
        if not line:
            continue
        digest, _, rel = line.partition("  ")
        manifest[rel] = digest
    return manifest


def _skill_dirs() -> list[Path]:
    if not SKILLS_ROOT.is_dir():
        return []
    return sorted(d for d in SKILLS_ROOT.iterdir() if d.is_dir())


def _generated_skill_dirs() -> list[Path]:
    return sorted(d for d in _skill_dirs() if d.name not in LOCAL_SKILL_DIRS)


def _marker_violations() -> list[str]:
    """Skill dirs whose SKILL.md is missing or does not carry the GENERATED marker."""
    violations: list[str] = []
    for skill_dir in _generated_skill_dirs():
        skill_md = skill_dir / "SKILL.md"
        if not skill_md.is_file():
            violations.append(f"{skill_dir.name}: no SKILL.md")
        elif MARKER_PREFIX not in skill_md.read_text():
            violations.append(f"{skill_dir.name}: SKILL.md missing GENERATED marker")
    return violations


def run_check() -> int:
    expected = read_manifest()
    if not expected:
        print(
            "codex-skills-sync: no manifest at"
            f" {MANIFEST_PATH.relative_to(REPO_ROOT)}; run --refresh to pull from CPP.",
            file=sys.stderr,
        )
        return 1

    actual = compute_manifest()
    drift = 0

    for rel in sorted(set(expected) - set(actual)):
        print(f"MISSING: .codex/skills/{rel} (in manifest, not on disk)")
        drift = 1
    for rel in sorted(set(actual) - set(expected)):
        print(f"EXTRA: .codex/skills/{rel} (on disk, not in manifest)")
        drift = 1
    for rel in sorted(set(expected) & set(actual)):
        if expected[rel] != actual[rel]:
            print(f"DRIFT: .codex/skills/{rel} differs from the vendored (pinned) copy")
            drift = 1

    for violation in _marker_violations():
        print(f"MARKER: .codex/skills/{violation}")
        drift = 1

    if drift:
        print(
            "\ncodex-skills-sync: DRIFT detected. These are generated from"
            " claude-power-pack; do not hand-edit. To reconcile, edit the SOURCE in"
            " claude-power-pack .claude/commands/<family>/, regenerate there"
            " (make codex-skills), then re-run: scripts/codex_skills_sync.py --refresh"
            " --cpp-root <path>",
            file=sys.stderr,
        )
        return 1

    print(f"codex-skills-sync: {len(actual)} file(s) across {len(_generated_skill_dirs())} generated skill(s) in sync")
    return 0


def run_write() -> int:
    VENDOR_DIR.mkdir(parents=True, exist_ok=True)
    manifest = compute_manifest()
    MANIFEST_PATH.write_text(format_manifest(manifest))
    print(
        f"codex-skills-sync: snapshot {len(manifest)} file(s) ->"
        f" {MANIFEST_PATH.relative_to(REPO_ROOT)}"
    )
    return 0


def _write_pin(ref: str) -> None:
    VENDOR_DIR.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Pinned claude-power-pack source for the generated Codex skills (pull model).",
        "# Managed by scripts/codex_skills_sync.py --refresh; do not hand-edit.",
        f"repo: {CPP_REPO_URL}",
        f"commit: {ref}",
        "pulls: codex/skills/  ->  .codex/skills/",
        "",
    ]
    PIN_PATH.write_text("\n".join(lines))


def run_refresh(cpp_root: Path, ref: str) -> int:
    src_root = cpp_root / "codex" / "skills"
    if not src_root.is_dir():
        print(
            f"codex-skills-sync: no generated skills at {src_root}"
            " (is --cpp-root a claude-power-pack checkout?)",
            file=sys.stderr,
        )
        return 2

    excluded_prefixes = tuple(f"{fam}-" for fam in PULL_EXCLUDE_FAMILIES)
    src_dirs = sorted(
        d
        for d in src_root.iterdir()
        if d.is_dir()
        and (d / "SKILL.md").is_file()
        and not d.name.startswith(excluded_prefixes)
    )
    if not src_dirs:
        print(f"codex-skills-sync: no skill dirs under {src_root}", file=sys.stderr)
        return 2

    SKILLS_ROOT.mkdir(parents=True, exist_ok=True)
    wanted = {d.name for d in src_dirs}

    # Prune generated skill dirs that no longer exist upstream (keep CxPP-owned skill dirs).
    for existing in _skill_dirs():
        if existing.name in LOCAL_SKILL_DIRS:
            continue
        if existing.name not in wanted:
            shutil.rmtree(existing)
            print(f"codex-skills-sync: pruned {existing.name} (no longer generated upstream)")

    for src_dir in src_dirs:
        dest = SKILLS_ROOT / src_dir.name
        if dest.exists():
            shutil.rmtree(dest)
        shutil.copytree(src_dir, dest)

    _write_pin(ref)
    print(
        f"codex-skills-sync: pulled {len(src_dirs)} skill(s) from {CPP_REPO_URL}@{ref[:12]}"
    )
    return run_write()


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Vendor + drift-gate the CPP-generated Codex skills (pull model)."
    )
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--check", action="store_true", help="fail on drift (default)")
    mode.add_argument("--write", action="store_true", help="re-snapshot the drift manifest")
    mode.add_argument(
        "--refresh",
        action="store_true",
        help="mirror <cpp-root>/codex/skills/ -> .codex/skills/, update PIN + manifest",
    )
    parser.add_argument("--cpp-root", type=Path, help="path to a claude-power-pack checkout (with --refresh)")
    parser.add_argument("--ref", default="", help="the CPP commit SHA being pinned (with --refresh)")
    args = parser.parse_args(argv)

    if args.refresh:
        if args.cpp_root is None:
            parser.error("--refresh requires --cpp-root")
        return run_refresh(args.cpp_root.expanduser().resolve(), args.ref or "unknown")
    if args.write:
        return run_write()
    return run_check()


if __name__ == "__main__":
    sys.exit(main())
