#!/usr/bin/env python3
"""codex_skills_sync.py - vendor + drift-gate the CPP-generated Codex skills (pull model).

codex-power-pack#75 (epic #64, single source-of-truth bridge): CxPP does NOT author
the shared CPP command families. claude-power-pack (CPP) authors those once in
`.claude/commands/<family>/` and generates per-command Codex skill dirs under its
`codex/skills/`. This repo PULLS that generated output - pinned by CPP commit SHA -
into `.codex/skills/`, and gates drift so a hand-edit of a generated skill fails CI.
CxPP-owned native skill families may also live under `.codex/skills/`; they are
explicitly excluded from this vendored manifest and refresh/prune logic.

Surfaces:
    .codex/skills/<family>-<cmd>/     generated skill dirs (SKILL.md [+ reference.md]
                                      [+ scripts/*]), byte-identical to CPP output.
    .codex/skills/agents-md-*/        CxPP-authored native AGENTS.md skills (not
                                      vendored; not covered by the drift manifest).
    .codex/skills/project-next/       CxPP-authored deterministic project triage
                                      adapter; lib/project_next owns decisions
    .codex/skills/project-lite/       CxPP-authored native project orientation skill
    .codex/skills/codex-wayfinder/    CxPP-authored multi-session decision mapping
    .codex/skills/cxpp-*/             CxPP-authored host bootstrap/status skills
    .codex/skills/spec-*/             CxPP-authored spec-kit workflow skills
    .codex/skills/woodpecker-*/       CxPP-authored Woodpecker API client skills
    .codex/skills/README.md           CxPP-authored surface note (NOT vendored; not
                                      covered by the drift manifest).
    vendor/claude-power-pack/PIN      provenance: CPP repo URL + pinned commit SHA.
    vendor/claude-power-pack/codex-skills.sha256
                                      integrity manifest (`<sha256>  <relpath>`) of
                                      every generated file under `.codex/skills/`.

Modes:
    --check   (default) recompute `.codex/skills/` hashes, compare to the manifest,
              and assert every skill's SKILL.md carries the CPP GENERATED marker;
              exit 1 on any drift. Git-free and network-free, so it runs unchanged in
              the `uv:python3.11` validate container.
    --write   re-snapshot the manifest from the current `.codex/skills/` tree (bless a
              fresh refresh). Fetches nothing.
    --refresh --cpp-root PATH [--ref SHA]
              (maintainer) mirror `<cpp-root>/codex/skills/<dir>/` -> `.codex/skills/`,
              after validating the exact clean source/ref, update PIN, then
              re-snapshot the manifest.
    --source-check --cpp-root PATH
              compare the adopted, Codex-adapted payload with a CPP checkout;
              used by CI after a shallow upstream clone to catch stale pins.
    --pin-check --cpp-root PATH
              prove the checkout is the exact clean PIN and compare complete
              adapted/generated/manifest/plugin payload coverage and bytes.
    --pin-ref print the strictly parsed immutable commit for safe CI checkout.

Reconcile rule (hybrid SoT): for generated shared families, edit the SOURCE in claude-power-pack
`.claude/commands/<family>/`, regenerate CPP's `codex/skills/` (`make codex-skills`
there), then re-run this with `--refresh` here. For CxPP-owned native families,
edit their `.codex/skills/<name>/` package directly and keep the allowlist below
narrow.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import shutil
import subprocess
import sys
from pathlib import Path
from typing import NamedTuple

REPO_ROOT = Path(__file__).resolve().parent.parent
SKILLS_ROOT = REPO_ROOT / ".codex" / "skills"
VENDOR_DIR = REPO_ROOT / "vendor" / "claude-power-pack"
MANIFEST_PATH = VENDOR_DIR / "codex-skills.sha256"
PIN_PATH = VENDOR_DIR / "PIN"
PLUGINS_ROOT = REPO_ROOT / "plugins"

CPP_REPO_URL = "https://github.com/cooneycw/claude-power-pack"
PIN_PULL_SOURCE = "codex/skills/"
PIN_PULL_DESTINATION = ".codex/skills/"
PIN_FIELDS = {"repo", "commit", "pulls"}
COMMIT_RE = re.compile(r"[0-9a-f]{40}")
DIGEST_RE = re.compile(r"[0-9a-f]{64}")

# The GENERATED marker CPP's codex-skill-sync.py stamps into every skill it emits.
MARKER_PREFIX = "<!-- GENERATED by claude-power-pack"

# Shared families CPP generates that CxPP does NOT adopt (a CxPP-owned pull policy).
# `claude-md` is Out-of-Scope per the plugin-marketplace-modernization spec: CxPP is
# the AGENTS.md world, and a Codex-native `agents-md` family covers it (epic #64/#66),
# so CPP's CLAUDE.md-oriented claude-md skills are not pulled here (codex-power-pack#75).
PULL_EXCLUDE_FAMILIES = {"claude-md", "agents-md"}

# CxPP-owned top-level files that live under .codex/skills/ but are NOT pulled from
# CPP, so the drift manifest and copy/prune logic must leave them alone.
LOCAL_FILES = {"README.md"}

# CxPP-owned native skill dirs under .codex/skills/. These are edited in this repo
# and intentionally do not carry the CPP GENERATED marker. project-next is not a
# prompt-policy fork: docs/project-next-contract.md and lib/project_next are the
# authoritative cross-harness behavioral contract, while this native skill is a
# thin Codex adapter. Keep this allowlist narrow so generated CPP drift stays
# protected.
LOCAL_SKILL_DIRS = {
    "agents-md-help",
    "agents-md-lint",
    "claude-code-review",
    "codex-wayfinder",
    "cxpp-init",
    "cxpp-status",
    "cxpp-update",
    "documentation-c4",
    "documentation-pptx",
    "project-lite",
    "project-init",
    "project-next",
    "qa-help",
    "qa-test",
    "second-opinion-help",
    "second-opinion-models",
    "second-opinion-start",
    "security-deep",
    "security-help",
    "security-quick",
    "security-scan",
    "self-improvement-retro",
    "spec-adopt",
    "spec-sync",
    "evaluate-issue",
    "woodpecker-help",
    "woodpecker-logs",
    "woodpecker-restart",
    "woodpecker-status",
}

# Helpers that execute as part of an installed flow skill.  CPP's generated
# references use Claude's stable ~/.claude/scripts location; Codex plugins do
# not populate that directory.  CxPP ships these files inside each skill and
# resolves them from the skill package instead (issue #139).
FLOW_RUNTIME_HELPERS = {
    "check-ignored-additions.sh",
    "flow-finish-gate.sh",
    "flow-live-driver-guard.sh",
    "flow-stale-check.sh",
    "flow-start-resolve.sh",
    "flow-worktree-guard.sh",
    "friction-log.sh",
    "gh-pr-merge.sh",
    "hook-permission-census.sh",
    "worktree-remove.sh",
}

FLOW_AUTO_DESCRIPTION = (
    "Deliver an open GitHub issue end to end through an isolated worktree, "
    "necessity and approval gates, implementation, tests, PR, merge, CI, and "
    "optional deployment. Use for issue-lifecycle requests; do not use for "
    "questions, ordinary repository edits, or closed issues without approval."
)

LEGACY_SKILL_REPLACEMENTS = {
    "cpp-init": "cxpp-init",
    "cpp-status": "cxpp-status",
    "cpp-update": "cxpp-update",
    "codex-code_review": "claude-code-review",
}

_CODEX_PROJECT_HELP_BODY = """# Project Skills

Use project skills for three distinct goals. Select one explicitly with
`$skill-name`, discover installed skills with `/skills`, or describe the matching
goal in ordinary language when the skill is eligible for implicit selection.

| Goal | Owning skill | Boundary |
|---|---|---|
| Create a new local Python project | `$project-init` | Explicit-only; confirms the path and optional Git/commit |
| Orient quickly inside an existing repository | `$project-lite` | Read-only; never scaffolds a project |
| Recommend the next repository action | `$project-next` | Read-only triage; never starts issue work |

`$project-init` creates only a local Python scaffold. It does not publish to
GitHub, install Codex Power Pack, adopt Spec Kit, create issues, or add persistent
guidance. Those are separate, consented handoffs:

- GitHub publication: use a repository-aware GitHub workflow after reviewing
  owner, name, visibility, remote, and first push.
- Spec Kit adoption: use `$spec-adopt`.
- Approved spec-to-issue synchronization: use `$spec-sync`.
- Persistent Codex Power Pack guidance or hooks: use `$cxpp-init`.

Do not select `$project-init` for existing-repository orientation, next-work
analysis, publication, Spec Kit operations, ordinary repository changes, or any
request that does not explicitly ask for a new local Python project.
"""

SKILL_DIR_TOKEN = "<SKILL_DIR>"
_GENERIC_WORKTREE_ADAPTATION = (
    "- Native worktrees (`EnterWorktree`/`ExitWorktree` tool calls,"
    " `.claude/worktrees/` paths): use plain git instead -"
    " `git worktree add <path> -b <branch>`, work inside it, then"
    " `git worktree remove <path>` when done."
)
_CXPP_WORKTREE_ADAPTATION = (
    "- Codex worktrees: use the bundled resolver and plain git. Worktrees live"
    " at `$FLOW_WORKTREE_BASE/<repo>-<branch>` when configured, otherwise as a"
    " visible sibling `../<repo>-<branch>`; enter with `cd` and clean up with"
    " `git worktree remove`. Never use Claude's hidden worktree directory."
)
_SKILL_HELPER_PREAMBLE = f"""## Codex installed-skill runtime contract

`{SKILL_DIR_TOKEN}` below means the absolute directory containing this loaded
skill's `SKILL.md`. Resolve it from the skill locator before running a command;
never interpret bundled helper paths relative to the target repository. The
bundled resolver always selects the plain-git lane and creates visible sibling
worktrees (or uses `FLOW_WORKTREE_BASE` when configured).

"""
_CLAUDE_CICD_DISCOVERY = (
    "for dir in ~/Projects/claude-power-pack /opt/claude-power-pack ~/.claude-power-pack; do"
)
_CODEX_CICD_DISCOVERY = f"""# Prefer the CxPP-owned runner. The first two candidates cover a
# repo-local .codex skill and a checkout-local plugin respectively; installed
# marketplace skills then fall through to the standard CxPP checkout locations.
# claude-power-pack is an explicit compatibility fallback only (CxPP #142).
for dir in \\
  "{SKILL_DIR_TOKEN}/../../.." \\
  "{SKILL_DIR_TOKEN}/../../../.." \\
  "$HOME/Projects/codex-power-pack" \\
  /opt/codex-power-pack \\
  "$HOME/.codex-power-pack" \\
  "$HOME/Projects/claude-power-pack" \\
  /opt/claude-power-pack \\
  "$HOME/.claude-power-pack"; do"""
_GITHUB_REPO_PREAMBLE = """## Codex target-repository contract

Resolve `REPO` from an explicit `owner/repo` argument when supplied; otherwise
run `gh repo view --json nameWithOwner --jq .nameWithOwner` in the current
checkout. Pass `--repo "$REPO"` to every issue command. If neither source can
resolve a repository, ask the user before performing a write.

"""
_CLAUDE_REVIEW_ESCALATION = """If implementation hits a blocker:
- Make up to two materially distinct, evidence-driven attempts to resolve it
  locally. Repeating the same failing command or edit does not count as a new
  attempt.
- If the blocker persists, invoke `$claude-code-review` (the Codex-native
  `claude:code_review` capability) once for that blocker fingerprint. Give it
  the issue criteria, failed approaches, safe error summary, and current
  worktree. Claude is read-only support; Codex remains responsible for every
  edit and decision.
- Verify Claude's findings against the code, apply only supported fixes, and
  rerun the focused test. If the skill or SDK is unavailable, continue directly
  to the normal STOP path.
- If the blocker remains unresolved after the review, **STOP** and report it.
- Suggest manual intervention."""
_CODEX_DOCTOR_HELPERS = f"""# Installed Codex flow helper family (issue #139).
# Resolve SKILL_DIR from this loaded flow-doctor skill before running.
FLOW_SKILLS_ROOT="{SKILL_DIR_TOKEN}/.."
for script in flow-start-resolve.sh flow-stale-check.sh flow-worktree-guard.sh \
  flow-live-driver-guard.sh gh-pr-merge.sh; do
  helper=$(find "$FLOW_SKILLS_ROOT" -path "*/scripts/$script" -type f -perm -u+x -print -quit)
  if [ -n "$helper" ]; then
    echo "PASS $script (bundled Codex flow helper)"
  else
    echo "FAIL $script (missing from installed flow plugin; reinstall or upgrade flow@codex-power-pack)"
  fi
done"""


class IntegrityError(ValueError):
    """A provenance, source, manifest, or payload integrity violation."""


class Pin(NamedTuple):
    repo: str
    commit: str
    source: str
    destination: str


class PreparedPayload(NamedTuple):
    content: bytes
    mode: int


class PreparedPlugin(NamedTuple):
    destination: Path
    metadata: PreparedPayload | None


def _safe_relative_path(value: str, *, label: str, trailing_slash: bool = False) -> str:
    """Validate a repository-relative POSIX path without normalizing attacker input."""
    if not value or "\x00" in value or "\\" in value or value.startswith("/"):
        raise IntegrityError(f"{label}: expected a safe relative POSIX path")
    if trailing_slash != value.endswith("/"):
        suffix = " with a trailing slash" if trailing_slash else " without a trailing slash"
        raise IntegrityError(f"{label}: expected a file path{suffix}")
    trimmed = value[:-1] if trailing_slash else value
    parts = trimmed.split("/")
    if not trimmed or any(part in {"", ".", ".."} for part in parts):
        raise IntegrityError(f"{label}: path is empty, non-normalized, or escapes its root")
    if re.match(r"^[A-Za-z]:", parts[0]):
        raise IntegrityError(f"{label}: drive-qualified paths are not allowed")
    return value


def _github_repo_identity(value: str) -> tuple[str, str]:
    """Return a normalized GitHub owner/repository for documented safe URL forms."""
    patterns = (
        r"https://github\.com/([^/]+)/([^/]+?)(?:\.git)?/?",
        r"git@github\.com:([^/]+)/([^/]+?)(?:\.git)?",
        r"ssh://git@github\.com/([^/]+)/([^/]+?)(?:\.git)?/?",
    )
    for pattern in patterns:
        match = re.fullmatch(pattern, value, flags=re.IGNORECASE)
        if match:
            return match.group(1).lower(), match.group(2).lower()
    raise IntegrityError("repository URL is not a documented credential-free GitHub spelling")


def read_pin(path: Path | None = None) -> Pin:
    """Parse the provenance file strictly; duplicate or unknown fields are invalid."""
    pin_path = path or PIN_PATH
    if not pin_path.is_file():
        raise IntegrityError(f"PIN is missing at {pin_path}")

    fields: dict[str, str] = {}
    for line_number, raw in enumerate(pin_path.read_text(encoding="utf-8").splitlines(), 1):
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        key, separator, value = line.partition(":")
        key = key.strip()
        value = value.strip()
        if not separator or not key or not value:
            raise IntegrityError(f"PIN line {line_number}: expected 'field: value'")
        if key not in PIN_FIELDS:
            raise IntegrityError(f"PIN line {line_number}: unknown field '{key}'")
        if key in fields:
            raise IntegrityError(f"PIN line {line_number}: duplicate field '{key}'")
        fields[key] = value

    missing = sorted(PIN_FIELDS - fields.keys())
    if missing:
        raise IntegrityError(f"PIN missing field(s): {', '.join(missing)}")
    if not COMMIT_RE.fullmatch(fields["commit"]):
        raise IntegrityError("PIN commit must be exactly 40 lowercase hexadecimal characters")
    if _github_repo_identity(fields["repo"]) != _github_repo_identity(CPP_REPO_URL):
        raise IntegrityError("PIN repository does not identify cooneycw/claude-power-pack")

    pulls = re.fullmatch(r"(\S+)\s+->\s+(\S+)", fields["pulls"])
    if pulls is None:
        raise IntegrityError("PIN pulls must be '<source>/  ->  <destination>/'")
    source = _safe_relative_path(pulls.group(1), label="PIN pulls source", trailing_slash=True)
    destination = _safe_relative_path(
        pulls.group(2), label="PIN pulls destination", trailing_slash=True
    )
    if source != PIN_PULL_SOURCE or destination != PIN_PULL_DESTINATION:
        raise IntegrityError(
            f"PIN pulls must map {PIN_PULL_SOURCE} to {PIN_PULL_DESTINATION}"
        )
    return Pin(fields["repo"], fields["commit"], source, destination)


def _git_output(cpp_root: Path, *args: str) -> str:
    completed = subprocess.run(
        ["git", "-C", str(cpp_root), *args],
        check=False,
        stdout=subprocess.PIPE,
        stderr=subprocess.DEVNULL,
        text=True,
    )
    if completed.returncode != 0:
        raise IntegrityError(f"source checkout failed git {args[0]} validation")
    return completed.stdout.strip()


def _git_bytes(cpp_root: Path, *args: str) -> bytes:
    completed = subprocess.run(
        ["git", "-C", str(cpp_root), *args],
        check=False,
        stdout=subprocess.PIPE,
        stderr=subprocess.DEVNULL,
    )
    if completed.returncode != 0:
        raise IntegrityError(f"source checkout failed git {args[0]} validation")
    return completed.stdout


def _assert_no_symlinks(root: Path, *, label: str) -> None:
    if root.is_symlink():
        raise IntegrityError(f"{label}: root may not be a symlink")
    if not root.exists():
        return
    for path in root.rglob("*"):
        if path.is_symlink():
            rel = path.relative_to(root).as_posix()
            raise IntegrityError(f"{label}: symlink path is unsafe: {rel}")


def _validate_source_checkout(cpp_root: Path, *, commit: str, repo: str) -> tuple[str, str]:
    """Validate source identity and cleanliness without trusting a branch label."""
    if cpp_root.is_symlink() or not cpp_root.is_dir():
        raise IntegrityError("source checkout must be an existing non-symlink directory")
    if not COMMIT_RE.fullmatch(commit):
        raise IntegrityError("source ref must be exactly 40 lowercase hexadecimal characters")

    resolved_root = cpp_root.resolve()
    top_level = Path(_git_output(cpp_root, "rev-parse", "--show-toplevel")).resolve()
    if top_level != resolved_root:
        raise IntegrityError("source path must name the Git worktree root")
    origin = _git_output(cpp_root, "remote", "get-url", "origin")
    if _github_repo_identity(origin) != _github_repo_identity(repo):
        raise IntegrityError("source origin does not match the PIN repository")

    _git_output(cpp_root, "cat-file", "-e", f"{commit}^{{commit}}")
    head = _git_output(cpp_root, "rev-parse", "HEAD")
    if head != commit:
        raise IntegrityError(f"source HEAD {head} does not match declared ref {commit}")
    dirty = _git_output(cpp_root, "status", "--porcelain", "--untracked-files=all")
    if dirty:
        raise IntegrityError("source checkout is dirty")

    source_root = cpp_root / PIN_PULL_SOURCE
    if not source_root.is_dir():
        raise IntegrityError(f"source checkout has no {PIN_PULL_SOURCE}")
    _assert_no_symlinks(source_root, label="source payload")
    tree = _git_output(cpp_root, "rev-parse", "HEAD^{tree}")
    return head, tree


def _assert_repo_ancestors_safe(path: Path, *, label: str) -> None:
    """Reject lexical or symlink redirection at any component below REPO_ROOT."""
    lexical_repo = REPO_ROOT.absolute()
    lexical_path = path.absolute()
    try:
        relative = lexical_path.relative_to(lexical_repo)
    except ValueError as exc:
        raise IntegrityError(f"{label}: destination escapes repository root") from exc

    current = lexical_repo
    for index, part in enumerate(relative.parts):
        current /= part
        if current.is_symlink():
            raise IntegrityError(f"{label}: symlink component is unsafe: {current}")
        if index < len(relative.parts) - 1 and current.exists() and not current.is_dir():
            raise IntegrityError(f"{label}: parent component is not a directory: {current}")

    resolved_repo = REPO_ROOT.resolve()
    if not path.resolve(strict=False).is_relative_to(resolved_repo):
        raise IntegrityError(f"{label}: destination escapes repository root")


def _assert_destination_tree_safe(root: Path, *, label: str) -> None:
    """Reject roots, ancestors, or existing descendants that redirect writes."""
    _assert_repo_ancestors_safe(root, label=label)
    if root.exists() and not root.is_dir():
        raise IntegrityError(f"{label}: destination root is not a directory")
    _assert_no_symlinks(root, label=label)


def _assert_publication_file_safe(path: Path, *, label: str) -> None:
    """Require a regular-or-absent in-repo file with ordinary directory parents."""
    _assert_repo_ancestors_safe(path, label=label)
    if path.exists() and not path.is_file():
        raise IntegrityError(f"{label}: existing destination is not a regular file")


def _is_local_path(path: Path) -> bool:
    rel = path.relative_to(SKILLS_ROOT)
    first = rel.parts[0]
    return first in LOCAL_FILES or first in LOCAL_SKILL_DIRS


def _is_python_cache(path: Path) -> bool:
    return "__pycache__" in path.parts or path.suffix in {".pyc", ".pyo"}


def _generated_files() -> list[Path]:
    """Every pulled file under .codex/skills/ - i.e. files inside a skill subdir.

    Top-level files and CxPP-owned native skill dirs are excluded: they are owned
    here, not vendored, so they are not part of the drift surface.
    """
    if not SKILLS_ROOT.is_dir():
        return []
    return sorted(
        p
        for p in SKILLS_ROOT.rglob("*")
        if p.is_file()
        and not _is_python_cache(p)
        and not _is_local_path(p)
        and len(p.relative_to(SKILLS_ROOT).parts) > 1
    )


def _rel(path: Path) -> str:
    return path.relative_to(SKILLS_ROOT).as_posix()


def _sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def compute_manifest() -> dict[str, str]:
    """Map `<relpath>` -> sha256 for every generated file under .codex/skills/."""
    return {_rel(p): _sha256(p) for p in _generated_files()}


def format_manifest(manifest: dict[str, str]) -> str:
    lines = [f"{digest}  {rel}" for rel, digest in sorted(manifest.items())]
    return "\n".join(lines) + ("\n" if lines else "")


def read_manifest(path: Path | None = None) -> dict[str, str]:
    manifest_path = path or MANIFEST_PATH
    if not manifest_path.is_file():
        return {}
    manifest: dict[str, str] = {}
    for line_number, raw in enumerate(
        manifest_path.read_text(encoding="utf-8").splitlines(), 1
    ):
        if not raw.strip():
            continue
        match = re.fullmatch(r"([0-9a-f]{64})  (\S+)", raw)
        if match is None:
            raise IntegrityError(
                f"manifest line {line_number}: expected '<64 lowercase hex>  <relative path>'"
            )
        digest, rel = match.groups()
        if not DIGEST_RE.fullmatch(digest):
            raise IntegrityError(f"manifest line {line_number}: malformed digest")
        _safe_relative_path(rel, label=f"manifest line {line_number}")
        if rel in manifest:
            raise IntegrityError(f"manifest line {line_number}: duplicate path '{rel}'")
        manifest[rel] = digest
    return manifest


def _skill_dirs() -> list[Path]:
    if not SKILLS_ROOT.is_dir():
        return []
    return sorted(d for d in SKILLS_ROOT.iterdir() if d.is_dir())


def _generated_skill_dirs() -> list[Path]:
    return sorted(d for d in _skill_dirs() if d.name not in LOCAL_SKILL_DIRS)


def _marker_violations() -> list[str]:
    """Skill dirs whose SKILL.md is missing or does not carry the GENERATED marker."""
    violations: list[str] = []
    for skill_dir in _generated_skill_dirs():
        skill_md = skill_dir / "SKILL.md"
        if not skill_md.is_file():
            violations.append(f"{skill_dir.name}: no SKILL.md")
        elif MARKER_PREFIX not in skill_md.read_text():
            violations.append(f"{skill_dir.name}: SKILL.md missing GENERATED marker")
    return violations


def run_check() -> int:
    try:
        read_pin()
        expected = read_manifest()
        _assert_destination_tree_safe(SKILLS_ROOT, label="generated skills")
    except IntegrityError as exc:
        print(f"codex-skills-sync: invalid provenance: {exc}", file=sys.stderr)
        return 1
    if not expected:
        print(
            "codex-skills-sync: no manifest at"
            f" {MANIFEST_PATH.relative_to(REPO_ROOT)}; run --refresh to pull from CPP.",
            file=sys.stderr,
        )
        return 1

    actual = compute_manifest()
    drift = 0

    for rel in sorted(set(expected) - set(actual)):
        print(f"MISSING: .codex/skills/{rel} (in manifest, not on disk)")
        drift = 1
    for rel in sorted(set(actual) - set(expected)):
        print(f"EXTRA: .codex/skills/{rel} (on disk, not in manifest)")
        drift = 1
    for rel in sorted(set(expected) & set(actual)):
        if expected[rel] != actual[rel]:
            print(f"DRIFT: .codex/skills/{rel} differs from the vendored (pinned) copy")
            drift = 1

    for violation in _marker_violations():
        print(f"MARKER: .codex/skills/{violation}")
        drift = 1

    if drift:
        print(
            "\ncodex-skills-sync: DRIFT detected. These are generated from"
            " claude-power-pack; do not hand-edit. To reconcile, edit the SOURCE in"
            " claude-power-pack .claude/commands/<family>/, regenerate there"
            " (make codex-skills), then re-run: scripts/codex_skills_sync.py --refresh"
            " --cpp-root <path>",
            file=sys.stderr,
        )
        return 1

    print(f"codex-skills-sync: {len(actual)} file(s) across {len(_generated_skill_dirs())} generated skill(s) in sync")
    return 0


def run_write() -> int:
    try:
        read_pin()
        _assert_destination_tree_safe(SKILLS_ROOT, label="generated skills")
    except IntegrityError as exc:
        print(f"codex-skills-sync: snapshot refused: {exc}", file=sys.stderr)
        return 1
    VENDOR_DIR.mkdir(parents=True, exist_ok=True)
    manifest = compute_manifest()
    MANIFEST_PATH.write_text(format_manifest(manifest))
    print(
        f"codex-skills-sync: snapshot {len(manifest)} file(s) ->"
        f" {MANIFEST_PATH.relative_to(REPO_ROOT)}"
    )
    return 0


def _write_pin(ref: str) -> None:
    VENDOR_DIR.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Pinned claude-power-pack source for the generated Codex skills (pull model).",
        "# Managed by scripts/codex_skills_sync.py --refresh; do not hand-edit.",
        f"repo: {CPP_REPO_URL}",
        f"commit: {ref}",
        f"pulls: {PIN_PULL_SOURCE}  ->  {PIN_PULL_DESTINATION}",
        "",
    ]
    PIN_PATH.write_text("\n".join(lines))


def _source_skill_dirs(cpp_root: Path) -> list[Path]:
    src_root = cpp_root / "codex" / "skills"
    if not src_root.is_dir():
        return []
    excluded_prefixes = tuple(f"{fam}-" for fam in PULL_EXCLUDE_FAMILIES)
    return sorted(
        d
        for d in src_root.iterdir()
        if d.is_dir()
        and (d / "SKILL.md").is_file()
        and not d.name.startswith(excluded_prefixes)
        # A newly generated upstream command must never overwrite a native
        # CxPP skill with the same name (#135/#139).
        and d.name not in LOCAL_SKILL_DIRS
    )


def _git_source_payloads(
    cpp_root: Path, commit: str
) -> dict[str, dict[str, PreparedPayload]]:
    """Load every adopted input from immutable Git blobs and verify the checkout.

    `git status` can hide modified paths through index flags and ignored files.  The
    exact-pin lane therefore derives its input inventory and bytes from the pinned
    tree, then independently proves that the filesystem view has no consumed-file
    additions, removals, byte changes, or executable-bit changes.
    """
    raw_tree = _git_bytes(
        cpp_root,
        "ls-tree",
        "-r",
        "-z",
        "--full-tree",
        commit,
        "--",
        PIN_PULL_SOURCE.rstrip("/"),
    )
    tree_entries: dict[str, tuple[str, str]] = {}
    prefix = PIN_PULL_SOURCE
    for raw_entry in raw_tree.split(b"\0"):
        if not raw_entry:
            continue
        metadata, separator, raw_path = raw_entry.partition(b"\t")
        if not separator:
            raise IntegrityError("pinned source tree contains a malformed entry")
        try:
            mode, object_type, object_id = metadata.decode("ascii").split()
            path = raw_path.decode("utf-8")
        except (UnicodeDecodeError, ValueError) as exc:
            raise IntegrityError("pinned source tree contains an unsupported entry") from exc
        if not path.startswith(prefix):
            raise IntegrityError(f"pinned source path escapes {prefix}: {path}")
        rel = _safe_relative_path(path[len(prefix) :], label="pinned source path")
        if object_type != "blob" or mode not in {"100644", "100755"}:
            raise IntegrityError(f"pinned source path has unsafe Git mode/type: {path}")
        if rel in tree_entries:
            raise IntegrityError(f"pinned source tree has duplicate path: {rel}")
        tree_entries[rel] = (mode, object_id)

    excluded_prefixes = tuple(f"{family}-" for family in PULL_EXCLUDE_FAMILIES)
    skill_names = {
        rel.partition("/")[0]
        for rel in tree_entries
        if "/" in rel and rel.endswith("/SKILL.md")
    }
    skill_names = {
        name
        for name in skill_names
        if not name.startswith(excluded_prefixes) and name not in LOCAL_SKILL_DIRS
    }
    if not skill_names:
        raise IntegrityError("pinned source tree has no adopted generated skills")

    immutable: dict[str, dict[str, PreparedPayload]] = {
        name: {} for name in sorted(skill_names)
    }
    for rel, (mode, object_id) in sorted(tree_entries.items()):
        skill_name, separator, skill_rel = rel.partition("/")
        if not separator or skill_name not in immutable:
            continue
        rel_path = Path(skill_rel)
        if _is_python_cache(rel_path):
            continue
        if skill_name == "evaluate-help" and skill_rel == "scripts/speckit-tasks-to-issues.sh":
            continue
        content = _git_bytes(cpp_root, "cat-file", "blob", object_id)
        immutable[skill_name][skill_rel] = PreparedPayload(
            content, 0o755 if mode == "100755" else 0o644
        )

    actual_skill_dirs = {path.name: path for path in _source_skill_dirs(cpp_root)}
    if set(actual_skill_dirs) != set(immutable):
        missing = sorted(set(immutable) - set(actual_skill_dirs))
        extra = sorted(set(actual_skill_dirs) - set(immutable))
        raise IntegrityError(
            f"source skill inventory differs from pinned tree: missing={missing}, extra={extra}"
        )

    for skill_name, expected in immutable.items():
        skill_dir = actual_skill_dirs[skill_name]
        actual_paths = {
            path.relative_to(skill_dir).as_posix(): path
            for path in skill_dir.rglob("*")
            if path.is_file()
            and not _is_python_cache(path)
            and not (
                skill_name == "evaluate-help"
                and path.relative_to(skill_dir).as_posix()
                == "scripts/speckit-tasks-to-issues.sh"
            )
        }
        if set(actual_paths) != set(expected):
            missing = sorted(set(expected) - set(actual_paths))
            extra = sorted(set(actual_paths) - set(expected))
            raise IntegrityError(
                f"source skill {skill_name} differs from pinned file inventory: "
                f"missing={missing}, extra={extra}"
            )
        for rel, pinned in expected.items():
            path = actual_paths[rel]
            if path.read_bytes() != pinned.content:
                raise IntegrityError(
                    f"source skill {skill_name}/{rel} differs from pinned Git blob"
                )
            executable = bool(path.stat().st_mode & 0o111)
            if executable != bool(pinned.mode & 0o111):
                raise IntegrityError(
                    f"source skill {skill_name}/{rel} executable bit differs from pinned tree"
                )
    return immutable


def _adapt_flow_text(skill_dir: Path, source_file: Path, text: str) -> str:
    """Apply the narrow CxPP-owned Codex runtime overlay to flow payloads."""
    if not skill_dir.name.startswith("flow-"):
        return text

    text = text.replace(_GENERIC_WORKTREE_ADAPTATION, _CXPP_WORKTREE_ADAPTATION)
    text = text.replace(".claude/friction.jsonl", ".codex/friction.jsonl")

    for helper in sorted(FLOW_RUNTIME_HELPERS):
        helper_owner = next(
            (
                candidate
                for candidate in (
                    skill_dir,
                    skill_dir.parent / "flow-start",
                    skill_dir.parent / "flow-auto",
                    skill_dir.parent / "flow-merge",
                )
                if (candidate / "scripts" / helper).is_file()
            ),
            None,
        )
        if helper_owner is None:
            continue
        if helper_owner == skill_dir:
            resolved = f"{SKILL_DIR_TOKEN}/scripts/{helper}"
        else:
            resolved = f"{SKILL_DIR_TOKEN}/../{helper_owner.name}/scripts/{helper}"
        text = text.replace(f"~/.claude/scripts/{helper}", resolved)
        text = re.sub(
            rf"(?<![/A-Za-z0-9_.-])scripts/{re.escape(helper)}",
            resolved,
            text,
        )

    # New upstream prose can refer to the stable Claude helper directory
    # without naming an individual helper (#590). Codex packages helpers with
    # the loaded skill, so the generic directory must follow the same overlay.
    text = text.replace("~/.claude/scripts/", f"{SKILL_DIR_TOKEN}/scripts/")

    # Generated references describe Claude's native hidden worktrees.  The
    # SKILL.md adaptation and resolver below are authoritative for Codex, but
    # remove the stale path spellings as well so examples cannot be followed
    # literally and the harness lint remains meaningful.
    text = text.replace(".claude/worktrees", "../<repo>-<branch>")
    text = text.replace(
        "Helpers are invoked bare at their stable `~/.claude/scripts/` paths",
        "Helpers are invoked by absolute path from the installed Codex skill package",
    )

    if skill_dir.name == "flow-doctor" and source_file.name == "reference.md":
        text = re.sub(
            r"# Flow helper family \(issue #581\):.*?^done$",
            _CODEX_DOCTOR_HELPERS,
            text,
            count=1,
            flags=re.MULTILINE | re.DOTALL,
        )
        text = text.replace(
            "| Flow helper family | ✅/⚠️ | flow-start-resolve, flow-stale-check,"
            " flow-worktree-guard, flow-live-driver-guard, gh-pr-merge at"
            " ~/.claude/scripts/ (zero-prompt lane, #581) |",
            "| Flow helper family | ✅/❌ | Bundled executable helpers in the installed"
            " flow skill packages (#139) |",
        )
        text = text.replace(
            "2c. ⚠️ **Flow helper(s) not at ~/.claude/scripts/** - the #581 zero-prompt"
            " lane degrades to CPP-checkout fallback paths, which prompt. Run"
            " `/cpp:update` (Step 5b re-links new scripts) or `/cpp:init` Tier 2",
            "2c. ❌ **Bundled Codex flow helper(s) missing** - reinstall or upgrade"
            " `flow@codex-power-pack`; a CPP clone is not required.",
        )

    if source_file.name == "reference.md" and SKILL_DIR_TOKEN in text:
        marker_end = text.find("\n\n")
        if marker_end != -1 and _SKILL_HELPER_PREAMBLE not in text:
            text = text[: marker_end + 2] + _SKILL_HELPER_PREAMBLE + text[marker_end + 2 :]
    return text


def _adapt_flow_cicd_runtime(skill_dir: Path, source_file: Path, text: str) -> str:
    """Prefer CxPP's runner in Codex finish lanes, retaining CPP as fallback."""
    if source_file.name != "reference.md" or skill_dir.name not in {
        "flow-auto",
        "flow-finish",
        "flow-merge",
    }:
        return text

    discovery = re.compile(
        rf'^(?P<indent>[ \t]*)CPP_DIR=""\n(?P=indent)'
        rf'{re.escape(_CLAUDE_CICD_DISCOVERY)}\n(?P<body>.*?)\n(?P=indent)done',
        re.DOTALL | re.MULTILINE,
    )

    def adapt_match(match: re.Match[str]) -> str:
        # A flow reference can also locate CPP solely for legacy helper scripts.
        # Adapt only blocks whose nearby command actually invokes lib.cicd.
        if "python -m lib.cicd" not in text[match.end() : match.end() + 1600]:
            return match.group(0)
        indent = match.group("indent")
        body = match.group("body").replace(
            'if [ -d "$dir" ] && [ -f "$dir/CLAUDE.md" ]; then',
            'if [ -d "$dir/lib/cicd" ] && '
            '{ [ -f "$dir/AGENTS.md" ] || [ -f "$dir/CLAUDE.md" ]; }; then',
        )
        body = body.replace(
            '[ -d "$dir" ] && [ -f "$dir/CLAUDE.md" ] && { CPP_DIR="$dir"; break; }',
            '[ -d "$dir/lib/cicd" ] && '
            '{ [ -f "$dir/AGENTS.md" ] || [ -f "$dir/CLAUDE.md" ]; } && '
            '{ CPP_DIR="$dir"; break; }',
        )
        discovery_text = "\n".join(f"{indent}{line}" for line in _CODEX_CICD_DISCOVERY.splitlines())
        return (
            f'{indent}CPP_DIR=""\n{indent}CICD_RUNTIME_KIND=""\n{discovery_text}\n'
            f'{body}\n{indent}done\n'
            f'{indent}if [ -n "$CPP_DIR" ]; then\n'
            f'{indent}  if [ -f "$CPP_DIR/AGENTS.md" ]; then\n'
            f'{indent}    CICD_RUNTIME_KIND="cxpp"\n'
            f'{indent}  else\n'
            f'{indent}    CICD_RUNTIME_KIND="cpp-compat"\n'
            f'{indent}  fi\n'
            f'{indent}fi'
        )

    text = discovery.sub(adapt_match, text)
    runner_command = re.compile(
        r'^(?P<indent>[ \t]*)PYTHONPATH="\$CPP_DIR:\$PYTHONPATH" '
        r'uv run --project "\$CPP_DIR" python -m lib\.cicd '
        r'(?P<args>run --plan finish|check --summary)$',
        re.MULTILINE,
    )

    def adapt_runner_command(match: re.Match[str]) -> str:
        indent = match.group("indent")
        args = match.group("args")
        return (
            f'{indent}if [ "$CICD_RUNTIME_KIND" = "cxpp" ]; then\n'
            f'{indent}    PYTHONPATH="$CPP_DIR:$PYTHONPATH" '
            f'uv run python -m lib.cicd {args}\n'
            f"{indent}else\n"
            f'{indent}    PYTHONPATH="$CPP_DIR:$PYTHONPATH" '
            f'uv run --project "$CPP_DIR" python -m lib.cicd {args}\n'
            f"{indent}fi"
        )

    text = runner_command.sub(adapt_runner_command, text)
    text = text.replace("CPP checkout not found", "CxPP/CPP runtime not found")
    return text


def _adapt_flow_cicd_helper(skill_dir: Path, source_file: Path, text: str) -> str:
    """Make the bundled finish gate prefer CxPP and provision its dev runtime."""
    if source_file.name != "flow-finish-gate.sh" or not skill_dir.name.startswith("flow-"):
        return text

    upstream_discovery = """# --- Locate the CPP checkout (same search the command docs use) -------------
if [[ -n "${FLOW_GATE_CPP_DIR+x}" ]]; then
    CPP_DIR="$FLOW_GATE_CPP_DIR"
else
    CPP_DIR=""
    for dir in "$HOME/Projects/claude-power-pack" /opt/claude-power-pack "$HOME/.claude-power-pack"; do
        if [[ -d "$dir" && -f "$dir/CLAUDE.md" ]]; then
            CPP_DIR="$dir"
            break
        fi
    done
fi
"""
    codex_discovery = """# --- Locate the CxPP runner, retaining CPP as compatibility fallback --------
SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
# Bare helper invocation cannot prefix uv with an environment assignment. Keep
# caller configuration when present; otherwise use a cache location that is
# writable in restricted agent sandboxes as well as normal shells.
export UV_CACHE_DIR="${UV_CACHE_DIR:-${TMPDIR:-/tmp}/codex-power-pack-uv-cache}"
if [[ -n "${FLOW_GATE_CPP_DIR+x}" ]]; then
    CPP_DIR="$FLOW_GATE_CPP_DIR"
else
    CPP_DIR=""
    for dir in \\
        "$SCRIPT_DIR/../../../.." \\
        "$SCRIPT_DIR/../../../../.." \\
        "$HOME/Projects/codex-power-pack" \\
        /opt/codex-power-pack \\
        "$HOME/.codex-power-pack" \\
        "$HOME/Projects/claude-power-pack" \\
        /opt/claude-power-pack \\
        "$HOME/.claude-power-pack"; do
        if [[ -d "$dir/lib/cicd" && ( -f "$dir/AGENTS.md" || -f "$dir/CLAUDE.md" ) ]]; then
            CPP_DIR="$dir"
            break
        fi
    done
fi

CICD_RUNTIME_KIND=""
if [[ -n "$CPP_DIR" ]]; then
    if [[ -f "$CPP_DIR/AGENTS.md" ]]; then
        CICD_RUNTIME_KIND="cxpp"
    else
        CICD_RUNTIME_KIND="cpp-compat"
    fi
fi
"""
    if upstream_discovery not in text:
        return text
    text = text.replace(upstream_discovery, codex_discovery, 1)
    text = text.replace("CPP checkout not found", "CxPP/CPP runtime not found")

    upstream_command = (
        'PYTHONPATH="$CPP_DIR:${PYTHONPATH:-}" uv run --project "$CPP_DIR" '
        "python -m lib.cicd"
    )
    codex_check_command = """    if [[ "$CICD_RUNTIME_KIND" == "cxpp" ]]; then
        PYTHONPATH="$CPP_DIR:${PYTHONPATH:-}" uv run --project "$CPP_DIR" --extra dev python -m lib.cicd check --summary
    else
        PYTHONPATH="$CPP_DIR:${PYTHONPATH:-}" uv run --project "$CPP_DIR" python -m lib.cicd check --summary
    fi"""
    codex_runner_command = (
        '    if [[ "$CICD_RUNTIME_KIND" == "cxpp" ]]; then\n'
        '        PYTHONPATH="$CPP_DIR:${PYTHONPATH:-}" uv run --project "$CPP_DIR" '
        '--extra dev python -m lib.cicd run --plan "$PLAN"\n'
        "    else\n"
        '        PYTHONPATH="$CPP_DIR:${PYTHONPATH:-}" uv run --project "$CPP_DIR" '
        'python -m lib.cicd run --plan "$PLAN"\n'
        "    fi"
    )
    text = text.replace(
        f"    {upstream_command} check --summary",
        codex_check_command,
        1,
    )
    text = text.replace(
        f'    {upstream_command} run --plan "$PLAN"',
        codex_runner_command,
        1,
    )
    return text


def _adapt_flow_claude_review(skill_dir: Path, source_file: Path, text: str) -> str:
    """Add CxPP's bounded cross-model escalation to Codex flow:auto."""
    if skill_dir.name != "flow-auto" or source_file.name != "reference.md":
        return text
    original = """If implementation hits a blocker that cannot be resolved:
- **STOP** and report the blocker.
- Suggest manual intervention."""
    if original in text:
        return text.replace(original, _CLAUDE_REVIEW_ESCALATION, 1)
    return text


def _adapt_flow_resolver(text: str) -> str:
    """Make CPP's resolver use Codex's plain-git visible-worktree lane."""
    text = text.replace(
        "GIT_LANE=$CROSS_REPO\n[ -n \"${FLOW_WORKTREE_BASE:-}\" ] && GIT_LANE=1",
        "# Codex has no EnterWorktree tool: every lane uses plain git.\nGIT_LANE=1",
    )
    text = text.replace(
        'echo "$TARGET_REPO/.claude/worktrees/$1"',
        'echo "$(dirname "$TARGET_REPO")/$(basename "$TARGET_REPO")-$1"',
    )
    text = text.replace(
        "<target repo>/.claude/worktrees/<branch>",
        "<target repo parent>/<repo>-<branch>",
    )
    text = text.replace(".claude/worktrees", "visible sibling worktrees")
    return text


def _adapt_github_text(skill_dir: Path, source_file: Path, text: str) -> str:
    """Keep shared GitHub skills repository-neutral on the CxPP surface."""
    if not skill_dir.name.startswith("github-"):
        return text
    text = text.replace("cooneycw/claude-power-pack", '"$REPO"')
    if source_file.name == "SKILL.md" and _GITHUB_REPO_PREAMBLE not in text:
        marker_end = text.find("\n\n")
        if marker_end != -1:
            text = text[: marker_end + 2] + _GITHUB_REPO_PREAMBLE + text[marker_end + 2 :]
    return text


def _adapt_codex_runtime_text(skill_dir: Path, source_file: Path, text: str) -> str:
    """Remove operational Claude state/runtime paths from the Codex payload."""
    if source_file.suffix not in {".md", ".sh"}:
        return text

    text = text.replace(".claude/cicd_tasks.yml", ".codex/cicd_tasks.yml")
    text = text.replace(".claude/cicd.yml", ".codex/cicd.yml")
    text = text.replace(".claude/deploy.log", ".codex/deploy.log")
    text = text.replace(".claude/secrets.yml", ".codex/secrets.yml")

    if skill_dir.name.startswith("cicd-"):
        text = text.replace(
            '$PWD/lib:$HOME/Projects/claude-power-pack/lib:$PYTHONPATH',
            '$PWD:$HOME/Projects/codex-power-pack:$PYTHONPATH',
        )
        text = text.replace(
            '$CPP_DIR/lib:$PYTHONPATH',
            '$HOME/Projects/codex-power-pack:$PYTHONPATH',
        )

    if skill_dir.name == "secrets-help":
        text = text.replace(
            '$HOME/Projects/claude-power-pack/lib:$PYTHONPATH',
            '$HOME/Projects/codex-power-pack:$PYTHONPATH',
        )

    if skill_dir.name == "self-improvement-deployment" and source_file.name == "reference.md":
        text = text.replace(
            "cp ~/Projects/claude-power-pack/templates/Makefile.example Makefile",
            "cp ~/Projects/codex-power-pack/templates/Makefile.example Makefile",
        )
        text = text.replace(
            "Reference template: `~/Projects/claude-power-pack/templates/Makefile.example`",
            "Reference template: `~/Projects/codex-power-pack/templates/Makefile.example`",
        )
        text = text.replace(
            'PYTHONPATH="${PYTHONPATH:+$PYTHONPATH:}$HOME/Projects/claude-power-pack/lib"',
            'PYTHONPATH="${PYTHONPATH:+$PYTHONPATH:}$HOME/Projects/codex-power-pack"',
        )
    return text


def _adapt_invocation_text(skill_dir: Path, source_file: Path, text: str) -> str:
    """Normalize generated user guidance to native Codex skill selection."""
    if source_file.suffix != ".md":
        return text

    text = text.replace("/claude-md-lint", "$agents-md-lint")
    text = text.replace("$claude-md-lint", "$agents-md-lint")
    text = text.replace("Audit CLAUDE.md", "Audit AGENTS.md")

    if skill_dir.name == "flow-auto" and source_file.name == "SKILL.md":
        text = re.sub(
            r'^description:.*$',
            f'description: "{FLOW_AUTO_DESCRIPTION}"',
            text,
            count=1,
            flags=re.MULTILINE,
        )

    if skill_dir.name == "project-help" and source_file.name == "SKILL.md":
        text = re.sub(
            r'^description:.*$',
            'description: "Explain which project skill owns scaffolding, orientation, and next-work triage"',
            text,
            count=1,
            flags=re.MULTILINE,
        )
        heading = text.find("# Project Commands")
        if heading != -1:
            text = text[:heading] + _CODEX_PROJECT_HELP_BODY

    if skill_dir.name == "evaluate-help" and source_file.name == "SKILL.md":
        text = text.replace(
            "Use `./scripts/speckit-tasks-to-issues.sh` to create GitHub issues from the generated tasks.",
            "Hand approved Spec Kit artifacts to `$spec-sync`; evaluate does not own or bundle\n"
            "an issue compiler.",
        )
        text = text.replace(
            "- `scripts/speckit-tasks-to-issues.sh` - Turn a spec `tasks.md` into GitHub issues",
            "- `$spec-sync` - Separately preview and compile approved artifacts into GitHub issues",
        )

    skill_names = {
        path.name
        for path in skill_dir.parent.iterdir()
        if path.is_dir() and (path / "SKILL.md").is_file()
    } | LOCAL_SKILL_DIRS

    def replace_namespaced(match: re.Match[str]) -> str:
        candidate = f"{match.group(1)}-{match.group(2)}"
        selected = LEGACY_SKILL_REPLACEMENTS.get(candidate, candidate)
        return f"${selected}" if selected in skill_names else match.group(0)

    text = re.sub(
        r"(?<![A-Za-z0-9./])/(?!/)([a-z][a-z0-9_-]+):([a-z][a-z0-9_-]+)",
        replace_namespaced,
        text,
    )
    if skill_names:
        bare = re.compile(
            r"(?<![A-Za-z0-9./])/(?!/)("
            + "|".join(re.escape(name) for name in sorted(skill_names, key=len, reverse=True))
            + r")(?![A-Za-z0-9_-])"
        )
        text = bare.sub(lambda match: f"${match.group(1)}", text)
    return text


def _adapted_source_payloads(
    skill_dir: Path,
    immutable_payloads: dict[str, PreparedPayload] | None = None,
) -> dict[str, PreparedPayload]:
    _assert_no_symlinks(skill_dir, label=f"source skill {skill_dir.name}")
    files: dict[str, PreparedPayload] = {}
    if immutable_payloads is None:
        source_payloads = {
            path.relative_to(skill_dir).as_posix(): PreparedPayload(
                path.read_bytes(), path.stat().st_mode & 0o777
            )
            for path in skill_dir.rglob("*")
            if path.is_file() and not _is_python_cache(path)
        }
    else:
        source_payloads = immutable_payloads
    for rel, source_payload in sorted(source_payloads.items()):
        source_file = skill_dir / rel
        _safe_relative_path(rel, label=f"source skill {skill_dir.name}")
        if skill_dir.name == "evaluate-help" and rel == "scripts/speckit-tasks-to-issues.sh":
            continue
        try:
            text = source_payload.content.decode()
        except UnicodeDecodeError:
            files[rel] = source_payload
            continue
        if rel == "scripts/flow-start-resolve.sh":
            text = _adapt_flow_resolver(text)
        text = _adapt_flow_text(skill_dir, source_file, text)
        text = _adapt_flow_cicd_helper(skill_dir, source_file, text)
        text = _adapt_flow_cicd_runtime(skill_dir, source_file, text)
        text = _adapt_flow_claude_review(skill_dir, source_file, text)
        text = _adapt_github_text(skill_dir, source_file, text)
        text = _adapt_codex_runtime_text(skill_dir, source_file, text)
        text = _adapt_invocation_text(skill_dir, source_file, text)
        files[rel] = PreparedPayload(text.encode(), source_payload.mode)
    return files


def _adapted_source_files(skill_dir: Path) -> dict[str, bytes]:
    return {
        rel: payload.content
        for rel, payload in _adapted_source_payloads(skill_dir).items()
    }


def _write_skill_payload(dest: Path, payloads: dict[str, PreparedPayload]) -> None:
    if dest.exists():
        shutil.rmtree(dest)
    for rel, payload in payloads.items():
        target = dest / rel
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_bytes(payload.content)
        target.chmod(payload.mode)


def _plugin_payload_destinations(skill_name: str) -> list[Path]:
    if not PLUGINS_ROOT.is_dir():
        raise IntegrityError(f"plugin root is missing at {PLUGINS_ROOT}")
    return sorted(
        (
            plugin_dir / "skills" / skill_name
            for plugin_dir in PLUGINS_ROOT.iterdir()
            if plugin_dir.is_dir()
        ),
        key=lambda path: len(path.parts),
    )


def _sync_plugin_payload(
    skill_name: str,
    prepared_plugin: PreparedPlugin | None = None,
    *,
    prevalidated: bool = False,
) -> None:
    """Mirror one skill, preserving only the plugin-owned openai.yaml metadata."""
    source = SKILLS_ROOT / skill_name
    if not prevalidated:
        prepared_plugin = _validate_refresh_destinations({skill_name})[skill_name]
    if prepared_plugin is None:
        return
    destination, metadata = prepared_plugin
    if not destination.is_dir():
        raise IntegrityError(f"expected plugin package is missing: {destination}")
    shutil.rmtree(destination)
    for source_file in sorted(
        path for path in source.rglob("*") if path.is_file() and not _is_python_cache(path)
    ):
        rel = source_file.relative_to(source)
        if rel.as_posix() == "agents/openai.yaml":
            continue
        target = destination / rel
        target.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(source_file, target)
    if metadata is not None:
        metadata_path = destination / "agents" / "openai.yaml"
        metadata_path.parent.mkdir(parents=True, exist_ok=True)
        metadata_path.write_bytes(metadata.content)
        metadata_path.chmod(metadata.mode)


def _prepare_source_payloads(
    cpp_root: Path,
    *,
    commit: str | None = None,
) -> tuple[list[Path], dict[str, dict[str, PreparedPayload]], dict[str, bytes]]:
    source_root = cpp_root / PIN_PULL_SOURCE
    _assert_no_symlinks(source_root, label="source payload")
    src_dirs = _source_skill_dirs(cpp_root)
    if not src_dirs:
        raise IntegrityError(f"no generated skills under {cpp_root}")
    immutable_by_skill = _git_source_payloads(cpp_root, commit) if commit else None

    by_skill: dict[str, dict[str, PreparedPayload]] = {}
    flattened: dict[str, bytes] = {}
    for src_dir in src_dirs:
        _safe_relative_path(src_dir.name, label="source skill directory")
        immutable = immutable_by_skill[src_dir.name] if immutable_by_skill else None
        payloads = _adapted_source_payloads(src_dir, immutable)
        if not payloads:
            raise IntegrityError(f"source skill {src_dir.name} has no payload files")
        by_skill[src_dir.name] = payloads
        for rel, payload in payloads.items():
            combined = f"{src_dir.name}/{rel}"
            if combined in flattened:
                raise IntegrityError(f"duplicate prepared source path: {combined}")
            flattened[combined] = payload.content
    return src_dirs, by_skill, flattened


def _current_generated_payloads() -> dict[str, bytes]:
    _assert_destination_tree_safe(SKILLS_ROOT, label="generated skills")
    return {_rel(path): path.read_bytes() for path in _generated_files()}


def _payload_drift(expected: dict[str, bytes], actual: dict[str, bytes]) -> list[str]:
    drift: list[str] = []
    for rel in sorted(set(expected) - set(actual)):
        drift.append(f"missing generated payload: {rel}")
    for rel in sorted(set(actual) - set(expected)):
        drift.append(f"extra generated payload: {rel}")
    for rel in sorted(set(expected) & set(actual)):
        if expected[rel] != actual[rel]:
            drift.append(f"generated payload differs from adapted source: {rel}")
    return drift


def _manifest_drift(manifest: dict[str, str], actual: dict[str, bytes]) -> list[str]:
    drift: list[str] = []
    for rel in sorted(set(manifest) - set(actual)):
        drift.append(f"manifest path missing from generated payload: {rel}")
    for rel in sorted(set(actual) - set(manifest)):
        drift.append(f"generated payload missing from manifest: {rel}")
    for rel in sorted(set(manifest) & set(actual)):
        digest = hashlib.sha256(actual[rel]).hexdigest()
        if manifest[rel] != digest:
            drift.append(f"manifest digest mismatch: {rel}")
    return drift


def _packaged_skill_inventory(skill_names: set[str]) -> dict[str, Path | None]:
    """Resolve expected packages from the checked-in, versioned skill contract."""
    contract_path = REPO_ROOT / ".agents" / "skill-contracts.json"
    try:
        contract = json.loads(contract_path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise IntegrityError(f"cannot read package inventory at {contract_path}") from exc
    records = contract.get("skills")
    if not isinstance(records, list):
        raise IntegrityError("package inventory has no skills list")

    inventory: dict[str, Path | None] = {}
    for record in records:
        if not isinstance(record, dict) or record.get("name") not in skill_names:
            continue
        name = record["name"]
        if name in inventory:
            raise IntegrityError(f"package inventory has duplicate skill: {name}")
        package = record.get("package")
        if not isinstance(package, dict):
            raise IntegrityError(f"package inventory record is malformed: {name}")
        state = package.get("state")
        if state == "unpackaged":
            inventory[name] = None
            continue
        path_value = package.get("path")
        if state != "packaged" or not isinstance(path_value, str):
            raise IntegrityError(f"package inventory state is malformed: {name}")
        _safe_relative_path(path_value, label=f"package inventory path for {name}")
        destination = REPO_ROOT / path_value
        if not destination.resolve(strict=False).is_relative_to(PLUGINS_ROOT.resolve()):
            raise IntegrityError(f"package inventory path escapes plugin root: {name}")
        if destination.name != name:
            raise IntegrityError(f"package inventory path names the wrong skill: {name}")
        inventory[name] = destination

    missing = sorted(skill_names - set(inventory))
    if missing:
        raise IntegrityError(f"package inventory is missing generated skills: {missing}")
    return inventory


def _plugin_payload_drift(actual: dict[str, bytes]) -> tuple[list[str], int]:
    """Compare every inventory-declared package, exempting only UI metadata."""
    _assert_destination_tree_safe(PLUGINS_ROOT, label="plugin payloads")
    by_skill: dict[str, dict[str, bytes]] = {}
    for rel, content in actual.items():
        skill_name, separator, skill_rel = rel.partition("/")
        if not separator:
            raise IntegrityError(f"generated payload has no skill directory: {rel}")
        by_skill.setdefault(skill_name, {})[skill_rel] = content

    drift: list[str] = []
    packaged_skills = 0
    inventory = _packaged_skill_inventory(set(by_skill))
    for skill_name, destination in sorted(inventory.items()):
        if destination is None:
            continue
        expected = by_skill[skill_name]
        if not destination.is_dir():
            drift.append(f"plugin package missing: {destination.relative_to(REPO_ROOT)}")
            continue
        packaged_skills += 1
        _assert_no_symlinks(destination, label=f"plugin skill {skill_name}")
        packaged = {
            path.relative_to(destination).as_posix(): path.read_bytes()
            for path in destination.rglob("*")
            if path.is_file()
            and path.relative_to(destination).as_posix() != "agents/openai.yaml"
            and not _is_python_cache(path)
        }
        expected = {
            rel: content for rel, content in expected.items() if rel != "agents/openai.yaml"
        }
        for rel in sorted(set(expected) - set(packaged)):
            drift.append(f"plugin payload missing: {skill_name}/{rel}")
        for rel in sorted(set(packaged) - set(expected)):
            drift.append(f"plugin payload extra: {skill_name}/{rel}")
        for rel in sorted(set(expected) & set(packaged)):
            if expected[rel] != packaged[rel]:
                drift.append(f"plugin payload differs: {skill_name}/{rel}")
    return drift, packaged_skills


def _validate_refresh_destinations(
    skill_names: set[str],
) -> dict[str, PreparedPlugin | None]:
    if not PLUGINS_ROOT.is_dir():
        raise IntegrityError(f"plugin root is missing at {PLUGINS_ROOT}")
    _assert_destination_tree_safe(SKILLS_ROOT, label="generated skills")
    _assert_destination_tree_safe(PLUGINS_ROOT, label="plugin payloads")
    _assert_destination_tree_safe(VENDOR_DIR, label="provenance directory")
    _assert_publication_file_safe(PIN_PATH, label="PIN publication")
    _assert_publication_file_safe(MANIFEST_PATH, label="manifest publication")

    prepared: dict[str, PreparedPlugin | None] = {}
    for skill_name, destination in _packaged_skill_inventory(skill_names).items():
        if destination is None:
            prepared[skill_name] = None
            continue
        if not destination.is_dir():
            raise IntegrityError(
                f"expected plugin package is missing for {skill_name}: {destination}"
            )
        metadata_path = destination / "agents" / "openai.yaml"
        _assert_publication_file_safe(
            metadata_path, label=f"plugin metadata for {skill_name}"
        )
        metadata: PreparedPayload | None = None
        if metadata_path.is_file():
            try:
                metadata = PreparedPayload(
                    metadata_path.read_bytes(), metadata_path.stat().st_mode & 0o777
                )
            except OSError as exc:
                raise IntegrityError(
                    f"cannot freeze plugin metadata for {skill_name}"
                ) from exc
        prepared[skill_name] = PreparedPlugin(destination, metadata)
    return prepared


def run_pin_check(cpp_root: Path) -> int:
    """Verify immutable source, overlay, generated, manifest, and plugin parity."""
    try:
        pin = read_pin()
        manifest = read_manifest()
        if not manifest:
            raise IntegrityError("manifest is empty")
        head, tree = _validate_source_checkout(
            cpp_root, commit=pin.commit, repo=pin.repo
        )
        _, _, expected = _prepare_source_payloads(cpp_root, commit=pin.commit)
        actual = _current_generated_payloads()
        drift = _payload_drift(expected, actual)
        drift.extend(_manifest_drift(manifest, actual))
        plugin_drift, packaged_skills = _plugin_payload_drift(actual)
        drift.extend(plugin_drift)
        marker_drift = _marker_violations()
        drift.extend(f"generated marker violation: {item}" for item in marker_drift)
        if drift:
            for item in drift:
                print(f"PIN-INTEGRITY: {item}")
            raise IntegrityError(f"{len(drift)} integrity mismatch(es)")
    except IntegrityError as exc:
        print(f"codex-skills-sync: exact-pin check failed: {exc}", file=sys.stderr)
        print("CODEX_PIN_CHECK: fail")
        return 1

    overlay_digest = hashlib.sha256(Path(__file__).read_bytes()).hexdigest()
    manifest_digest = hashlib.sha256(MANIFEST_PATH.read_bytes()).hexdigest()
    print(f"PIN_REPO={pin.repo}")
    print(f"PIN_COMMIT={pin.commit}")
    print(f"SOURCE_HEAD={head}")
    print(f"SOURCE_TREE={tree}")
    print(f"OVERLAY_SHA256={overlay_digest}")
    print(f"MANIFEST_SHA256={manifest_digest}")
    print(f"PAYLOAD_FILES={len(actual)}")
    print(f"PACKAGED_SKILLS={packaged_skills}")
    print("CODEX_PIN_CHECK: ok")
    return 0


def run_source_check(cpp_root: Path) -> int:
    """Fail when the adopted generated payload differs from a CPP checkout."""
    try:
        _, _, expected = _prepare_source_payloads(cpp_root)
        actual = _current_generated_payloads()
    except IntegrityError as exc:
        print(f"codex-skills-sync: source check failed: {exc}", file=sys.stderr)
        return 2

    stale = sorted(rel for rel in set(expected) | set(actual) if expected.get(rel) != actual.get(rel))
    if stale:
        for rel in stale:
            print(f"UPSTREAM-DRIFT: .codex/skills/{rel}")
        print(
            "codex-skills-sync: vendored skills differ from the supplied CPP source;"
            " run --refresh with that checkout",
            file=sys.stderr,
        )
        return 1
    print(f"codex-skills-sync: {len(actual)} vendored file(s) current with {cpp_root}")
    return 0


def run_refresh(cpp_root: Path, ref: str) -> int:
    # All fallible integrity validation precedes the first destination write.
    # Publication spans several directories and is deliberately not described as
    # crash-atomic; this guarantee is specifically about validation failures.
    try:
        _validate_source_checkout(cpp_root, commit=ref, repo=CPP_REPO_URL)
        src_dirs, prepared_by_skill, _ = _prepare_source_payloads(cpp_root, commit=ref)
        prepared_manifest = {
            f"{skill_name}/{rel}": hashlib.sha256(payload.content).hexdigest()
            for skill_name, payloads in prepared_by_skill.items()
            for rel, payload in payloads.items()
        }
        prepared_plugins = _validate_refresh_destinations(set(prepared_by_skill))
    except IntegrityError as exc:
        print(f"codex-skills-sync: refresh validation failed: {exc}", file=sys.stderr)
        return 2

    SKILLS_ROOT.mkdir(parents=True, exist_ok=True)
    wanted = {d.name for d in src_dirs}

    # Prune generated skill dirs that no longer exist upstream (keep CxPP-owned skill dirs).
    for existing in _skill_dirs():
        if existing.name in LOCAL_SKILL_DIRS:
            continue
        if existing.name not in wanted:
            shutil.rmtree(existing)
            print(f"codex-skills-sync: pruned {existing.name} (no longer generated upstream)")

    for src_dir in src_dirs:
        dest = SKILLS_ROOT / src_dir.name
        _write_skill_payload(dest, prepared_by_skill[src_dir.name])
        _sync_plugin_payload(
            src_dir.name, prepared_plugins[src_dir.name], prevalidated=True
        )

    _write_pin(ref)
    print(
        f"codex-skills-sync: pulled {len(src_dirs)} skill(s) from {CPP_REPO_URL}@{ref[:12]}"
    )
    MANIFEST_PATH.write_text(format_manifest(prepared_manifest), encoding="utf-8")
    print(
        f"codex-skills-sync: snapshot {len(prepared_manifest)} file(s) ->"
        f" {MANIFEST_PATH.relative_to(REPO_ROOT)}"
    )
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Vendor + drift-gate the CPP-generated Codex skills (pull model)."
    )
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--check", action="store_true", help="fail on drift (default)")
    mode.add_argument("--write", action="store_true", help="re-snapshot the drift manifest")
    mode.add_argument(
        "--refresh",
        action="store_true",
        help="mirror <cpp-root>/codex/skills/ -> .codex/skills/, update PIN + manifest",
    )
    mode.add_argument(
        "--source-check",
        action="store_true",
        help="compare vendored skills with <cpp-root> after Codex runtime adaptations",
    )
    mode.add_argument(
        "--pin-check",
        action="store_true",
        help="verify the exact pinned source, generated tree, manifest, and plugin payloads",
    )
    mode.add_argument(
        "--pin-ref",
        action="store_true",
        help="print the strictly validated immutable PIN commit for safe CI checkout",
    )
    parser.add_argument(
        "--cpp-root",
        type=Path,
        help="path to a claude-power-pack checkout (with --refresh/--source-check/--pin-check)",
    )
    parser.add_argument("--ref", default="", help="the CPP commit SHA being pinned (with --refresh)")
    args = parser.parse_args(argv)

    if args.refresh:
        if args.cpp_root is None:
            parser.error("--refresh requires --cpp-root")
        if not args.ref:
            parser.error("--refresh requires --ref with the exact source commit")
        return run_refresh(args.cpp_root.expanduser(), args.ref)
    if args.source_check:
        if args.cpp_root is None:
            parser.error("--source-check requires --cpp-root")
        return run_source_check(args.cpp_root.expanduser())
    if args.pin_check:
        if args.cpp_root is None:
            parser.error("--pin-check requires --cpp-root")
        return run_pin_check(args.cpp_root.expanduser())
    if args.pin_ref:
        try:
            print(read_pin().commit)
        except IntegrityError as exc:
            print(f"codex-skills-sync: invalid PIN: {exc}", file=sys.stderr)
            return 2
        return 0
    if args.write:
        return run_write()
    return run_check()


if __name__ == "__main__":
    sys.exit(main())
