#!/usr/bin/env python3
"""Build and check the Wave 7 skill-contract inventory.

The inventory is the machine-readable input to the semantic release gate.  It
records source, installed, package, marketplace, reference, adaptation, and
exclusion state without silently treating an unexplained result as compatible.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from collections import Counter, defaultdict
from pathlib import Path
from typing import Any

import yaml

REPO_ROOT = Path(__file__).resolve().parent.parent
SOURCE_ROOT = REPO_ROOT / ".codex" / "skills"
PLUGINS_ROOT = REPO_ROOT / "plugins"
MARKETPLACE_PATH = REPO_ROOT / ".agents" / "plugins" / "marketplace.json"
CONTRACT_PATH = REPO_ROOT / ".agents" / "skill-contracts.json"
EVALUATION_PATH = REPO_ROOT / ".agents" / "skill-evaluation-cases.json"
INVOCATION_POLICY_PATH = REPO_ROOT / ".agents" / "skill-invocation-policy.json"
REPORT_PATH = REPO_ROOT / "docs" / "skill-contract-baseline.md"

SCHEMA_VERSION = "1.0"
BASELINE_CAPTURED_AT = "2026-08-06T19:21:59Z"
BASELINE_COMMIT = "b98934be8f8a654d65d1728207fadc1597ad8c7c"
BASELINE_ISSUE = 157
BASELINE_OWNER = "Codex Power Pack maintainers"
REVIEW_BY = "2026-09-30"
EXCLUSION_REVIEW_BY = "2027-03-31"
EXCLUSION_TRACKING_ISSUE = 173

GENERATED_MARKER = "<!-- GENERATED by claude-power-pack"
EXPLICIT_SKILL_RE = re.compile(r"\$([a-z][a-z0-9_]*(?:-[a-z0-9_]+)+)")
NAMESPACED_COMMAND_RE = re.compile(r"(?<![A-Za-z0-9.])/(?!/)([a-z][a-z0-9_-]+):([a-z][a-z0-9_-]+)")

NATIVE_COMMANDS = {
    "/fewer-permission-prompts",
    "/permissions",
    "/plan",
    "/skills",
}
CLAUDE_HOST_COMMANDS = {"/plugin"}
HOST_TOOLS = {
    "AskUserQuestion",
    "EnterWorktree",
    "ExitWorktree",
    "WebFetch",
    "WebSearch",
}
HOST_PATH_PATTERNS = {
    "CLAUDE_PLUGIN_ROOT": re.compile(r"\bCLAUDE_PLUGIN_ROOT\b"),
    ".claude/": re.compile(r"(?<![A-Za-z0-9_-])(?:~/)?\.claude/"),
    "fixed-claude-power-pack-runtime": re.compile(
        r"(?:\$HOME|~)/Projects/claude-power-pack|/opt/claude-power-pack|~/\.claude-power-pack"
    ),
}

EXCLUSION_DECISIONS = {
    "browser-help": {
        "rationale": "Replace: Codex browser orientation is covered by the native Playwright MCP workflow.",
        "replacement": "qa-help and upstream Playwright MCP guidance",
    },
    "browser-session": {
        "rationale": (
            "Keep source-only: named concurrent authenticated sessions remain distinct, but no measured demand or "
            "activation evidence justifies packaging."
        ),
        "replacement": "qa-test for single-session QA; no packaged replacement for named concurrent sessions",
    },
    "cicd-woodpecker": {
        "rationale": (
            "Replace: supported Woodpecker pipeline generation and client operations are split across narrower "
            "skills; CxPP does not own server or agent lifecycle."
        ),
        "replacement": "cicd-pipeline and the explicit woodpecker client skills",
    },
    "cpp-dockers": {
        "rationale": (
            "Retire: whole-daemon inspection and the retired CPP Docker runtime are outside CxPP's host-runtime "
            "boundary."
        ),
        "replacement": "no CxPP replacement; use host Docker tooling and cxpp-status for CxPP services",
    },
    "cpp-happy-check": {
        "rationale": (
            "Retire: third-party Happy CLI currency is outside CxPP ownership and has no measured CxPP demand."
        ),
        "replacement": "no CxPP replacement; use the Happy CLI update workflow outside CxPP",
    },
    "cpp-help": {
        "rationale": "Replace: a global catch-all would duplicate the bounded packaged family help skills.",
        "replacement": "the packaged family help skills",
    },
    "cpp-load-best-practices": {
        "rationale": "Replace: Codex uses focused instructions and documentation instead of a Claude context loader.",
        "replacement": "AGENTS.md and focused Codex documentation",
    },
    "cpp-load-mcp-docs": {
        "rationale": "Replace: MCP discovery is host-managed and does not need a Claude context loader.",
        "replacement": "docs/HOST_MANAGED.md and second-opinion-help",
    },
    "flow-auto_codex": {
        "rationale": (
            "Replace: a second full-lifecycle entrypoint would duplicate flow-auto; claude-code-review is not an "
            "automatic Codex pre-PR stage."
        ),
        "replacement": "flow-auto plus separately and explicitly selected claude-code-review",
    },
    "flow-repair": {
        "rationale": "Replace: Codex flow packages bundle helpers and do not install Claude stable-path scripts.",
        "replacement": "bundled flow helpers, flow-doctor, and reinstall or cxpp-update",
    },
}

EXCLUSION_OWNER = "Codex Power Pack maintainers"


def _load_json(path: Path) -> dict[str, Any]:
    payload = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(payload, dict):
        raise ValueError(f"{path}: expected a JSON object")
    return payload


def _relative(path: Path) -> str:
    return path.relative_to(REPO_ROOT).as_posix()


def _source_skills() -> dict[str, Path]:
    return {
        path.name: path
        for path in sorted(SOURCE_ROOT.iterdir())
        if path.is_dir() and (path / "SKILL.md").is_file()
    }


def _packaged_skills() -> dict[str, dict[str, Any]]:
    packaged: dict[str, dict[str, Any]] = {}
    for skill_md in sorted(PLUGINS_ROOT.glob("*/skills/*/SKILL.md")):
        plugin = skill_md.parents[2].name
        name = skill_md.parent.name
        metadata_path = skill_md.parent / "agents" / "openai.yaml"
        metadata = yaml.safe_load(metadata_path.read_text(encoding="utf-8"))
        if not isinstance(metadata, dict):
            raise ValueError(f"{metadata_path}: expected a YAML mapping")
        interface = metadata.get("interface", {})
        policy = metadata.get("policy", {})
        short_description = str(interface.get("short_description", ""))
        packaged[name] = {
            "plugin": plugin,
            "path": skill_md.parent,
            "metadata_path": metadata_path,
            "implicit": policy.get("allow_implicit_invocation") is True,
            "short_description": short_description,
            "metadata_bytes": len(f"{plugin}:{name}: {short_description}".encode("utf-8")),
        }
    return packaged


def _marketplace() -> tuple[dict[str, Any], dict[str, dict[str, Any]]]:
    payload = _load_json(MARKETPLACE_PATH)
    entries = {entry["name"]: entry for entry in payload["plugins"]}
    return payload, entries


def _invocation_policy(packaged: dict[str, dict[str, Any]]) -> dict[str, Any]:
    policy = _load_json(INVOCATION_POLICY_PATH)
    expected = {entry["name"] for entry in policy["implicit_entrypoints"]}
    actual = {name for name, package in packaged.items() if package["implicit"]}
    if actual != expected:
        raise ValueError(
            "implicit metadata differs from .agents/skill-invocation-policy.json: "
            f"expected={sorted(expected)}, actual={sorted(actual)}"
        )
    unknown = expected - set(packaged)
    if unknown:
        raise ValueError(f"implicit policy names unpackaged skills: {sorted(unknown)}")
    return policy


def _adapted_skills(sources: dict[str, Path]) -> set[str]:
    return {
        name
        for name, path in sources.items()
        if "## Codex harness adaptations" in (path / "SKILL.md").read_text(encoding="utf-8")
    }


def _is_generated_source_context(line: str) -> bool:
    return GENERATED_MARKER in line and ".claude/commands/" in line


def _is_legacy_context(line: str) -> bool:
    lowered = line.casefold()
    return (
        "legacy" in lowered
        or "historical" in lowered
        or "source context" in lowered
        or ("optional" in lowered and ".claude/friction" in lowered)
    )


def _reference(
    *,
    source_skill: str,
    path: Path,
    line: int,
    token: str,
    kind: str,
    target: str,
    classification: str,
) -> dict[str, Any]:
    return {
        "source_skill": source_skill,
        "path": _relative(path),
        "line": line,
        "token": token,
        "kind": kind,
        "target": target,
        "classification": classification,
    }


def _extract_references(
    sources: dict[str, Path], packaged: dict[str, dict[str, Any]]
) -> list[dict[str, Any]]:
    source_names = set(sources)
    packaged_names = set(packaged)
    adapted = _adapted_skills(sources)
    command_namespaces = {package["plugin"] for package in packaged.values()} | {"codex", "cpp"}
    bare_skill_re = re.compile(
        r"(?<![A-Za-z0-9.])/(?!/)("
        + "|".join(re.escape(name) for name in sorted(source_names, key=len, reverse=True))
        + r")(?![A-Za-z0-9_-])"
    )
    native_re = re.compile("|".join(re.escape(value) for value in sorted(NATIVE_COMMANDS, key=len, reverse=True)))
    claude_command_re = re.compile(
        r"(?<![A-Za-z0-9_.-])(?:"
        + "|".join(re.escape(value) for value in sorted(CLAUDE_HOST_COMMANDS, key=len, reverse=True))
        + r")(?![A-Za-z0-9_-])"
    )

    references: list[dict[str, Any]] = []
    seen: set[tuple[str, str, int, str, str]] = set()

    def add(item: dict[str, Any]) -> None:
        key = (item["source_skill"], item["path"], item["line"], item["token"], item["kind"])
        if key not in seen:
            seen.add(key)
            references.append(item)

    for source_skill, package in sorted(packaged.items()):
        package_path: Path = package["path"]
        has_adaptation = source_skill in adapted
        for markdown_path in sorted(package_path.rglob("*.md")):
            for line_number, line in enumerate(markdown_path.read_text(encoding="utf-8").splitlines(), start=1):
                for match in EXPLICIT_SKILL_RE.finditer(line):
                    target = match.group(1)
                    if target == "skill-name":
                        classification = "example"
                    elif target in packaged_names:
                        classification = "resolvable"
                    elif target in EXCLUSION_DECISIONS:
                        classification = "excluded"
                    else:
                        classification = "unexplained"
                    add(
                        _reference(
                            source_skill=source_skill,
                            path=markdown_path,
                            line=line_number,
                            token=match.group(0),
                            kind="skill",
                            target=target,
                            classification=classification,
                        )
                    )

                for match in NAMESPACED_COMMAND_RE.finditer(line):
                    if match.group(1) not in command_namespaces:
                        continue
                    target = f"{match.group(1)}-{match.group(2)}"
                    add(
                        _reference(
                            source_skill=source_skill,
                            path=markdown_path,
                            line=line_number,
                            token=match.group(0),
                            kind="legacy_skill_command",
                            target=target,
                            classification="unexplained",
                        )
                    )

                for match in bare_skill_re.finditer(line):
                    target = match.group(1)
                    add(
                        _reference(
                            source_skill=source_skill,
                            path=markdown_path,
                            line=line_number,
                            token=match.group(0),
                            kind="legacy_skill_command",
                            target=target,
                            classification="unexplained",
                        )
                    )

                for match in native_re.finditer(line):
                    add(
                        _reference(
                            source_skill=source_skill,
                            path=markdown_path,
                            line=line_number,
                            token=match.group(0),
                            kind="native_command",
                            target=match.group(0),
                            classification="native",
                        )
                    )

                for match in claude_command_re.finditer(line):
                    classification = (
                        "source_context"
                        if _is_generated_source_context(line) or _is_legacy_context(line)
                        else "adapted"
                        if has_adaptation
                        else "unexplained"
                    )
                    add(
                        _reference(
                            source_skill=source_skill,
                            path=markdown_path,
                            line=line_number,
                            token=match.group(0),
                            kind="host_command",
                            target=match.group(0),
                            classification=classification,
                        )
                    )

                for tool in HOST_TOOLS:
                    if re.search(rf"\b{re.escape(tool)}\b", line):
                        add(
                            _reference(
                                source_skill=source_skill,
                                path=markdown_path,
                                line=line_number,
                                token=tool,
                                kind="host_command",
                                target=tool,
                                classification="adapted" if has_adaptation else "unexplained",
                            )
                        )

                for token, pattern in HOST_PATH_PATTERNS.items():
                    if pattern.search(line):
                        classification = (
                            "source_context"
                            if _is_generated_source_context(line) or _is_legacy_context(line)
                            else "adapted"
                            if has_adaptation
                            else "unexplained"
                        )
                        add(
                            _reference(
                                source_skill=source_skill,
                                path=markdown_path,
                                line=line_number,
                                token=token,
                                kind="host_path",
                                target=token,
                                classification=classification,
                            )
                        )

    references.sort(key=lambda item: (item["source_skill"], item["path"], item["line"], item["token"]))
    for index, item in enumerate(references, start=1):
        item["id"] = f"REF-{index:04d}"
    return references


def _aliases(name: str, plugin: str | None) -> list[dict[str, str]]:
    if plugin is None:
        return []
    suffix = name.removeprefix(f"{plugin}-")
    aliases = [
        {"value": f"${name}", "state": "supported"},
        {"value": f"{plugin}:{name}", "state": "display_only"},
        {"value": f"/{name}", "state": "legacy_unsupported"},
        {"value": f"/{plugin}:{suffix}", "state": "legacy_unsupported"},
    ]
    unique = {(item["value"], item["state"]): item for item in aliases}
    return [unique[key] for key in sorted(unique)]


def _exclusion(name: str, packaged: bool) -> dict[str, Any]:
    if packaged:
        return {
            "state": "not_excluded",
            "owner": None,
            "rationale": None,
            "replacement": None,
            "review_by": None,
            "tracking_issue": None,
        }
    decision = EXCLUSION_DECISIONS[name]
    return {
        "state": "excluded",
        "owner": EXCLUSION_OWNER,
        "rationale": decision["rationale"],
        "replacement": decision["replacement"],
        "review_by": EXCLUSION_REVIEW_BY,
        "tracking_issue": EXCLUSION_TRACKING_ISSUE,
    }


def _gaps(
    sources: dict[str, Path], packaged: dict[str, dict[str, Any]], references: list[dict[str, Any]]
) -> list[dict[str, Any]]:
    gaps: list[dict[str, Any]] = []
    for name in sorted(set(sources) - set(packaged)):
        decision = EXCLUSION_DECISIONS[name]
        gaps.append(
            {
                "type": "unpackaged_skill",
                "subject": name,
                "owner": EXCLUSION_OWNER,
                "disposition": f"{decision['rationale']} Replacement: {decision['replacement']}.",
                "tracking_issue": EXCLUSION_TRACKING_ISSUE,
                "review_by": EXCLUSION_REVIEW_BY,
                "status": "reviewed_exclusion",
                "evidence": [_relative(sources[name] / "SKILL.md")],
            }
        )

    grouped: dict[tuple[str, str], list[dict[str, Any]]] = defaultdict(list)
    for reference in references:
        if reference["classification"] == "unexplained":
            grouped[(reference["kind"], reference["token"])].append(reference)

    for (kind, token), items in sorted(grouped.items()):
        tracking_issue = 159 if kind == "legacy_skill_command" else 160
        owner = "Wave 7 Stage 2" if tracking_issue == 159 else "Wave 7 Stage 3"
        disposition = (
            "Replace legacy slash-style skill invocation with `$skill-name` or `/skills`."
            if tracking_issue == 159
            else "Resolve to a packaged/native capability, add a narrow adaptation, or record a reviewed exclusion."
        )
        gaps.append(
            {
                "type": "unexplained_reference",
                "subject": token,
                "owner": owner,
                "disposition": disposition,
                "tracking_issue": tracking_issue,
                "review_by": REVIEW_BY,
                "status": "scheduled",
                "evidence": sorted({f"{item['path']}:{item['line']}" for item in items}),
            }
        )

    for index, gap in enumerate(gaps, start=1):
        gap["id"] = f"GAP-{index:03d}"
    return gaps


def build_contract() -> dict[str, Any]:
    sources = _source_skills()
    packaged = _packaged_skills()
    _invocation_policy(packaged)
    marketplace, marketplace_entries = _marketplace()
    references = _extract_references(sources, packaged)
    refs_by_skill: dict[str, set[str]] = defaultdict(set)
    for reference in references:
        if reference["target"] in sources and reference["target"] != reference["source_skill"]:
            refs_by_skill[reference["source_skill"]].add(reference["target"])

    skills: list[dict[str, Any]] = []
    for name, source_path in sorted(sources.items()):
        package = packaged.get(name)
        plugin = package["plugin"] if package else None
        published = plugin in marketplace_entries if plugin else False
        skills.append(
            {
                "name": name,
                "source": {
                    "path": _relative(source_path),
                    "ownership": (
                        "generated"
                        if GENERATED_MARKER in (source_path / "SKILL.md").read_text(encoding="utf-8")
                        else "native"
                    ),
                },
                "installed": {
                    "state": "present",
                    "path": _relative(source_path),
                },
                "package": {
                    "state": "packaged" if package else "unpackaged",
                    "plugin": plugin,
                    "path": _relative(package["path"]) if package else None,
                },
                "marketplace": {
                    "state": "published" if published else "unpublished",
                    "plugin": plugin,
                },
                "implicit": {
                    "state": (
                        "enabled" if package and package["implicit"] else "disabled" if package else "not_packaged"
                    ),
                    "metadata_path": _relative(package["metadata_path"]) if package else None,
                    "metadata_bytes": package["metadata_bytes"] if package else 0,
                },
                "aliases": _aliases(name, plugin),
                "dependencies": sorted(refs_by_skill[name]),
                "exclusion": _exclusion(name, package is not None),
            }
        )

    plugin_inventory = []
    for name, entry in sorted(marketplace_entries.items()):
        plugin_path = REPO_ROOT / entry["source"]["path"]
        plugin_inventory.append(
            {
                "name": name,
                "path": _relative(plugin_path),
                "state": "published" if plugin_path.is_dir() else "missing",
            }
        )

    return {
        "$schema": "./skill-contracts.schema.json",
        "schema_version": SCHEMA_VERSION,
        "generated_at": BASELINE_CAPTURED_AT,
        "baseline": {
            "source_commit": BASELINE_COMMIT,
            "tracking_issue": BASELINE_ISSUE,
            "owner": BASELINE_OWNER,
        },
        "summary": {
            "source_skills": len(sources),
            "packaged_skills": len(packaged),
            "unpackaged_skills": len(set(sources) - set(packaged)),
            "marketplace_plugins": len(marketplace_entries),
            "implicit_skills": sum(1 for package in packaged.values() if package["implicit"]),
            "references": len(references),
            "unexplained_references": sum(
                reference["classification"] == "unexplained" for reference in references
            ),
        },
        "marketplace": {
            "path": _relative(MARKETPLACE_PATH),
            "name": marketplace["name"],
            "plugins": plugin_inventory,
        },
        "skills": skills,
        "references": references,
        "gaps": _gaps(sources, packaged, references),
    }


def render_report(contract: dict[str, Any]) -> str:
    evaluation = _load_json(EVALUATION_PATH)["captures"][0]
    policy = _load_json(INVOCATION_POLICY_PATH)
    fresh_capture = policy["fresh_full_suite_capture"]
    implicit_names = ", ".join(f"`${entry['name']}`" for entry in policy["implicit_entrypoints"])
    summary = contract["summary"]
    classifications = Counter(reference["classification"] for reference in contract["references"])
    unpackaged = [gap for gap in contract["gaps"] if gap["type"] == "unpackaged_skill"]
    unexplained = [gap for gap in contract["gaps"] if gap["type"] == "unexplained_reference"]

    lines = [
        "# Skill Contract Baseline",
        "",
        f"> Captured {evaluation['captured_at']} from `{evaluation['source_commit']}` for issue #{BASELINE_ISSUE}.",
        "> This report records evidence and dispositions; it does not change skill runtime behavior.",
        "",
        "## Inventory",
        "",
        "| Surface | Count |",
        "|---|---:|",
        f"| Source skills | {summary['source_skills']} |",
        f"| Packaged skills | {summary['packaged_skills']} |",
        f"| Unpackaged source skills | {summary['unpackaged_skills']} |",
        f"| Marketplace plugins | {summary['marketplace_plugins']} |",
        f"| Implicitly eligible packaged skills | {summary['implicit_skills']} |",
        f"| Extracted packaged-Markdown references | {summary['references']} |",
        f"| Unexplained reference occurrences | {summary['unexplained_references']} |",
        "",
        "The machine-readable source of truth is [`.agents/skill-contracts.json`](../.agents/skill-contracts.json).",
        "",
        "## Current Invocation Policy",
        "",
        f"Payload `{policy['payload_version']}` keeps {implicit_names} "
        "implicitly eligible. Every other packaged skill remains available through explicit "
        "`$skill-name` selection or `/skills` discovery. Plugin metadata changes require an "
        "upgrade or reinstall followed by a new Codex session.",
        "",
        "The versioned source of truth is "
        "[`.agents/skill-invocation-policy.json`](../.agents/skill-invocation-policy.json).",
        "",
        "## Current Fresh Full-Suite Capture",
        "",
        f"An isolated `{fresh_capture['codex_version']}` full-profile install captured at "
        f"`{fresh_capture['captured_at']}` exposed {fresh_capture['total_entries']} entries: "
        f"{fresh_capture['cxpp_entries']} CxPP and {fresh_capture['system_entries']} system entries. "
        f"Skill entry lines consumed {fresh_capture['entry_metadata_bytes']:,} bytes; the framed Skills section "
        f"consumed {fresh_capture['skills_section_bytes']:,} bytes. The focused fresh-install tests reproduce "
        "the profile inventory and enforce the policy budgets.",
        "",
        "## Stage 0 Full-Suite Prompt Capture",
        "",
        f"An isolated `{evaluation['codex_version']}` full-suite install exposed "
        f"{evaluation['inventory']['total_entries']} entries: {evaluation['inventory']['cxpp_entries']} CxPP and "
        f"{evaluation['inventory']['system_entries']} system entries. Skill entry lines consumed "
        f"{evaluation['inventory']['entry_metadata_bytes']:,} bytes; the framed Skills section consumed "
        f"{evaluation['inventory']['skills_section_bytes']:,} bytes.",
        "",
        "Prompt presence passed. Direct recall, indirect recall, and negative precision remain explicitly unmeasured "
        "until issue #161 supplies the bounded live evaluator; this baseline does not turn absence of measurement "
        "into green.",
        "",
        "## Unpackaged Skills",
        "",
        "| Skill | Owner | Disposition | Review by |",
        "|---|---|---|---|",
    ]
    lines.extend(
        f"| `{gap['subject']}` | {gap['owner']} (#{gap['tracking_issue']}) | "
        f"{gap['disposition']} | {gap['review_by']} |"
        for gap in unpackaged
    )
    lines.extend(
        [
            "",
            "The post-release evidence and decision record is "
            "[`wave-7-exclusion-review.md`](wave-7-exclusion-review.md).",
            "",
            "## Reference Classification",
            "",
            "| Classification | Occurrences | Meaning |",
            "|---|---:|---|",
            f"| Resolvable | {classifications['resolvable']} | Explicit `$skill-name` resolves to a packaged skill. |",
            f"| Native | {classifications['native']} | Supported Codex host command. |",
            f"| Adapted | {classifications['adapted']} | The packaged skill carries an explicit Codex harness "
            "adaptation. |",
            f"| Excluded | {classifications['excluded']} | Target has a reviewed, owned, time-bound exclusion. |",
            f"| Source context | {classifications['source_context']} | Non-operational provenance or migration text. |",
            f"| Example | {classifications['example']} | Documented placeholder syntax, not a dependency. |",
            f"| Unexplained | {classifications['unexplained']} | Scheduled for invocation normalization or semantic "
            "review. |",
            "",
            "Unexplained occurrences are grouped below so every gap has one owner and disposition without hiding "
            "its evidence locations.",
            "",
            "| Token | Evidence count | Owner | Disposition | Review by |",
            "|---|---:|---|---|---|",
        ]
    )
    lines.extend(
        f"| `{gap['subject']}` | {len(gap['evidence'])} | {gap['owner']} (#{gap['tracking_issue']}) | "
        f"{gap['disposition']} | {gap['review_by']} |"
        for gap in unexplained
    )
    lines.extend(
        [
            "",
            "## Stage 0 Known Failures and Owners",
            "",
            "| ID | Finding | Owner | Disposition |",
            "|---|---|---|---|",
        ]
    )
    lines.extend(
        f"| {failure['id']} | {failure['summary']} | {failure['owner']} (#{failure['tracking_issue']}) | "
        f"{failure['disposition']} |"
        for failure in evaluation["known_failures"]
    )
    lines.extend(
        [
            "",
            "## Evaluation Contract",
            "",
            "[`.agents/skill-evaluation-cases.schema.json`](../.agents/skill-evaluation-cases.schema.json) versions "
            "direct, indirect, negative, incomplete, and edge cases. "
            "[`.agents/skill-evaluation-cases.json`](../.agents/skill-evaluation-cases.json) preserves this capture, "
            "including honest `not_run` activation results for Stage 4 to replace with measurements.",
            "",
            "## Reproduction",
            "",
            "```bash",
            "uv run --extra dev python scripts/skill_contract_baseline.py --check",
            "```",
            "",
            "Use `--write` only when intentionally reconciling the current source/package/reference manifest. "
            "Do not rewrite the dated evaluation capture when runtime behavior changes; add a new capture instead.",
            "",
        ]
    )
    return "\n".join(lines)


def _json_text(payload: dict[str, Any]) -> str:
    return json.dumps(payload, indent=2, sort_keys=False, ensure_ascii=False) + "\n"


def run_check() -> int:
    expected_contract = _json_text(build_contract())
    expected_report = render_report(json.loads(expected_contract))
    failures = []
    if CONTRACT_PATH.read_text(encoding="utf-8") != expected_contract:
        failures.append(_relative(CONTRACT_PATH))
    if REPORT_PATH.read_text(encoding="utf-8") != expected_report:
        failures.append(_relative(REPORT_PATH))
    if failures:
        print("skill-contract-baseline: stale generated files: " + ", ".join(failures), file=sys.stderr)
        print("Run: uv run --extra dev python scripts/skill_contract_baseline.py --write", file=sys.stderr)
        return 1
    print(
        "skill-contract-baseline: current "
        f"({len(json.loads(expected_contract)['skills'])} skills, "
        f"{len(json.loads(expected_contract)['references'])} references)"
    )
    return 0


def run_write() -> int:
    contract = build_contract()
    CONTRACT_PATH.write_text(_json_text(contract), encoding="utf-8")
    REPORT_PATH.write_text(render_report(contract), encoding="utf-8")
    print(f"wrote {_relative(CONTRACT_PATH)} and {_relative(REPORT_PATH)}")
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--check", action="store_true", help="fail when generated baseline files are stale")
    mode.add_argument("--write", action="store_true", help="reconcile generated baseline files")
    args = parser.parse_args(argv)
    return run_write() if args.write else run_check()


if __name__ == "__main__":
    raise SystemExit(main())
